// Conform queue I/O: read/write/upsert/mutate for standards-drift.md and
// standards-backlog.md, header constants, acknowledgement markers, audit
// log, pending-evaluation cache, and queue mutation helpers.
//
// Mirrors tools/drift/queue.js but specialized for conform's per-rule entry
// shape (queueKey = `<standard_id>.<rule_id>`, files grouped by party for
// contracts). Baseline helpers (parseBaseline/setBaseline) live here rather
// than a separate baseline.js because conform has only the parse/set pair
// and the dedup logic — no SHA descent math like drift.

const fs = require('fs')
const path = require('path')
const { KB_ROOT } = require('../../lib/kb-constants')

const STANDARDS_DRIFT_PATH = path.join(KB_ROOT, 'sync/standards-drift.md')
const STANDARDS_BACKLOG_PATH = path.join(KB_ROOT, 'sync/standards-backlog.md')
const DRIFT_LOG_DIR = path.join(KB_ROOT, 'sync/drift-log')
const PENDING_DIR = path.join(KB_ROOT, 'sync/.conform-pending')

const STANDARDS_DRIFT_HEADER = `<!-- AUTO-GENERATED by kb-mcp — resolve via kb_conform in Claude. Do not delete entries manually. -->

# Standards Drift Queue

Code touched in the current diff window violates one or more standards rules.
Review-required before PR merge.

> **Before opening a PR:** resolve entries by running \`kb_conform\` and
> picking \`applied\`, \`exempted\`, \`promoted\`, or \`dismissed\` per entry.

> **On merge conflicts:** queue files use \`merge=union\` — different entries from different branches coalesce automatically. Same-entry collisions are real and intentional. The post-merge git hook collapses duplicate baseline lines.

`

const STANDARDS_BACKLOG_HEADER = `<!-- AUTO-GENERATED by kb-mcp — surfaced advisorily by kb_get when editing affected files. -->

# Standards Backlog

Aspirational entries from retroactive sweeps when standards are tightened.
Advisory — fix opportunistically when next editing the affected files.

> **On merge conflicts:** queue files use \`merge=union\` — different entries from different branches coalesce automatically. Same-entry collisions are real and intentional.

`

const BASELINE_RE = /<!--\s*baseline:\s*([a-f0-9]+)\s*-->/gi

// ── Header / baseline helpers ─────────────────────────────────────────────────

function parseBaseline(header) {
  const matches = [...header.matchAll(BASELINE_RE)]
  return matches.length > 0 ? matches[matches.length - 1][1] : null
}

function setBaseline(header, sha) {
  const stripped = header.replace(BASELINE_RE, '').replace(/\n{3,}/g, '\n\n')
  if (/<!-- AUTO-GENERATED[^\n]*-->\n/.test(stripped)) {
    return stripped.replace(/(<!-- AUTO-GENERATED[^\n]*-->\n)/, `$1<!-- baseline: ${sha} -->\n`)
  }
  return `<!-- baseline: ${sha} -->\n` + stripped
}

function ensureHeader(filePath, header) {
  if (!fs.existsSync(filePath)) {
    fs.mkdirSync(path.dirname(filePath), { recursive: true })
    fs.writeFileSync(filePath, header, 'utf8')
    return
  }
  const content = fs.readFileSync(filePath, 'utf8')
  if (content.startsWith('<!-- AUTO-GENERATED')) return
  const preserved = parseBaseline(content)
  const newHeader = preserved ? setBaseline(header, preserved) : header
  fs.writeFileSync(filePath, newHeader + content, 'utf8')
}

// ── Acknowledgement marker — shared format across all queues ─────────────────
// Same syntax as in drift.js so reviewers learn one shape across the three
// queue files (code-drift, kb-drift, standards-drift).

const ACK_LINE_RE = /\*\*Acknowledged\*\*:\s*@(\S+)\s+at\s+`([^`]+)`\s+\(([^)]+)\)\s+—\s+"([^"]+)"/

function parseAcknowledgement(block) {
  const m = block.match(ACK_LINE_RE)
  if (!m) return null
  return { by: m[1], atCommit: m[2], atDate: m[3], reason: m[4] }
}

function formatAcknowledgement(ack) {
  const reason = (ack.reason || '').replace(/"/g, '\\"')
  return `- **Acknowledged**: @${ack.by} at \`${ack.atCommit}\` (${ack.atDate}) — "${reason}"`
}

// ── Queue parse / serialize ───────────────────────────────────────────────────
//
// Entry shape (markdown):
//
//   ## <standard-id>.<rule-id>
//
//   - **Standard:** `<standard-id>` (kind)
//   - **Rule:** `<rule-id>` — <severity>
//   - **Files:**
//     - `path/to/file.ext` — since `<sha>` (<date>)[, latest `<sha>` (<date>)]
//   - **Files (party: backend):**         (only for contracts)
//     - `...`
//   - **Reason:** <one-line summary from latest judgment>

function readQueue(filePath, header) {
  ensureHeader(filePath, header)
  const content = fs.readFileSync(filePath, 'utf8')
  const headerEnd = content.indexOf('\n## ')
  const hdr = headerEnd === -1 ? content : content.slice(0, headerEnd)
  const entriesStr = headerEnd === -1 ? '' : content.slice(headerEnd + 1)
  const blocks = entriesStr.split(/\n(?=## )/).filter(b => b.trim())

  const entries = blocks.map(block => {
    const headingMatch = block.match(/^## (.+)/)
    const queueKey = headingMatch ? headingMatch[1].trim() : null
    const stdMatch = block.match(/\*\*Standard:\*\*\s*`([^`]+)`(?:\s*\(([^)]+)\))?/)
    const ruleMatch = block.match(/\*\*Rule:\*\*\s*`([^`]+)`\s*—\s*(\w+)/)
    const reasonMatch = block.match(/\*\*Reason:\*\*\s*(.+?)(?:\n|$)/)
    const acknowledgement = parseAcknowledgement(block)

    // Files can be in a single "Files:" block OR per-party "Files (party: X):" blocks
    const filesByParty = {} // null key for non-contract single block
    const lines = block.split('\n')
    let currentParty = null
    let inFiles = false
    for (const line of lines) {
      const partyMatch = line.match(/^- \*\*Files(?:\s*\(party:\s*([^)]+)\))?:\*\*/)
      if (partyMatch) {
        inFiles = true
        currentParty = partyMatch[1] || null
        if (!filesByParty[currentParty || '_']) filesByParty[currentParty || '_'] = []
        continue
      }
      if (/^- \*\*/.test(line)) { inFiles = false; continue }
      if (!inFiles) continue
      const m = line.match(/^\s+-\s+`([^`]+)`\s+—\s+since\s+`([^`]+)`\s+\(([^)]+)\)(?:,\s+latest\s+`([^`]+)`\s+\(([^)]+)\))?(?:\s+—\s+by\s+@(\S+))?/)
      if (m) {
        const partyKey = currentParty || '_'
        filesByParty[partyKey].push({
          path: m[1],
          sinceCommit: m[2],
          sinceDate: m[3],
          ...(m[4] && { latestCommit: m[4], latestDate: m[5] }),
          ...(m[6] && { author: m[6] })
        })
      }
    }

    return {
      queueKey,
      standardId: stdMatch ? stdMatch[1] : null,
      standardKind: stdMatch ? stdMatch[2] : null,
      ruleId: ruleMatch ? ruleMatch[1] : null,
      severity: ruleMatch ? ruleMatch[2] : null,
      reason: reasonMatch ? reasonMatch[1].trim() : null,
      filesByParty,
      ...(acknowledgement && { acknowledgement })
    }
  }).filter(e => e.queueKey)

  return { header: hdr, entries }
}

function writeQueue(filePath, header, entries) {
  const body = entries.map(entry => {
    const partyKeys = Object.keys(entry.filesByParty || {})
    let filesBlock = ''
    if (partyKeys.length === 0) {
      filesBlock = '- **Files:**\n  - _(empty)_'
    } else if (partyKeys.length === 1 && partyKeys[0] === '_') {
      const fileLines = entry.filesByParty._.map(f => formatFileLine(f))
      filesBlock = `- **Files:**\n${fileLines.join('\n')}`
    } else {
      const blocks = partyKeys.sort().map(party => {
        const label = party === '_' ? '' : ` (party: ${party})`
        const fileLines = entry.filesByParty[party].map(f => formatFileLine(f))
        return `- **Files${label}:**\n${fileLines.join('\n')}`
      })
      filesBlock = blocks.join('\n')
    }
    const kindNote = entry.standardKind ? ` (${entry.standardKind})` : ''
    const reasonLine = entry.reason ? `\n- **Reason:** ${entry.reason}` : ''
    const ackLine = entry.acknowledgement ? `\n${formatAcknowledgement(entry.acknowledgement)}` : ''
    return `## ${entry.queueKey}\n\n- **Standard:** \`${entry.standardId}\`${kindNote}\n- **Rule:** \`${entry.ruleId}\` — ${entry.severity || 'warn'}\n${filesBlock}${reasonLine}${ackLine}`
  }).join('\n\n')

  fs.writeFileSync(filePath, header + (body ? '\n' + body + '\n' : ''), 'utf8')
}

function formatFileLine(f) {
  const latestNote = f.latestCommit && f.latestCommit !== f.sinceCommit
    ? `, latest \`${f.latestCommit}\` (${f.latestDate})`
    : ''
  const authorNote = f.author ? ` — by @${f.author}` : ''
  return `  - \`${f.path}\` — since \`${f.sinceCommit}\` (${f.sinceDate})${latestNote}${authorNote}`
}

// ── Audit log ────────────────────────────────────────────────────────────────

function getDriftLogPath() {
  const d = new Date()
  const month = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`
  return path.join(DRIFT_LOG_DIR, `${month}.md`)
}

function appendToDriftLog(entries) {
  if (!fs.existsSync(DRIFT_LOG_DIR)) fs.mkdirSync(DRIFT_LOG_DIR, { recursive: true })
  const logPath = getDriftLogPath()
  const DRIFT_LOG_HEADER = `<!-- AUTO-GENERATED audit trail — do not edit manually. -->\n\n# Drift Log\n\nResolved drift events. Append-only.\n\n`
  ensureHeader(logPath, DRIFT_LOG_HEADER)
  const date = new Date().toISOString().split('T')[0]
  let block = ''
  for (const entry of entries) {
    if (entry.event_type === 'conformed') {
      block += `\n## ${date} · CONFORMED · ${entry.resolution}\n`
      block += `\n- **Queue key:** \`${entry.queue_key}\``
      if (entry.file_paths) block += `\n- **Files:** ${entry.file_paths.map(f => `\`${f}\``).join(', ')}`
      if (entry.originating_files) block += `\n- **Originating files:** ${entry.originating_files.map(f => `\`${f}\``).join(', ')}`
      if (entry.reason) block += `\n- **Reason:** ${entry.reason}`
      if (entry.note) block += `\n- **Note:** ${entry.note}`
      block += '\n'
      continue
    }
    if (entry.event_type === 'dismissed-conform') {
      block += `\n## ${date} · DISMISSED-CONFORM\n`
      block += `\n- **Queue key:** \`${entry.queue_key}\``
      block += `\n- **Reason:** ${entry.reason}\n`
      continue
    }
    if (entry.event_type === 'auto-dismissed-standard-removed') {
      block += `\n## ${date} · AUTO-DISMISSED · standard removed\n`
      block += `\n- **Queue key:** \`${entry.queue_key}\``
      block += `\n- **Reason:** ${entry.reason}\n`
      continue
    }
    if (entry.event_type === 'closed-promotion') {
      block += `\n## ${date} · CLOSED-PROMOTION\n`
      block += `\n- **Queue key:** \`${entry.queue_key}\``
      if (entry.file_paths) block += `\n- **Files:** ${entry.file_paths.map(f => `\`${f}\``).join(', ')}`
      block += `\n- **Reason:** ${entry.reason}\n`
      continue
    }
    if (entry.event_type === 'auto-closed-promotion-rule-changed') {
      block += `\n## ${date} · AUTO-CLOSED-PROMOTION · rule changed\n`
      block += `\n- **Queue key:** \`${entry.queue_key}\``
      block += `\n- **Reason:** ${entry.reason}\n`
      continue
    }
    if (entry.event_type === 'auto-closed-promotion-standard-removed') {
      block += `\n## ${date} · AUTO-CLOSED-PROMOTION · standard removed\n`
      block += `\n- **Queue key:** \`${entry.queue_key}\``
      block += `\n- **Reason:** ${entry.reason}\n`
      continue
    }
    if (entry.event_type === 'acknowledged') {
      block += `\n## ${date} · ACKNOWLEDGED · standards-drift\n`
      block += `\n- **Queue key:** \`${entry.queue_key}\``
      if (entry.by) block += `\n- **By:** @${entry.by}`
      if (entry.at_commit) block += `\n- **At:** \`${entry.at_commit}\``
      block += `\n- **Reason:** ${entry.reason}\n`
      continue
    }
  }
  if (block) fs.appendFileSync(logPath, block)
}

// ── Pending evaluations cache ────────────────────────────────────────────────

function writePending(pending) {
  if (!fs.existsSync(PENDING_DIR)) fs.mkdirSync(PENDING_DIR, { recursive: true })
  const file = path.join(PENDING_DIR, `${pending.mode}.json`)
  fs.writeFileSync(file, JSON.stringify(pending, null, 2), 'utf8')
}

function readPending(mode) {
  const file = path.join(PENDING_DIR, `${mode}.json`)
  if (!fs.existsSync(file)) return null
  try { return JSON.parse(fs.readFileSync(file, 'utf8')) } catch { return null }
}

function clearPending(mode) {
  const file = path.join(PENDING_DIR, `${mode}.json`)
  if (fs.existsSync(file)) fs.unlinkSync(file)
}

// ── Queue mutations ──────────────────────────────────────────────────────────

/**
 * Upsert a queue entry keyed by `<standard_id>.<rule_id>`. Adds the file under
 * the matching party (or `_` for non-contracts). Returns 'new' for a brand-new
 * entry, 're_detected' for a Latest bump on an existing file, or null on no-op.
 */
function upsertQueueEntry(state, standard, rule, files, reason) {
  const queueKey = `${standard.id}.${rule.id}`
  let entry = state.entries.find(e => e.queueKey === queueKey)
  let outcome = null
  if (!entry) {
    entry = {
      queueKey,
      standardId: standard.id,
      standardKind: standard.kind,
      ruleId: rule.id,
      severity: rule.severity || 'warn',
      reason: reason || null,
      filesByParty: {}
    }
    state.entries.push(entry)
    outcome = 'new'
  } else {
    // Update reason to the latest one (most recent judgment is more relevant)
    if (reason) entry.reason = reason
  }
  for (const f of files) {
    const partyKey = f.partyName || '_'
    if (!entry.filesByParty[partyKey]) entry.filesByParty[partyKey] = []
    const list = entry.filesByParty[partyKey]
    const existingFile = list.find(x => x.path === f.filePath)
    if (existingFile) {
      const newer = f.sinceCommit
      let changed = false
      if (newer && newer !== existingFile.sinceCommit && newer !== existingFile.latestCommit) {
        existingFile.latestCommit = newer
        existingFile.latestDate = f.sinceDate
        changed = true
      }
      if (f.source && existingFile.source !== f.source) {
        existingFile.source = f.source
        if (f.source === 'working-tree') entry.source = 'working-tree'
        changed = true
      }
      if (f.author && !existingFile.author) {
        existingFile.author = f.author
        changed = true
      }
      if (changed && outcome === null) outcome = 're_detected'
    } else {
      list.push({
        path: f.filePath,
        sinceCommit: f.sinceCommit,
        sinceDate: f.sinceDate,
        ...(f.source && { source: f.source }),
        ...(f.author && { author: f.author })
      })
      if (f.source === 'working-tree') entry.source = 'working-tree'
      if (outcome === null) outcome = 'new'
    }
  }
  return outcome
}

/**
 * Apply a list of renames + deletions to the queue state in-place. Mirrors
 * drift's `handleCodeRename` shape but specialized for conform's per-rule
 * file lists.
 */
function applyFileChangesToQueue(state, renamed, deleted) {
  const renameMap = new Map(renamed.map(r => [r.from, r.to]))
  const deletedSet = new Set(deleted)
  const surviving = []
  for (const entry of state.entries) {
    let totalFiles = 0
    for (const partyKey of Object.keys(entry.filesByParty || {})) {
      const list = entry.filesByParty[partyKey]
      const updated = []
      for (const f of list) {
        if (deletedSet.has(f.path)) continue // drop deleted files
        if (renameMap.has(f.path)) {
          updated.push({ ...f, path: renameMap.get(f.path), renamedFrom: f.path })
        } else {
          updated.push(f)
        }
      }
      entry.filesByParty[partyKey] = updated
      totalFiles += updated.length
    }
    if (totalFiles > 0) surviving.push(entry)
  }
  state.entries = surviving
}

function findEntryByKey(state, queueKey) {
  return state.entries.find(e => e.queueKey === queueKey)
}

function removeEntry(state, queueKey) {
  state.entries = state.entries.filter(e => e.queueKey !== queueKey)
}

module.exports = {
  // Paths + headers
  STANDARDS_DRIFT_PATH,
  STANDARDS_BACKLOG_PATH,
  DRIFT_LOG_DIR,
  PENDING_DIR,
  STANDARDS_DRIFT_HEADER,
  STANDARDS_BACKLOG_HEADER,
  // Baseline
  BASELINE_RE,
  parseBaseline,
  setBaseline,
  ensureHeader,
  // Acks
  parseAcknowledgement,
  formatAcknowledgement,
  // Queue I/O
  readQueue,
  writeQueue,
  formatFileLine,
  // Audit log
  getDriftLogPath,
  appendToDriftLog,
  // Pending
  writePending,
  readPending,
  clearPending,
  // Mutations
  upsertQueueEntry,
  applyFileChangesToQueue,
  findEntryByKey,
  removeEntry
}
