const fs = require('fs')
const path = require('path')
const simpleGit = require('simple-git')
const { loadRules } = require('../lib/rules')
const { globMatch, matchAllPatterns, resolveKbTarget, extractName } = require('../lib/patterns')
const { loadGraph, getDependents } = require('../lib/graph')

const KB_ROOT = 'knowledge'
const CODE_DRIFT_PATH = path.join(KB_ROOT, 'sync/code-drift.md')
const KB_DRIFT_PATH = path.join(KB_ROOT, 'sync/kb-drift.md')
const DRIFT_LOG_DIR = path.join(KB_ROOT, 'sync/drift-log')

function getDriftLogPath() {
  const d = new Date()
  const month = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`
  return path.join(DRIFT_LOG_DIR, `${month}.md`)
}

const CODE_DRIFT_HEADER = `<!-- AUTO-GENERATED by kb-mcp — resolve via kb_drift in Claude. Do not delete entries manually. -->

# Code Drift Queue

Code changed without matching KB update. PM/tech lead reviews with Claude — approve (update KB) or reject (revert code) per KB document.

> **Before opening a PR:** resolve entries for files you touched.
> Wrote KB first? Already clean. Wrote code first? Run \`kb_drift\`, update KB, commit.
> Pulled entries from main? Not yours unless you touched those files.

`

const KB_DRIFT_HEADER = `<!-- AUTO-GENERATED by kb-mcp — resolve via kb_drift in Claude. Do not delete entries manually. -->

# KB Drift Queue

KB spec changed — developer reviews with Claude whether code still matches.

> **Before opening a PR:** confirm entries for specs you changed.
> Run \`kb_drift\` with \`kb_confirmed\` for each entry once code matches.

`

const DRIFT_LOG_HEADER = `<!-- AUTO-GENERATED audit trail — do not edit manually. -->

# Drift Log

Resolved drift events. Append-only.

`

/**
 * kb_drift — Bidirectional drift detection.
 *
 * Phase 1 (no resolution params):
 *   code→kb: code files changed → upsert entries in sync/code-drift.md
 *            keyed by KB target, tracks all code files + since-commit per file
 *            multiple commits to same file accumulate automatically (git diff since..HEAD)
 *   kb→code: KB files changed → upsert entries in sync/kb-drift.md
 *            keyed by KB file, tracks since-commit
 *
 * Phase 2 resolutions:
 *   summaries:    [{ kb_target, summary }]  PM approved — KB updated
 *   reverted:     [{ code_file }]            PM rejected — code file reverted
 *   kb_confirmed: [{ kb_file }]              developer confirmed code matches
 */
async function runTool({ since = 'last-sync', summaries, reverted, kb_confirmed, remote } = {}) {
  if (summaries && Array.isArray(summaries)) return resolveWithSummaries(summaries)
  if (reverted && Array.isArray(reverted)) return resolveReverted(reverted)
  if (kb_confirmed && Array.isArray(kb_confirmed)) return resolveKbConfirmed(kb_confirmed)
  return detectDrift(since, remote)
}

// ── Phase 1: detect drift ─────────────────────────────────────────────────────

async function detectDrift(since, remote) {
  const mainGit = simpleGit(process.cwd())
  const rules = loadRules(KB_ROOT)

  // Resolve the comparison ref:
  // - explicit SHA/ref → use directly
  // - 'last-sync' → KB-commit baseline (last commit touching knowledge/),
  //   then graduated fallback via resolveLastSyncRef
  const lastKbCommit = await getLastKbCommit(mainGit)
  let ref
  if (since !== 'last-sync') {
    ref = since
  } else {
    ref = lastKbCommit || await resolveLastSyncRef(mainGit, remote)
  }

  // Get HEAD commit info for "since" tracking
  let headCommit = 'unknown'
  let headDate = new Date().toISOString().split('T')[0]
  try {
    const log = await mainGit.log({ maxCount: 1 })
    if (log.latest) {
      headCommit = log.latest.hash.slice(0, 7)
      headDate = log.latest.date.split('T')[0]
    }
  } catch { /* non-fatal */ }

  let changedEntries = []
  if (ref === null) {
    process.stderr.write('[kb-drift] warning: no sync baseline found — skipping main repo drift detection\n')
  } else {
    try {
      const mainFiles = await getChangedFiles(mainGit, ref)
      changedEntries.push(...mainFiles.map(f => ({ file: f.path, oldFile: f.oldPath || null, status: f.status, git: mainGit, localFile: f.path, commit: headCommit, date: headDate })))
    } catch (e) {
      return { code_entries: 0, kb_entries: 0, error: e.message }
    }
  }

  const submodules = await detectSubmodules()
  for (const sub of submodules) {
    try {
      const subGit = simpleGit(sub.fullPath)
      let subCommit = 'unknown'
      let subDate = headDate
      try {
        const subLog = await subGit.log({ maxCount: 1 })
        if (subLog.latest) {
          subCommit = subLog.latest.hash.slice(0, 7)
          subDate = subLog.latest.date.split('T')[0]
        }
      } catch { /* non-fatal */ }
      // KB-commit baseline: use the submodule pointer at the last knowledge/ commit.
      // This survives push — the baseline is "last KB update", not "last push".
      let subRef = null
      if (lastKbCommit) {
        subRef = await getSubmodulePointerAt(mainGit, lastKbCommit, sub.path)
      }
      // Fallback: existing logic for repos without KB history or new submodules
      if (subRef === null) {
        try { subRef = await resolveLastSyncRef(subGit, remote) } catch { subRef = null }
      }
      if (subRef === null) {
        process.stderr.write(`[kb-drift] warning: no sync baseline for submodule ${sub.path} — skipping\n`)
        continue
      }
      const subFiles = await getChangedFiles(subGit, subRef)
      changedEntries.push(...subFiles.map(f => ({
        file: `${sub.path}/${f.path}`,
        oldFile: f.oldPath ? `${sub.path}/${f.oldPath}` : null,
        status: f.status,
        git: subGit,
        localFile: f.path,
        commit: subCommit,
        date: subDate,
        isShared: sub.isShared
      })))
    } catch { /* submodule may not have enough history */ }
  }

  const patterns = rules.getCodePathPatterns()
  let codeEntriesWritten = 0
  let kbEntriesWritten = 0
  const stalePatterns = []

  for (const entry of changedEntries) {
    const { file, oldFile, status, commit, date, isShared } = entry

    // Rename/move — handle as a single linked operation
    if (status === 'R' && oldFile) {
      const result = handleRename(file, oldFile, commit, date, isShared, patterns)
      if (result.codeEntry) codeEntriesWritten++
      if (result.kbEntry) kbEntriesWritten++
      if (result.stalePattern) stalePatterns.push(result.stalePattern)
      continue
    }

    // Delete — no new path to track drift against
    if (status === 'D') continue

    // M, A, or other — existing logic
    if (isKbContentFile(file)) {
      // kb→code: KB file changed — always flag, even without mapped code paths
      const relative = file.replace(/^knowledge\//, '')
      const codePaths = reverseMapKbTarget(relative, patterns)
      const wasNew = upsertKbDriftEntry(relative, codePaths, commit, date)
      if (wasNew) kbEntriesWritten++
    } else {
      // code→kb: first-match-wins (patterns ordered by specificity in presets)
      const matches = matchAllPatterns(file, patterns)
      if (matches.length > 0) {
        const match = matches[0]
        const kbTarget = resolveKbTarget(match, file)
        const wasNew = upsertCodeDriftEntry(kbTarget, file, commit, date, isShared)
        if (wasNew) codeEntriesWritten++
      }
    }
  }

  const noDrift = codeEntriesWritten === 0 && kbEntriesWritten === 0
  const ownedSubs = submodules.filter(s => !s.isShared).map(s => s.path)
  const sharedSubs = submodules.filter(s => s.isShared).map(s => s.path)
  const subParts = []
  if (ownedSubs.length > 0) subParts.push(`owned: ${ownedSubs.join(', ')}`)
  if (sharedSubs.length > 0) subParts.push(`shared: ${sharedSubs.join(', ')}`)
  const subInfo = subParts.length > 0 ? ` (submodules — ${subParts.join('; ')})` : ''

  return {
    code_entries: codeEntriesWritten,
    kb_entries: kbEntriesWritten,
    submodules_owned: ownedSubs,
    submodules_shared: sharedSubs,
    ...(stalePatterns.length > 0 && { stale_patterns: stalePatterns }),
    ...(noDrift
      ? { message: `No drift detected.${subInfo}` }
      : { message: `${codeEntriesWritten} code→KB entry(s) in sync/code-drift.md, ${kbEntriesWritten} KB→code entry(s) in sync/kb-drift.md.${subInfo}` }
    )
  }
}

// ── Phase 2a: code→kb resolved — KB updated ──────────────────────────────────

async function resolveWithSummaries(summaries) {
  const resolved = []

  for (const { kb_target, summary } of summaries) {
    if (!summary || !kb_target) continue
    resolved.push({ direction: 'code→kb', resolution: 'kb-updated', kb_target, summary })
  }

  // Remove fully resolved KB target entries from code-drift.md
  const { entries, header } = readCodeDriftEntries()
  const kbTargets = summaries.map(s => s.kb_target)
  const remaining = entries.filter(e => !kbTargets.includes(e.kbTarget))
  writeCodeDriftEntries(header, remaining)

  appendToDriftLog(resolved)
  return { resolved: resolved.length }
}

// ── Phase 2b: code→kb resolved — code file reverted ──────────────────────────

async function resolveReverted(reverted) {
  const codeFiles = reverted.map(r => r.code_file || r)
  const { entries, header } = readCodeDriftEntries()
  const resolved = []

  // Remove the reverted code file from each entry that contains it
  const updated = entries.map(entry => {
    const before = entry.codeFiles.length
    entry.codeFiles = entry.codeFiles.filter(f => !codeFiles.includes(f.path))
    if (entry.codeFiles.length < before) {
      resolved.push({ direction: 'code→kb', resolution: 'code-reverted', kb_target: entry.kbTarget, code_files: codeFiles })
    }
    return entry
  }).filter(entry => entry.codeFiles.length > 0) // remove empty entries

  writeCodeDriftEntries(header, updated)
  appendToDriftLog(resolved)
  return { reverted: codeFiles.length }
}

// ── Phase 2c: kb→code resolved ────────────────────────────────────────────────

async function resolveKbConfirmed(kb_confirmed) {
  const kbFiles = kb_confirmed.map(r => r.kb_file || r)
  const rules = loadRules(KB_ROOT)
  const patterns = rules.getCodePathPatterns()

  const warnings = []
  const resolved = kbFiles.map(kb_file => {
    const codePaths = reverseMapKbTarget(kb_file, patterns)
    const unmapped = codePaths.length === 0
    if (unmapped) {
      warnings.push(`drift confirmed for "${kb_file}" but no code_path_patterns mapping exists in _rules.md. Future KB changes to this file will not trigger automatic drift detection. Recommended: add a code_path_patterns entry for this file.`)
    }
    return { direction: 'kb→code', resolution: 'confirmed', kb_file, ...(unmapped && { unmapped: true }) }
  })

  removeFromQueue(KB_DRIFT_PATH, entry => kbFiles.some(f => entry.includes(`## ${f}`)))
  appendToDriftLog(resolved)

  const result = { confirmed: kbFiles.length }
  if (warnings.length > 0) result.warnings = warnings
  return result
}

// ── code-drift.md parse / serialize ──────────────────────────────────────────

function readCodeDriftEntries() {
  ensureHeader(CODE_DRIFT_PATH, CODE_DRIFT_HEADER)
  const content = fs.readFileSync(CODE_DRIFT_PATH, 'utf8')
  const headerEnd = content.indexOf('\n## ')
  const header = headerEnd === -1 ? content : content.slice(0, headerEnd)
  const entriesStr = headerEnd === -1 ? '' : content.slice(headerEnd + 1)
  const blocks = entriesStr.split(/\n(?=## )/).filter(b => b.trim())

  const entries = blocks.map(block => {
    const headingMatch = block.match(/^## (.+)/)
    const kbTarget = headingMatch ? headingMatch[1].trim() : null
    const hasShared = /\*\*Shared module:\*\*\s*true/.test(block)
    const codeFiles = []
    for (const line of block.split('\n')) {
      // Match with optional ← renamed from annotation
      const m = line.match(/^\s+-\s+`([^`]+)`(?:\s+←\s+renamed from\s+`([^`]+)`)?\s+—\s+since\s+`([^`]+)`\s+\(([^)]+)\)/)
      if (m) codeFiles.push({ path: m[1], ...(m[2] && { renamedFrom: m[2] }), sinceCommit: m[3], sinceDate: m[4] })
    }
    return { kbTarget, codeFiles, hasShared }
  }).filter(e => e.kbTarget)

  return { header, entries }
}

function writeCodeDriftEntries(header, entries) {
  const body = entries.map(entry => {
    const fileLines = entry.codeFiles.map(f => {
      const renameNote = f.renamedFrom ? ` ← renamed from \`${f.renamedFrom}\`` : ''
      return `  - \`${f.path}\`${renameNote} — since \`${f.sinceCommit}\` (${f.sinceDate})`
    })
    const sharedLine = entry.hasShared ? '\n- **Shared module:** true' : ''
    return `## ${entry.kbTarget}\n\n- **KB target:** \`${entry.kbTarget}\`\n- **Code files:**\n${fileLines.join('\n')}${sharedLine}`
  }).join('\n\n')
  fs.writeFileSync(CODE_DRIFT_PATH, header + (body ? '\n' + body + '\n' : ''), 'utf8')
}

/**
 * Upsert a code file into the entry for a KB target.
 * Returns true if a new entry was created, false if existing was updated or skipped.
 * @param {string} renamedFrom — optional old path if this file was renamed/moved
 */
function upsertCodeDriftEntry(kbTarget, codeFile, sinceCommit, sinceDate, isShared, renamedFrom) {
  const { header, entries } = readCodeDriftEntries()
  const existing = entries.find(e => e.kbTarget === kbTarget)

  if (existing) {
    if (!existing.codeFiles.some(f => f.path === codeFile)) {
      existing.codeFiles.push({ path: codeFile, sinceCommit, sinceDate, ...(renamedFrom && { renamedFrom }) })
      if (isShared) existing.hasShared = true
      writeCodeDriftEntries(header, entries)
    }
    return false // entry already existed
  }

  entries.push({ kbTarget, codeFiles: [{ path: codeFile, sinceCommit, sinceDate, ...(renamedFrom && { renamedFrom }) }], hasShared: !!isShared })
  writeCodeDriftEntries(header, entries)
  return true // new entry created
}

// ── kb-drift.md upsert ────────────────────────────────────────────────────────

/**
 * Upsert a KB file entry in kb-drift.md.
 * Returns true if new entry created.
 */
function upsertKbDriftEntry(kbFile, codeAreas, sinceCommit, sinceDate) {
  ensureHeader(KB_DRIFT_PATH, KB_DRIFT_HEADER)
  const content = fs.readFileSync(KB_DRIFT_PATH, 'utf8')

  // Already tracked — don't duplicate (git diff since..HEAD covers new commits)
  if (content.includes(`## ${kbFile}`)) return false

  const unmapped = codeAreas.length === 0
  const areaLines = unmapped
    ? '  - _(no mapped code paths — review manually)_'
    : codeAreas.map(p => `  - \`${p}\``).join('\n')
  const unmappedHint = unmapped
    ? `\n- **⚠ KB spec changed without mapped code paths.** Verify that the implementation still matches this spec. To enable automatic code-area tracking, add a \`code_path_patterns\` entry in \`_rules.md\` for this file.`
    : ''
  const entry = `\n## ${kbFile}\n\n- **KB file:** \`${kbFile}\`\n- **Code areas to review:**\n${areaLines}\n- **Since:** \`${sinceCommit}\` (${sinceDate})${unmappedHint}\n`
  fs.appendFileSync(KB_DRIFT_PATH, entry)
  return true
}

// ── Rename/move handling ─────────────────────────────────────────────────────

/**
 * Dispatch a rename based on whether the files are KB or code files.
 * Returns { codeEntry: bool, kbEntry: bool, stalePattern: object|null }
 */
function handleRename(newPath, oldPath, commit, date, isShared, patterns) {
  const oldIsKb = isKbContentFile(oldPath)
  const newIsKb = isKbContentFile(newPath)

  if (oldIsKb && newIsKb) {
    return handleKbRename(newPath, oldPath, commit, date, patterns)
  }
  if (!oldIsKb && !newIsKb) {
    return handleCodeRename(newPath, oldPath, commit, date, isShared, patterns)
  }
  // Cross-boundary move (code↔KB) — unusual, treat new path as a normal add
  if (newIsKb) {
    const relative = newPath.replace(/^knowledge\//, '')
    const codePaths = reverseMapKbTarget(relative, patterns)
    const wasNew = upsertKbDriftEntry(relative, codePaths, commit, date)
    return { codeEntry: false, kbEntry: wasNew, stalePattern: null }
  }
  const matches = matchAllPatterns(newPath, patterns)
  if (matches.length > 0) {
    const wasNew = upsertCodeDriftEntry(resolveKbTarget(matches[0], newPath), newPath, commit, date, isShared)
    return { codeEntry: wasNew, kbEntry: false, stalePattern: null }
  }
  return { codeEntry: false, kbEntry: false, stalePattern: null }
}

/**
 * Handle a code file rename. Resolves KB targets for both old and new paths.
 * - Same target: replace old path with new in existing entry
 * - Different targets: remove from old, add to new with rename annotation
 * - No match for new: flag stale pattern warning
 */
function handleCodeRename(newPath, oldPath, commit, date, isShared, patterns) {
  const oldMatches = matchAllPatterns(oldPath, patterns)
  const newMatches = matchAllPatterns(newPath, patterns)
  const oldTarget = oldMatches.length > 0 ? resolveKbTarget(oldMatches[0], oldPath) : null
  const newTarget = newMatches.length > 0 ? resolveKbTarget(newMatches[0], newPath) : null

  let codeEntry = false
  let stalePattern = null

  if (oldTarget && newTarget && oldTarget === newTarget) {
    // Same KB target — swap path in-place
    replaceCodeFileInEntry(oldTarget, oldPath, newPath, commit, date)
  } else {
    // Different targets — remove old, add new with rename annotation
    if (oldTarget) removeCodeFileFromEntry(oldTarget, oldPath)
    if (newTarget) {
      codeEntry = upsertCodeDriftEntry(newTarget, newPath, commit, date, isShared, oldPath)
    }
  }

  // New path matches nothing but old did — pattern is stale
  if (!newTarget && oldTarget) {
    stalePattern = {
      intent: oldMatches[0].intent,
      kb_target: oldTarget,
      moved: { from: oldPath, to: newPath }
    }
  }

  return { codeEntry, kbEntry: false, stalePattern }
}

/**
 * Handle a KB file rename. Finds files that reference the old path and
 * creates a kb-drift entry with rename metadata.
 */
function handleKbRename(newPath, oldPath, commit, date, patterns) {
  const oldRelative = oldPath.replace(/^knowledge\//, '')
  const newRelative = newPath.replace(/^knowledge\//, '')

  // Find files referencing old path via the graph
  const graph = loadGraph(KB_ROOT)
  const oldWithoutExt = oldRelative.replace(/\.md$/, '')
  const dependents = getDependents(graph, oldWithoutExt)
  const refCount = dependents.length
  const refFiles = dependents.map(d => d.path)

  // Code areas for the new path (for reviewer context)
  const codePaths = reverseMapKbTarget(newRelative, patterns)

  ensureHeader(KB_DRIFT_PATH, KB_DRIFT_HEADER)
  const content = fs.readFileSync(KB_DRIFT_PATH, 'utf8')
  if (content.includes(`## ${newRelative}`)) return { codeEntry: false, kbEntry: false, stalePattern: null }

  const areaLines = codePaths.length > 0
    ? codePaths.map(p => `  - \`${p}\``).join('\n')
    : '  - _(no mapped code paths — review manually)_'
  const refLine = refCount > 0
    ? `\n- **References to update:** ${refCount} file(s) contain \`[[${oldWithoutExt}]]\`\n  - ${refFiles.map(f => `\`${f}\``).join('\n  - ')}`
    : '\n- **References to update:** none found'
  const entry = `\n## ${newRelative}\n\n- **KB file:** \`${newRelative}\`\n- **Renamed from:** \`${oldRelative}\`${refLine}\n- **Code areas to review:**\n${areaLines}\n- **Since:** \`${commit}\` (${date})\n`
  fs.appendFileSync(KB_DRIFT_PATH, entry)
  return { codeEntry: false, kbEntry: true, stalePattern: null }
}

/**
 * Replace a code file path in an existing code-drift entry (same KB target rename).
 */
function replaceCodeFileInEntry(kbTarget, oldPath, newPath, commit, date) {
  const { header, entries } = readCodeDriftEntries()
  const existing = entries.find(e => e.kbTarget === kbTarget)
  if (!existing) {
    // No existing entry — create one with rename annotation
    upsertCodeDriftEntry(kbTarget, newPath, commit, date, false, oldPath)
    return
  }
  const idx = existing.codeFiles.findIndex(f => f.path === oldPath)
  if (idx !== -1) {
    existing.codeFiles[idx] = { path: newPath, sinceCommit: commit, sinceDate: date, renamedFrom: oldPath }
  } else {
    existing.codeFiles.push({ path: newPath, sinceCommit: commit, sinceDate: date, renamedFrom: oldPath })
  }
  writeCodeDriftEntries(header, entries)
}

/**
 * Remove a single code file from its code-drift entry. Removes the entry entirely if empty.
 */
function removeCodeFileFromEntry(kbTarget, codePath) {
  const { header, entries } = readCodeDriftEntries()
  const existing = entries.find(e => e.kbTarget === kbTarget)
  if (!existing) return
  existing.codeFiles = existing.codeFiles.filter(f => f.path !== codePath)
  const remaining = existing.codeFiles.length > 0 ? entries : entries.filter(e => e.kbTarget !== kbTarget)
  writeCodeDriftEntries(header, remaining)
}

// ── Shared queue helpers ──────────────────────────────────────────────────────

function ensureHeader(filePath, header) {
  if (!fs.existsSync(filePath)) {
    fs.mkdirSync(path.dirname(filePath), { recursive: true })
    fs.writeFileSync(filePath, header, 'utf8')
  } else {
    const content = fs.readFileSync(filePath, 'utf8')
    if (!content.startsWith('<!-- AUTO-GENERATED')) {
      fs.writeFileSync(filePath, header + content, 'utf8')
    }
  }
}

function removeFromQueue(filePath, matchFn) {
  if (!fs.existsSync(filePath)) return []
  const content = fs.readFileSync(filePath, 'utf8')
  const headerEnd = content.indexOf('\n## ')
  const header = headerEnd === -1 ? content : content.slice(0, headerEnd)
  const entriesStr = headerEnd === -1 ? '' : content.slice(headerEnd + 1)
  const entries = entriesStr.split(/\n(?=## )/).filter(e => e.trim())
  const removed = []
  const remaining = []
  for (const entry of entries) {
    if (matchFn(entry)) removed.push(entry)
    else remaining.push(entry)
  }
  const newContent = header + (remaining.length > 0 ? '\n' + remaining.join('\n') : '')
  fs.writeFileSync(filePath, newContent, 'utf8')
  return removed
}

function appendToDriftLog(entries) {
  if (!fs.existsSync(DRIFT_LOG_DIR)) fs.mkdirSync(DRIFT_LOG_DIR, { recursive: true })
  const logPath = getDriftLogPath()
  ensureHeader(logPath, DRIFT_LOG_HEADER)
  const date = new Date().toISOString().split('T')[0]
  let block = ''
  for (const entry of entries) {
    block += `\n## ${date} · RESOLVED · ${entry.direction}\n`
    if (entry.kb_target) block += `\n- **KB target:** \`${entry.kb_target}\``
    if (entry.kb_file) block += `\n- **KB file:** \`${entry.kb_file}\``
    if (entry.code_file) block += `\n- **Code file:** \`${entry.code_file}\``
    if (entry.code_files) block += `\n- **Code files:** ${entry.code_files.map(f => `\`${f}\``).join(', ')}`
    block += `\n- **Resolution:** ${entry.resolution}`
    if (entry.renamed_from) block += `\n- **Renamed from:** \`${entry.renamed_from}\``
    if (entry.unmapped) block += `\n- **⚠ Unmapped:** no code_path_patterns entry — drift detection inactive for this KB file`
    if (entry.summary) block += `\n- **Summary:** ${entry.summary}`
    block += '\n'
  }
  if (block) fs.appendFileSync(logPath, block)
}

// ── kb→code reverse mapping ───────────────────────────────────────────────────

function reverseMapKbTarget(kbRelative, patterns) {
  const codePaths = []
  for (const pattern of patterns) {
    if (matchesKbTargetPattern(pattern.kb_target, kbRelative)) {
      codePaths.push(...(pattern.paths || []))
    }
  }
  return [...new Set(codePaths)]
}

function matchesKbTargetPattern(patternTarget, actualPath) {
  const regexStr = patternTarget
    .replace(/\./g, '\\.')
    .replace(/\{name\}/g, '[^/]+')
  try {
    return new RegExp(`^${regexStr}$`).test(actualPath)
  } catch {
    return patternTarget === actualPath
  }
}

function isKbContentFile(file) {
  if (!file.startsWith('knowledge/')) return false
  const rel = file.replace(/^knowledge\//, '')
  if (rel.startsWith('_') || rel.startsWith('sync/') || rel.startsWith('exports/') || rel.startsWith('assets/')) return false
  return file.endsWith('.md')
}

// ── git helpers ───────────────────────────────────────────────────────────────

/**
 * Find the most recent commit in the parent repo that touched knowledge/.
 * Used as the drift baseline: code changes are measured from the last KB update.
 * Returns null if knowledge/ has no commit history (fresh repo).
 */
async function getLastKbCommit(git) {
  try {
    const sha = (await git.raw(['log', '-1', '--format=%H', '--', 'knowledge/'])).trim()
    return sha || null
  } catch { return null }
}

/**
 * Get the submodule's commit SHA as recorded in the parent repo at a given commit.
 * Uses git ls-tree to read the submodule pointer (mode 160000) without checking out.
 * Returns null if the submodule didn't exist at that commit.
 */
async function getSubmodulePointerAt(git, commitSha, subPath) {
  try {
    const line = (await git.raw(['ls-tree', commitSha, subPath])).trim()
    const match = line.match(/^160000 commit ([a-f0-9]+)/)
    return match ? match[1] : null
  } catch { return null }
}

/**
 * Resolve the best "last sync" ref for drift comparison.
 * Graduated fallback: upstream tracking → remote branch → closest parent branch → null.
 * Returns null when no reliable baseline exists (caller should skip with warning).
 */
async function resolveLastSyncRef(git, remote) {
  // 1. Try upstream tracking ref (e.g. origin/main) — covers all unpushed commits
  try {
    const upstream = await git.raw(['rev-parse', '--abbrev-ref', '@{upstream}'])
    if (upstream && upstream.trim()) return upstream.trim()
  } catch { /* no upstream configured */ }

  // Validate that the requested remote exists in this repo.
  // Submodules may have different remote names than the parent repo.
  let validRemote = remote
  if (remote) {
    try {
      const remotes = (await git.raw(['remote'])).split('\n').filter(r => r.trim())
      if (!remotes.includes(remote)) {
        const cwd = git._executor?.cwd || 'unknown'
        process.stderr.write(`[kb-drift] warning: remote '${remote}' not found in ${cwd} — available remotes: ${remotes.join(', ') || 'none'}. Skipping drift detection.\n`)
        process.stderr.write(`[kb-drift]   fix: git -C ${cwd} remote rename <correct> ${remote}\n`)
        validRemote = null
      }
    } catch { validRemote = null }
  }

  // 2. Try <remote>/<current-branch> — branch exists on remote but no -u was used
  if (validRemote) {
    try {
      const branch = (await git.raw(['symbolic-ref', '--short', 'HEAD'])).trim()
      const remoteBranch = `${validRemote}/${branch}`
      await git.raw(['rev-parse', remoteBranch])
      return remoteBranch
    } catch { /* remote branch doesn't exist yet */ }
  }

  // 3. Find closest parent branch on remote — new branch, first push
  //    Tries all remote branches, picks the one whose merge-base is closest to HEAD.
  //    For main->dev->feature, this finds dev (not main) as the parent.
  if (validRemote) {
    try {
      const remoteBranches = (await git.raw(['for-each-ref', '--format=%(refname:short)', `refs/remotes/${validRemote}/`]))
        .split('\n')
        .filter(b => b.trim() && !b.includes('/HEAD'))
      let closest = null
      let minDistance = Infinity
      for (const rb of remoteBranches) {
        try {
          const mb = (await git.raw(['merge-base', 'HEAD', rb])).trim()
          if (!mb) continue
          const count = parseInt((await git.raw(['rev-list', '--count', `${mb}..HEAD`])).trim(), 10)
          if (count < minDistance) {
            minDistance = count
            closest = mb
          }
        } catch { /* skip branches with no common ancestor */ }
      }
      if (closest) {
        if (minDistance > 20) {
          process.stderr.write(`[kb-drift] hint: ${minDistance} commits since parent branch — consider pulling/rebasing to reduce drift noise\n`)
        }
        return closest
      }
    } catch { /* no remote branches available */ }
  }

  // 4. No reliable baseline — return null (caller skips with warning)
  return null
}

/**
 * Parse git diff --name-status output into structured objects.
 * Each line is tab-separated: STATUS\tPATH (or STATUS\tOLD\tNEW for renames/copies).
 * Returns: [{ status: 'M'|'A'|'D'|'R'|'C', path: string, oldPath?: string, similarity?: number }]
 */
function parseNameStatus(output) {
  return output.split('\n').filter(l => l.trim()).map(line => {
    const parts = line.split('\t')
    const statusCode = parts[0].trim()
    if (statusCode.startsWith('R') || statusCode.startsWith('C')) {
      const similarity = parseInt(statusCode.slice(1), 10) || 0
      return { status: statusCode.charAt(0), oldPath: parts[1], path: parts[2], similarity }
    }
    return { status: statusCode.charAt(0), path: parts[1] }
  })
}

async function getChangedFiles(git, ref) {
  try {
    const result = await git.diff(['--name-status', '-M', ref, 'HEAD'])
    return parseNameStatus(result)
  } catch {
    // Fallback for edge cases (detached HEAD, shallow clone, etc.)
    try {
      const result = await git.diff(['--name-status', '-M', '4b825dc642cb6eb9a060e54bf899d15f7dcb6820', 'HEAD'])
      return parseNameStatus(result)
    } catch {
      return []
    }
  }
}

async function detectSubmodules() {
  const gitmodulesPath = path.join(process.cwd(), '.gitmodules')
  if (!fs.existsSync(gitmodulesPath)) return []
  const content = fs.readFileSync(gitmodulesPath, 'utf8')
  const submodules = []
  const blocks = content.split(/(?=\[submodule\s+"[^"]+"\])/).filter(b => b.trim())
  for (const block of blocks) {
    const nameMatch = block.match(/\[submodule\s+"([^"]+)"\]/)
    const pathMatch = block.match(/path\s*=\s*(.+)/)
    if (!nameMatch || !pathMatch) continue
    const name = nameMatch[1].trim()
    const subPath = pathMatch[1].trim()
    const fullPath = path.join(process.cwd(), subPath)
    const isShared = /kb-shared\s*=\s*true/.test(block)
    if (fs.existsSync(fullPath)) submodules.push({ name, path: subPath, fullPath, isShared })
  }
  return submodules
}

// Pattern matching functions (globMatch, matchAllPatterns, resolveKbTarget, extractName)
// are imported from ../lib/patterns.js

module.exports = { runTool }
