const fs = require('fs')
const path = require('path')
const simpleGit = require('simple-git')
const { loadRules } = require('../lib/rules')
const { matchAllPatterns, resolveKbTarget, expandGlob } = require('../lib/patterns')
const { loadGraph, getDependents } = require('../lib/graph')

const KB_ROOT = 'knowledge'
const CODE_DRIFT_PATH = path.join(KB_ROOT, 'sync/code-drift.md')
const KB_DRIFT_PATH = path.join(KB_ROOT, 'sync/kb-drift.md')
const DRIFT_LOG_DIR = path.join(KB_ROOT, 'sync/drift-log')

function getDriftLogPath() {
  const d = new Date()
  const month = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`
  return path.join(DRIFT_LOG_DIR, `${month}.md`)
}

// Merge protocol guidance shared between both queue headers. The files are
// merged with `merge=union` (see .gitattributes): different entries coalesce
// cleanly, same-entry conflicts are real and intentional, and duplicate
// baseline lines are collapsed by the post-merge hook (or manually — keep
// the descendant SHA).
const MERGE_PROTOCOL_NOTE = `> **On merge conflicts:** queue files use \`merge=union\` — different entries from different branches coalesce automatically. If the same entry appears twice, dedupe by merging the two: keep the earlier \`Since\` commit (the true drift anchor) and the later \`Latest\` commit (the most recent touch). The post-merge git hook collapses duplicate \`<!-- baseline: -->\` lines automatically; if it didn't run, keep whichever SHA is the descendant of the other.`

const CODE_DRIFT_HEADER = `<!-- AUTO-GENERATED by kb-mcp — resolve via kb_drift in Claude. Do not delete entries manually. -->

# Code Drift Queue

Code changed without matching KB update. PM/tech lead reviews with Claude — approve (update KB) or reject (revert code) per KB document.

> **Before opening a PR:** resolve entries for files you touched.
> Wrote KB first? Already clean. Wrote code first? Run \`kb_drift\`, update KB, commit.
> Pulled entries from main? Not yours unless you touched those files.

${MERGE_PROTOCOL_NOTE}

`

const KB_DRIFT_HEADER = `<!-- AUTO-GENERATED by kb-mcp — resolve via kb_drift in Claude. Do not delete entries manually. -->

# KB Drift Queue

KB spec changed — developer reviews with Claude whether code still matches.

> **Before opening a PR:** confirm entries for specs you changed.
> Run \`kb_drift\` with \`kb_confirmed\` for each entry once code matches.

${MERGE_PROTOCOL_NOTE}

`

const DRIFT_LOG_HEADER = `<!-- AUTO-GENERATED audit trail — do not edit manually. -->

# Drift Log

Resolved drift events. Append-only.

`

// Budget for pre-fetched diffs returned via result._diffs. Prevents a single
// large drift queue from blowing the agent's context. When caps are hit, the
// diff content is dropped but the reproducible `cmd` is always preserved so
// the agent can fetch the full diff manually.
const PER_FILE_LINE_CAP = 400
const PER_ENTRY_LINE_CAP = 1500
const TOTAL_LINE_CAP = 6000
const COMMIT_CAP = 10

// v2 caps for the code_areas intersection on kb-drift entries. Bounded so a
// single wide pattern (e.g. `ms-linestop-admin-be/**`) can't starve the rest
// of the payload. When a cap is hit, the reproducible grep_cmd is preserved
// so the agent can rerun the scan manually.
const IDENTIFIER_CAP = 20
const FILES_PER_AREA_CAP = 25
const HITS_PER_AREA_CAP = 10
const HITS_PER_FILE_CAP = 3
const GREP_BUDGET_TOTAL = 200
const GREP_TIMEOUT_MS = 3000
const SNIPPET_MAX_CHARS = 120

// Baseline SHA lives inside the queue header as an HTML comment. Survives the
// existing `indexOf('\n## ')` header/body split because it has no `##` prefix.
// Queue files are merged with `merge=union` (.gitattributes), so after a
// branch merge the header can carry multiple baseline lines. parseBaseline
// returns the *last* one as a conservative default (unioned files append the
// incoming side after ours, so the later line is usually the descendant) and
// setBaseline strips all existing lines before inserting one. The post-merge
// hook runs dedupBaselines to pick the true descendant when both survive.
const BASELINE_RE = /<!--\s*baseline:\s*([a-f0-9]+)\s*-->/gi

function parseBaseline(header) {
  const matches = [...header.matchAll(BASELINE_RE)]
  return matches.length > 0 ? matches[matches.length - 1][1] : null
}

function setBaseline(header, sha) {
  const stripped = header.replace(BASELINE_RE, '').replace(/\n{3,}/g, '\n\n')
  if (/<!-- AUTO-GENERATED[^\n]*-->\n/.test(stripped)) {
    return stripped.replace(/(<!-- AUTO-GENERATED[^\n]*-->\n)/, `$1<!-- baseline: ${sha} -->\n`)
  }
  return `<!-- baseline: ${sha} -->\n` + stripped
}

/**
 * kb_drift — Bidirectional drift detection.
 *
 * Phase 1 (no resolution params):
 *   code→kb: code files changed → upsert entries in sync/code-drift.md
 *            keyed by KB target, tracks all code files + since-commit per file
 *   kb→code: KB files changed → upsert entries in sync/kb-drift.md
 *            keyed by KB file, tracks since-commit
 *   Each queue file carries its own baseline SHA in its header; both advance
 *   to HEAD on every successful run, regardless of whether anything drained.
 *
 * Phase 2 resolutions:
 *   summaries:    [{ kb_target, summary }]  PM approved — KB updated
 *   reverted:     [{ code_file }]            PM rejected — code file reverted
 *   kb_confirmed: [{ kb_file }]              developer confirmed code matches
 *
 * Admin escape hatch:
 *   force_baseline: 'HEAD'|<sha> — reset both queue baselines
 *   purge:         boolean        — with force_baseline, also clear all entries
 *
 * Merge-housekeeping (called by the post-merge git hook):
 *   dedup_baselines: boolean — collapse duplicate baseline lines in queue
 *     files (introduced by `merge=union` when two branches each wrote their
 *     own baseline). Keeps the descendant SHA; warns on diverged histories.
 */
async function runTool({ since = 'last-sync', summaries, reverted, kb_confirmed, remote, force_baseline, purge, dedup_baselines, include_diffs = true } = {}) {
  if (dedup_baselines) return dedupBaselines()
  if (force_baseline || purge) return resetBaselines({ force_baseline, purge })
  if (summaries && Array.isArray(summaries)) return resolveWithSummaries(summaries)
  if (reverted && Array.isArray(reverted)) return resolveReverted(reverted)
  if (kb_confirmed && Array.isArray(kb_confirmed)) return resolveKbConfirmed(kb_confirmed)
  return detectDrift(since, remote, { includeDiffs: include_diffs })
}

// ── Phase 1: detect drift ─────────────────────────────────────────────────────

async function detectDrift(since, remote, { includeDiffs = true } = {}) {
  const mainGit = simpleGit(process.cwd())
  const rules = loadRules(KB_ROOT)

  // Parse both queue files once up front; all mutations happen in memory.
  const codeState = readCodeDriftEntries()
  const kbState = readKbDriftEntries()

  // Resolve per-queue baselines. Explicit `since` overrides both; otherwise
  // read from the header, falling back to resolveLastSyncRef for bootstrap.
  let bCode, bKb
  if (since !== 'last-sync') {
    bCode = since
    bKb = since
  } else {
    bCode = parseBaseline(codeState.header)
    bKb = parseBaseline(kbState.header)

    // Stored baselines can become unreachable — squash-merges on the remote
    // or a checkout that never fetched the originating branch. Falling through
    // to getChangedFiles's empty-tree diff surfaces every file as "changed";
    // re-bootstrap instead and warn loudly.
    if (bCode && !(await baselineReachable(mainGit, bCode))) {
      const old = bCode
      const meta = {}
      bCode = await resolveLastSyncRef(mainGit, remote, meta)
      process.stderr.write(`[kb-drift] warning: code-drift baseline ${old} unreachable in parent repo (likely squash-merged or never fetched); re-bootstrapping. New baseline: ${bCode || '(none — skipping)'}\n`)
      appendToDriftLog([{ event_type: 're-bootstrap', repo: 'parent', queue: 'code-drift', old_sha: old, new_sha: bCode, resolver_used: meta.via }])
    }
    if (bKb && !(await baselineReachable(mainGit, bKb))) {
      const old = bKb
      const meta = {}
      bKb = await resolveLastSyncRef(mainGit, remote, meta)
      process.stderr.write(`[kb-drift] warning: kb-drift baseline ${old} unreachable in parent repo (likely squash-merged or never fetched); re-bootstrapping. New baseline: ${bKb || '(none — skipping)'}\n`)
      appendToDriftLog([{ event_type: 're-bootstrap', repo: 'parent', queue: 'kb-drift', old_sha: old, new_sha: bKb, resolver_used: meta.via }])
    }

    if (!bCode) bCode = await resolveLastSyncRef(mainGit, remote)
    if (!bKb) bKb = await resolveLastSyncRef(mainGit, remote)
  }

  // HEAD info — used for sinceCommit display, submodule anchoring, and the
  // post-run baseline advance.
  let headCommit = 'unknown'
  let headDate = new Date().toISOString().split('T')[0]
  let headSha = null
  try {
    const log = await mainGit.log({ maxCount: 1 })
    if (log.latest) {
      headCommit = log.latest.hash.slice(0, 7)
      headDate = log.latest.date.split('T')[0]
      headSha = log.latest.hash
    }
  } catch { /* non-fatal */ }

  const patterns = rules.getCodePathPatterns()
  let codeEntriesNew = 0
  let codeEntriesReDetected = 0
  let kbEntriesNew = 0
  let kbEntriesReDetected = 0
  const stalePatterns = []

  // ── code→KB pass (B_code, main + submodules, non-KB files only) ───────────
  const submodules = await detectSubmodules()
  let codeChanges = []
  let mainCodeIndex = new Map()
  if (bCode === null) {
    process.stderr.write('[kb-drift] warning: no sync baseline for code-drift — skipping code→KB detection\n')
  } else {
    try {
      const mainFiles = await getChangedFiles(mainGit, bCode)
      mainCodeIndex = await buildCommitIndex(mainGit, bCode)
      codeChanges.push(...mainFiles.map(f => ({
        file: f.path, oldFile: f.oldPath || null, status: f.status,
        indexPath: f.path, indexOldPath: f.oldPath || null,
        fallbackCommit: headCommit, fallbackDate: headDate,
        index: mainCodeIndex, isShared: false
      })))
    } catch (e) {
      return { code_entries: 0, kb_entries: 0, error: e.message }
    }

    for (const sub of submodules) {
      try {
        const subGit = simpleGit(sub.fullPath)
        let subCommit = 'unknown'
        let subDate = headDate
        try {
          const subLog = await subGit.log({ maxCount: 1 })
          if (subLog.latest) {
            subCommit = subLog.latest.hash.slice(0, 7)
            subDate = subLog.latest.date.split('T')[0]
          }
        } catch { /* non-fatal */ }
        // Parent's B_code is the anchor for submodule drift. Read the submodule
        // pointer at B_code; fall back to per-submodule bootstrap if unavailable
        // or unreachable in the local submodule clone.
        let subRef = null
        if (bCode) subRef = await getSubmodulePointerAt(mainGit, bCode, sub.path)
        if (subRef && !(await baselineReachable(subGit, subRef))) {
          const old = subRef
          const meta = {}
          try { subRef = await resolveLastSyncRef(subGit, remote, meta) } catch { subRef = null }
          process.stderr.write(`[kb-drift] warning: submodule ${sub.path} baseline ${old} unreachable (likely squash-merged or never fetched); re-bootstrapping. New baseline: ${subRef || '(none — skipping)'}\n`)
          appendToDriftLog([{ event_type: 're-bootstrap', repo: `submodule:${sub.path}`, queue: 'code-drift', old_sha: old, new_sha: subRef, resolver_used: meta.via }])
        }
        if (subRef === null) {
          try { subRef = await resolveLastSyncRef(subGit, remote) } catch { subRef = null }
        }
        if (subRef === null) {
          process.stderr.write(`[kb-drift] warning: no sync baseline for submodule ${sub.path} — skipping\n`)
          continue
        }
        const subFiles = await getChangedFiles(subGit, subRef)
        const subIndex = await buildCommitIndex(subGit, subRef)
        codeChanges.push(...subFiles.map(f => ({
          file: `${sub.path}/${f.path}`,
          oldFile: f.oldPath ? `${sub.path}/${f.oldPath}` : null,
          status: f.status,
          // Index keys are submodule-relative (what `git log` inside the submodule
          // reports) — keep the unprefixed path for lookup, prefix only for display.
          indexPath: f.path,
          indexOldPath: f.oldPath || null,
          fallbackCommit: subCommit,
          fallbackDate: subDate,
          index: subIndex,
          isShared: sub.isShared
        })))
      } catch { /* submodule may not have enough history */ }
    }
  }

  for (const entry of codeChanges) {
    const { file, oldFile, status, indexPath, indexOldPath, fallbackCommit, fallbackDate, index, isShared } = entry
    // code→KB only cares about non-KB new paths. KB files belong to the kb pass.
    if (isKbContentFile(file)) continue
    if (status === 'D') continue

    const range = resolveCommitRange(index, indexPath, indexOldPath)
        || { sinceCommit: fallbackCommit, sinceDate: fallbackDate, latestCommit: null, latestDate: null }
    const { sinceCommit, sinceDate, latestCommit, latestDate } = range

    if (status === 'R' && oldFile) {
      const result = handleCodeRename(codeState, file, oldFile, sinceCommit, sinceDate, latestCommit, latestDate, isShared, patterns)
      if (result.outcome === 'new') codeEntriesNew++
      else if (result.outcome === 're_detected') codeEntriesReDetected++
      if (result.stalePattern) stalePatterns.push(result.stalePattern)
      continue
    }

    const matches = matchAllPatterns(file, patterns)
    if (matches.length > 0) {
      const kbTarget = resolveKbTarget(matches[0], file)
      const outcome = upsertCodeDriftEntry(codeState, kbTarget, file, sinceCommit, sinceDate, latestCommit, latestDate, isShared)
      if (outcome === 'new') codeEntriesNew++
      else if (outcome === 're_detected') codeEntriesReDetected++
    }
  }

  // ── kb→code pass (B_kb, main repo only, KB files only) ────────────────────
  let kbChanges = []
  let mainKbIndex = new Map()
  if (bKb === null) {
    process.stderr.write('[kb-drift] warning: no sync baseline for kb-drift — skipping kb→code detection\n')
  } else {
    try {
      const mainFiles = await getChangedFiles(mainGit, bKb)
      // Reuse mainCodeIndex when bKb === bCode to avoid a duplicate git log.
      mainKbIndex = (bKb === bCode && mainCodeIndex.size > 0)
        ? mainCodeIndex
        : await buildCommitIndex(mainGit, bKb)
      kbChanges.push(...mainFiles.map(f => ({
        file: f.path, oldFile: f.oldPath || null, status: f.status,
        indexPath: f.path, indexOldPath: f.oldPath || null,
        fallbackCommit: headCommit, fallbackDate: headDate,
        index: mainKbIndex
      })))
    } catch { /* non-fatal — kb pass is main-only and its failure shouldn't abort */ }
  }

  for (const entry of kbChanges) {
    const { file, oldFile, status, indexPath, indexOldPath, fallbackCommit, fallbackDate, index } = entry
    if (!isKbContentFile(file)) continue
    if (status === 'D') continue

    const range = resolveCommitRange(index, indexPath, indexOldPath)
        || { sinceCommit: fallbackCommit, sinceDate: fallbackDate, latestCommit: null, latestDate: null }
    const { sinceCommit, sinceDate, latestCommit, latestDate } = range

    if (status === 'R' && oldFile && isKbContentFile(oldFile)) {
      const result = handleKbRename(kbState, file, oldFile, sinceCommit, sinceDate, latestCommit, latestDate, patterns)
      if (result.outcome === 'new') kbEntriesNew++
      else if (result.outcome === 're_detected') kbEntriesReDetected++
      continue
    }

    // Normal add/modify — or cross-boundary rename where old was non-KB:
    // treat the new KB path as a fresh add (matches the prior behavior).
    const relative = file.replace(/^knowledge\//, '')
    const codePaths = reverseMapKbTarget(relative, patterns)
    const outcome = upsertKbDriftEntry(kbState, relative, codePaths, sinceCommit, sinceDate, latestCommit, latestDate)
    if (outcome === 'new') kbEntriesNew++
    else if (outcome === 're_detected') kbEntriesReDetected++
  }

  // Advance both baselines to HEAD (always — cleanliness lives in the queue,
  // not in the baseline) and write both files once.
  if (headSha) {
    codeState.header = setBaseline(codeState.header, headSha)
    kbState.header = setBaseline(kbState.header, headSha)
  }
  writeCodeDriftEntries(codeState.header, codeState.entries)
  writeKbDriftEntries(kbState.header, kbState.entries)

  const codeEntriesWritten = codeEntriesNew + codeEntriesReDetected
  const kbEntriesWritten = kbEntriesNew + kbEntriesReDetected
  // Also count pre-existing open entries that were not touched in this run
  const codeEntriesPending = codeState.entries.length
  const kbEntriesPending = kbState.entries.length
  const noDrift = codeEntriesWritten === 0 && kbEntriesWritten === 0
               && codeEntriesPending === 0 && kbEntriesPending === 0
  const ownedSubs = submodules.filter(s => !s.isShared).map(s => s.path)
  const sharedSubs = submodules.filter(s => s.isShared).map(s => s.path)
  const subParts = []
  if (ownedSubs.length > 0) subParts.push(`owned: ${ownedSubs.join(', ')}`)
  if (sharedSubs.length > 0) subParts.push(`shared: ${sharedSubs.join(', ')}`)
  const subInfo = subParts.length > 0 ? ` (submodules — ${subParts.join('; ')})` : ''

  const reDetectedTotal = codeEntriesReDetected + kbEntriesReDetected
  const reDetectedNote = reDetectedTotal > 0 ? ` (${reDetectedTotal} re-detected)` : ''

  // Build message: show pending queue totals (new + pre-existing) so the agent
  // always sees the true open-entry count even when no new drift was detected.
  const totalCodeOpen = Math.max(codeEntriesWritten, codeEntriesPending)
  const totalKbOpen = Math.max(kbEntriesWritten, kbEntriesPending)
  const pendingNote = (codeEntriesWritten === 0 && kbEntriesWritten === 0 && !noDrift)
    ? ' (no new drift — pre-existing open entries remain)'
    : reDetectedNote

  const result = {
    code_entries: codeEntriesWritten,
    code_entries_new: codeEntriesNew,
    code_entries_re_detected: codeEntriesReDetected,
    code_entries_pending: codeEntriesPending,
    kb_entries: kbEntriesWritten,
    kb_entries_new: kbEntriesNew,
    kb_entries_re_detected: kbEntriesReDetected,
    kb_entries_pending: kbEntriesPending,
    submodules_owned: ownedSubs,
    submodules_shared: sharedSubs,
    ...(stalePatterns.length > 0 && { stale_patterns: stalePatterns }),
    message: noDrift
      ? `No drift detected.${subInfo}`
      : `${totalCodeOpen} code→KB entry(s) in sync/code-drift.md, ${totalKbOpen} KB→code entry(s) in sync/kb-drift.md${pendingNote}.${subInfo}`
  }

  const hasUnmappedKbEntries = (kbEntriesWritten > 0 || kbEntriesPending > 0) && (() => {
    try {
      const raw = fs.readFileSync(KB_DRIFT_PATH, 'utf8')
      return raw.includes('no mapped code paths')
    } catch { return false }
  })()

  if (!noDrift) {
    let instruction = 'For each entry in `_diffs.code` and `_diffs.kb`:\n'
      + '1. Read `diff` directly. If it is null, truncated, or has `error`, run the `cmd`.\n'
      + '2. Compare against the counterpart (KB file for code drift, listed code areas for kb drift).\n'
      + '3. For kb drift: verify the KB file is internally consistent; cross-check validation/ and flows/ for related rules.\n'
      + '4. Present both values (KB spec vs actual code) to the user and wait for explicit confirmation.\n'
      + '5. After confirmation: edit, then close with `kb_drift({ summaries: [...] })` (code drift) or `kb_drift({ kb_confirmed: [...] })` (kb drift).\n\n'
      + 'Never close silently. Never close without seeing the diff.'

    if (hasUnmappedKbEntries) {
      instruction += '\n\n⚠ One or more KB entries have no mapped code paths ("review manually"). '
        + 'For each unmapped entry: search the entire codebase for files related to the KB feature '
        + '(controllers, services, DTOs, entities, FE components, forms, i18n, DB schema) and verify '
        + 'all layers are consistent with the KB spec before confirming.'
    }

    if (submodules.length > 0) {
      instruction += '\n\nℹ Submodule files: since/latest SHAs belong to submodule history. '
        + 'The `cmd` field in `_diffs[*].files[*]` already uses `git -C <submodule>` — use it as-is.'
    }

    result._instruction = instruction
  }

  if (includeDiffs && !noDrift) {
    result._diffs = await buildDiffsPayload({ codeState, kbState, submodules })
  }

  return result
}

// ── Phase 2a: code→kb resolved — KB updated ──────────────────────────────────

async function resolveWithSummaries(summaries) {
  const resolved = []

  for (const { kb_target, summary } of summaries) {
    if (!summary || !kb_target) continue
    resolved.push({ direction: 'code→kb', resolution: 'kb-updated', kb_target, summary })
  }

  const { entries, header } = readCodeDriftEntries()
  const kbTargets = summaries.map(s => s.kb_target)
  const remaining = entries.filter(e => !kbTargets.includes(e.kbTarget))
  writeCodeDriftEntries(header, remaining)

  appendToDriftLog(resolved)

  const kbTargetList = resolved.map(r => r.kb_target).join(', ')
  return {
    resolved: resolved.length,
    _instruction: `Queue entries closed for: ${kbTargetList}. `
      + 'Verify that each KB file above was actually updated before this call. '
      + 'If not, the drift queue is now clean but the KB is stale — '
      + 'read the KB file(s) to confirm, and use kb_write to fix any that were missed.'
  }
}

// ── Phase 2b: code→kb resolved — code file reverted ──────────────────────────

async function resolveReverted(reverted) {
  const codeFiles = reverted.map(r => r.code_file || r)
  const { entries, header } = readCodeDriftEntries()
  const resolved = []

  const updated = entries.map(entry => {
    const before = entry.codeFiles.length
    entry.codeFiles = entry.codeFiles.filter(f => !codeFiles.includes(f.path))
    if (entry.codeFiles.length < before) {
      resolved.push({ direction: 'code→kb', resolution: 'code-reverted', kb_target: entry.kbTarget, code_files: codeFiles })
    }
    return entry
  }).filter(entry => entry.codeFiles.length > 0)

  writeCodeDriftEntries(header, updated)
  appendToDriftLog(resolved)
  return { reverted: codeFiles.length }
}

// ── Phase 2c: kb→code resolved ────────────────────────────────────────────────

async function resolveKbConfirmed(kb_confirmed) {
  const kbFiles = kb_confirmed.map(r => r.kb_file || r)
  const rules = loadRules(KB_ROOT)
  const patterns = rules.getCodePathPatterns()

  const warnings = []
  const resolved = kbFiles.map(kb_file => {
    const codePaths = reverseMapKbTarget(kb_file, patterns)
    const unmapped = codePaths.length === 0
    if (unmapped) {
      warnings.push(`drift confirmed for "${kb_file}" but no code_path_patterns mapping exists in _rules.md. Future KB changes to this file will not trigger automatic drift detection. Recommended: add a code_path_patterns entry for this file.`)
    }
    return { direction: 'kb→code', resolution: 'confirmed', kb_file, ...(unmapped && { unmapped: true }) }
  })

  const { header, entries } = readKbDriftEntries()
  const remaining = entries.filter(e => !kbFiles.includes(e.kbFile))
  writeKbDriftEntries(header, remaining)

  appendToDriftLog(resolved)

  const result = { confirmed: kbFiles.length }
  if (warnings.length > 0) result.warnings = warnings
  return result
}

// ── Admin escape hatch: force_baseline / purge ───────────────────────────────

async function resetBaselines({ force_baseline, purge }) {
  const git = simpleGit(process.cwd())
  let sha = null
  if (force_baseline) {
    const arg = force_baseline === 'HEAD' ? 'HEAD' : force_baseline
    try {
      sha = (await git.revparse([arg])).trim()
    } catch {
      return { error: `cannot resolve force_baseline="${force_baseline}" via git rev-parse` }
    }
  }

  const codeState = readCodeDriftEntries()
  const kbState = readKbDriftEntries()

  // Capture raw pre-purge queue bodies before any writes. These get logged
  // verbatim so a purge is reconstructable without leaning on `git show`.
  let codeBodyBefore = ''
  let kbBodyBefore = ''
  if (purge) {
    codeBodyBefore = extractQueueBody(CODE_DRIFT_PATH)
    kbBodyBefore = extractQueueBody(KB_DRIFT_PATH)
  }
  const codeCountBefore = codeState.entries.length
  const kbCountBefore = kbState.entries.length

  if (sha) {
    codeState.header = setBaseline(codeState.header, sha)
    kbState.header = setBaseline(kbState.header, sha)
  }

  const codeEntries = purge ? [] : codeState.entries
  const kbEntries = purge ? [] : kbState.entries

  writeCodeDriftEntries(codeState.header, codeEntries)
  writeKbDriftEntries(kbState.header, kbEntries)

  if (purge) {
    appendToDriftLog([{
      event_type: 'purged',
      baseline: sha,
      code_count: codeCountBefore,
      kb_count: kbCountBefore,
      code_body: codeBodyBefore,
      kb_body: kbBodyBefore
    }])
  }

  return {
    baseline: sha,
    purged: !!purge,
    message: purge
      ? `Queue files cleared; both baselines set to ${sha ? sha.slice(0, 7) : '(unchanged)'}.`
      : `Both baselines set to ${sha ? sha.slice(0, 7) : '(unchanged)'}; queue entries preserved.`
  }
}

// ── Merge housekeeping: deduplicate baseline lines ───────────────────────────
//
// The queue files have `merge=union` in .gitattributes, which concatenates
// both sides on merge. Entry-level unions are intentional (different entries
// from different branches coalesce cleanly). But if both branches wrote
// baseline lines, the merged header ends up with multiple <!-- baseline: -->
// comments — and until deduped, parseBaseline returns only the last one while
// the older orphan lingers as noise. Called by the post-merge git hook.
async function dedupBaselines() {
  const git = simpleGit(process.cwd())
  const results = []
  const queues = [
    { filePath: CODE_DRIFT_PATH, read: readCodeDriftEntries, write: writeCodeDriftEntries },
    { filePath: KB_DRIFT_PATH, read: readKbDriftEntries, write: writeKbDriftEntries }
  ]
  for (const { filePath, read, write } of queues) {
    if (!fs.existsSync(filePath)) continue
    const content = fs.readFileSync(filePath, 'utf8')
    const shas = [...content.matchAll(BASELINE_RE)].map(m => m[1])
    if (shas.length < 2) continue

    let winner = shas[0]
    for (let i = 1; i < shas.length; i++) {
      const candidate = shas[i]
      if (candidate === winner) continue
      try {
        await git.raw(['merge-base', '--is-ancestor', winner, candidate])
        winner = candidate
      } catch {
        try {
          await git.raw(['merge-base', '--is-ancestor', candidate, winner])
        } catch {
          process.stderr.write(`[kb-drift] warning: diverged baseline SHAs in ${filePath} (${winner.slice(0, 7)} vs ${candidate.slice(0, 7)}); keeping ${candidate.slice(0, 7)}\n`)
          winner = candidate
        }
      }
    }

    const state = read()
    state.header = setBaseline(state.header, winner)
    write(state.header, state.entries)
    results.push({ file: filePath, kept: winner, dropped: shas.length - 1 })
    process.stderr.write(`[kb-drift] deduped ${shas.length} baseline lines in ${filePath}; kept ${winner.slice(0, 7)}\n`)
  }
  return { deduped: results }
}

// Extract the body (everything after the header) of a queue file as a raw
// string. Used to capture pre-purge content into the drift-log.
function extractQueueBody(filePath) {
  if (!fs.existsSync(filePath)) return ''
  const content = fs.readFileSync(filePath, 'utf8')
  const headerEnd = content.indexOf('\n## ')
  if (headerEnd === -1) return ''
  return content.slice(headerEnd + 1).trimEnd()
}

// ── code-drift.md parse / serialize ──────────────────────────────────────────

function readCodeDriftEntries() {
  ensureHeader(CODE_DRIFT_PATH, CODE_DRIFT_HEADER)
  const content = fs.readFileSync(CODE_DRIFT_PATH, 'utf8')
  const headerEnd = content.indexOf('\n## ')
  const header = headerEnd === -1 ? content : content.slice(0, headerEnd)
  const entriesStr = headerEnd === -1 ? '' : content.slice(headerEnd + 1)
  const blocks = entriesStr.split(/\n(?=## )/).filter(b => b.trim())

  const entries = blocks.map(block => {
    const headingMatch = block.match(/^## (.+)/)
    const kbTarget = headingMatch ? headingMatch[1].trim() : null
    const hasShared = /\*\*Shared module:\*\*\s*true/.test(block)
    const codeFiles = []
    for (const line of block.split('\n')) {
      const m = line.match(/^\s+-\s+`([^`]+)`(?:\s+←\s+renamed from\s+`([^`]+)`)?\s+—\s+since\s+`([^`]+)`\s+\(([^)]+)\)(?:,\s+latest\s+`([^`]+)`\s+\(([^)]+)\))?/)
      if (m) {
        codeFiles.push({
          path: m[1],
          ...(m[2] && { renamedFrom: m[2] }),
          sinceCommit: m[3],
          sinceDate: m[4],
          ...(m[5] && { latestCommit: m[5], latestDate: m[6] })
        })
      }
    }
    return { kbTarget, codeFiles, hasShared }
  }).filter(e => e.kbTarget)

  return { header, entries }
}

function writeCodeDriftEntries(header, entries) {
  const body = entries.map(entry => {
    const fileLines = entry.codeFiles.map(f => {
      const renameNote = f.renamedFrom ? ` ← renamed from \`${f.renamedFrom}\`` : ''
      const latestNote = f.latestCommit && f.latestCommit !== f.sinceCommit
        ? `, latest \`${f.latestCommit}\` (${f.latestDate})`
        : ''
      return `  - \`${f.path}\`${renameNote} — since \`${f.sinceCommit}\` (${f.sinceDate})${latestNote}`
    })
    const sharedLine = entry.hasShared ? '\n- **Shared module:** true' : ''
    // Detect when kb_target doesn't exist on disk but sibling files in the same
    // folder do — likely means the project uses a consolidated file instead of
    // one-file-per-table. Emit a hint so the agent updates the right file.
    const targetAbs = path.join(KB_ROOT, entry.kbTarget)
    let consolidatedHint = ''
    if (!fs.existsSync(targetAbs)) {
      const dir = path.dirname(targetAbs)
      if (fs.existsSync(dir)) {
        const siblings = fs.readdirSync(dir).filter(f => f.endsWith('.md'))
        if (siblings.length > 0) {
          const siblingList = siblings.map(s => `\`${path.join(path.dirname(entry.kbTarget), s)}\``).join(', ')
          consolidatedHint = `\n- **⚠ Target file does not exist.** The \`${path.dirname(entry.kbTarget)}/\` folder already contains: ${siblingList}. Check whether the content belongs in one of these existing files before creating a new one.`
        }
      }
    }
    return `## ${entry.kbTarget}\n\n- **KB target:** \`${entry.kbTarget}\`\n- **Code files:**\n${fileLines.join('\n')}${sharedLine}${consolidatedHint}`
  }).join('\n\n')
  fs.writeFileSync(CODE_DRIFT_PATH, header + (body ? '\n' + body + '\n' : ''), 'utf8')
}

/**
 * Upsert a code file into the in-memory code-drift state.
 * Returns 'new' when a file is added (new entry or new file under existing entry),
 * 're_detected' when an existing file's Latest was bumped to a newer commit,
 * or null when no change was made.
 */
function upsertCodeDriftEntry(state, kbTarget, codeFile, sinceCommit, sinceDate, latestCommit, latestDate, isShared, renamedFrom) {
  const existing = state.entries.find(e => e.kbTarget === kbTarget)
  const fileShape = {
    path: codeFile,
    sinceCommit,
    sinceDate,
    ...(latestCommit && { latestCommit, latestDate }),
    ...(renamedFrom && { renamedFrom })
  }

  if (existing) {
    const existingFile = existing.codeFiles.find(f => f.path === codeFile)
    if (existingFile) {
      // Re-edit under an existing entry — bump Latest to the newest commit we
      // saw in this run, keep Since pinned as the drift anchor.
      const latestToRecord = latestCommit || sinceCommit
      const latestDateToRecord = latestCommit ? latestDate : sinceDate
      const currentLatest = existingFile.latestCommit || existingFile.sinceCommit
      if (latestToRecord !== currentLatest) {
        existingFile.latestCommit = latestToRecord
        existingFile.latestDate = latestDateToRecord
        if (isShared) existing.hasShared = true
        return 're_detected'
      }
      return null
    }
    existing.codeFiles.push(fileShape)
    if (isShared) existing.hasShared = true
    return 'new'
  }

  state.entries.push({
    kbTarget,
    codeFiles: [fileShape],
    hasShared: !!isShared
  })
  return 'new'
}

// ── kb-drift.md parse / serialize ────────────────────────────────────────────

function readKbDriftEntries() {
  ensureHeader(KB_DRIFT_PATH, KB_DRIFT_HEADER)
  const content = fs.readFileSync(KB_DRIFT_PATH, 'utf8')
  const headerEnd = content.indexOf('\n## ')
  const header = headerEnd === -1 ? content : content.slice(0, headerEnd)
  const entriesStr = headerEnd === -1 ? '' : content.slice(headerEnd + 1)
  const blocks = entriesStr.split(/\n(?=## )/).filter(b => b.trim())

  const entries = blocks.map(block => {
    const headingMatch = block.match(/^## (.+)/)
    const kbFile = headingMatch ? headingMatch[1].trim() : null
    const renamedMatch = block.match(/\*\*Renamed from:\*\*\s*`([^`]+)`/)
    const sinceMatch = block.match(/\*\*Since:\*\*\s*`([^`]+)`\s*\(([^)]+)\)/)
    const latestMatch = block.match(/\*\*Latest:\*\*\s*`([^`]+)`\s*\(([^)]+)\)/)
    const unmapped = /KB spec changed without mapped code paths/.test(block)

    const codeAreas = []
    let inCodeAreas = false
    let inRefs = false
    const references = []
    let refCount = null
    const lines = block.split('\n')
    for (const line of lines) {
      if (/^- \*\*Code areas to review:\*\*/.test(line)) { inCodeAreas = true; inRefs = false; continue }
      if (/^- \*\*References to update:\*\*/.test(line)) {
        inCodeAreas = false; inRefs = true
        const countMatch = line.match(/\*\*References to update:\*\*\s*(\d+)\s*file\(s\)\s*contain\s*`\[\[([^\]]+)\]\]`/)
        if (countMatch) refCount = { count: parseInt(countMatch[1], 10), anchor: countMatch[2] }
        else if (/none found/.test(line)) refCount = { count: 0, anchor: null }
        continue
      }
      if (/^- \*\*/.test(line)) { inCodeAreas = false; inRefs = false; continue }
      if (inCodeAreas) {
        const m = line.match(/^\s+-\s+`([^`]+)`/)
        if (m) codeAreas.push(m[1])
      }
      if (inRefs) {
        const m = line.match(/^\s+-\s+`([^`]+)`/)
        if (m) references.push(m[1])
      }
    }

    return {
      kbFile,
      ...(renamedMatch && { renamedFrom: renamedMatch[1] }),
      codeAreas,
      ...(refCount && { refCount }),
      references,
      ...(sinceMatch && { sinceCommit: sinceMatch[1], sinceDate: sinceMatch[2] }),
      ...(latestMatch && { latestCommit: latestMatch[1], latestDate: latestMatch[2] }),
      unmapped
    }
  }).filter(e => e.kbFile)

  return { header, entries }
}

function writeKbDriftEntries(header, entries) {
  const body = entries.map(entry => {
    const areaLines = entry.codeAreas.length > 0
      ? entry.codeAreas.map(p => `  - \`${p}\``).join('\n')
      : '  - _(no mapped code paths — review manually)_'
    const renamedLine = entry.renamedFrom ? `\n- **Renamed from:** \`${entry.renamedFrom}\`` : ''
    let refsLine = ''
    if (entry.refCount) {
      if (entry.refCount.count > 0 && entry.refCount.anchor) {
        refsLine = `\n- **References to update:** ${entry.refCount.count} file(s) contain \`[[${entry.refCount.anchor}]]\``
        if (entry.references.length > 0) {
          refsLine += '\n  - ' + entry.references.map(f => `\`${f}\``).join('\n  - ')
        }
      } else {
        refsLine = '\n- **References to update:** none found'
      }
    }
    const sinceLine = entry.sinceCommit ? `\n- **Since:** \`${entry.sinceCommit}\` (${entry.sinceDate})` : ''
    const latestLine = entry.latestCommit && entry.latestCommit !== entry.sinceCommit
      ? `\n- **Latest:** \`${entry.latestCommit}\` (${entry.latestDate})`
      : ''
    const unmappedHint = entry.unmapped
      ? `\n- **⚠ KB spec changed without mapped code paths.** Verify that the implementation still matches this spec. To enable automatic code-area tracking, add a \`code_path_patterns\` entry in \`_rules.md\` for this file.`
      : ''
    return `## ${entry.kbFile}\n\n- **KB file:** \`${entry.kbFile}\`${renamedLine}${refsLine}\n- **Code areas to review:**\n${areaLines}${sinceLine}${latestLine}${unmappedHint}`
  }).join('\n\n')
  fs.writeFileSync(KB_DRIFT_PATH, header + (body ? '\n' + body + '\n' : ''), 'utf8')
}

/**
 * Upsert a KB file into the in-memory kb-drift state.
 * Returns 'new' when a fresh entry is created, 're_detected' when an existing
 * entry's Latest was bumped to a newer commit, or null when no change.
 */
function upsertKbDriftEntry(state, kbFile, codeAreas, sinceCommit, sinceDate, latestCommit, latestDate) {
  const existing = state.entries.find(e => e.kbFile === kbFile)
  if (existing) {
    const latestToRecord = latestCommit || sinceCommit
    const latestDateToRecord = latestCommit ? latestDate : sinceDate
    const currentLatest = existing.latestCommit || existing.sinceCommit
    if (latestToRecord !== currentLatest) {
      existing.latestCommit = latestToRecord
      existing.latestDate = latestDateToRecord
      return 're_detected'
    }
    return null
  }

  state.entries.push({
    kbFile,
    codeAreas: [...codeAreas],
    references: [],
    sinceCommit,
    sinceDate,
    ...(latestCommit && { latestCommit, latestDate }),
    unmapped: codeAreas.length === 0
  })
  return 'new'
}

// ── Rename/move handling ─────────────────────────────────────────────────────

/**
 * Handle a code file rename. Resolves KB targets for both old and new paths.
 * - Same target: replace old path with new in existing entry
 * - Different targets: remove from old, add to new with rename annotation
 * - No match for new: flag stale pattern warning
 * Returns { outcome: 'new'|'re_detected'|null, stalePattern }.
 */
function handleCodeRename(state, newPath, oldPath, sinceCommit, sinceDate, latestCommit, latestDate, isShared, patterns) {
  const oldMatches = matchAllPatterns(oldPath, patterns)
  const newMatches = matchAllPatterns(newPath, patterns)
  const oldTarget = oldMatches.length > 0 ? resolveKbTarget(oldMatches[0], oldPath) : null
  const newTarget = newMatches.length > 0 ? resolveKbTarget(newMatches[0], newPath) : null

  let outcome = null
  let stalePattern = null

  if (oldTarget && newTarget && oldTarget === newTarget) {
    replaceCodeFileInEntry(state, oldTarget, oldPath, newPath, sinceCommit, sinceDate, latestCommit, latestDate)
    outcome = 'new'
  } else {
    if (oldTarget) removeCodeFileFromEntry(state, oldTarget, oldPath)
    if (newTarget) {
      outcome = upsertCodeDriftEntry(state, newTarget, newPath, sinceCommit, sinceDate, latestCommit, latestDate, isShared, oldPath)
    }
  }

  if (!newTarget && oldTarget) {
    stalePattern = {
      intent: oldMatches[0].intent,
      kb_target: oldTarget,
      moved: { from: oldPath, to: newPath }
    }
  }

  return { outcome, stalePattern }
}

/**
 * Handle a KB file rename. Finds files that reference the old path and
 * creates a kb-drift entry with rename metadata.
 * Returns { outcome: 'new'|'re_detected'|null }.
 */
function handleKbRename(state, newPath, oldPath, sinceCommit, sinceDate, latestCommit, latestDate, patterns) {
  const oldRelative = oldPath.replace(/^knowledge\//, '')
  const newRelative = newPath.replace(/^knowledge\//, '')

  if (state.entries.some(e => e.kbFile === newRelative)) {
    return { outcome: null }
  }

  const graph = loadGraph(KB_ROOT)
  const oldWithoutExt = oldRelative.replace(/\.md$/, '')
  const dependents = getDependents(graph, oldWithoutExt)
  const refCount = dependents.length
  const refFiles = dependents.map(d => d.path)

  const codePaths = reverseMapKbTarget(newRelative, patterns)

  state.entries.push({
    kbFile: newRelative,
    renamedFrom: oldRelative,
    codeAreas: codePaths,
    refCount: { count: refCount, anchor: refCount > 0 ? oldWithoutExt : null },
    references: refFiles,
    sinceCommit,
    sinceDate,
    ...(latestCommit && { latestCommit, latestDate }),
    unmapped: false
  })
  return { outcome: 'new' }
}

/**
 * Replace a code file path in an existing code-drift entry (same KB target rename).
 */
function replaceCodeFileInEntry(state, kbTarget, oldPath, newPath, sinceCommit, sinceDate, latestCommit, latestDate) {
  const existing = state.entries.find(e => e.kbTarget === kbTarget)
  const shape = {
    path: newPath,
    sinceCommit,
    sinceDate,
    ...(latestCommit && { latestCommit, latestDate }),
    renamedFrom: oldPath
  }
  if (!existing) {
    upsertCodeDriftEntry(state, kbTarget, newPath, sinceCommit, sinceDate, latestCommit, latestDate, false, oldPath)
    return
  }
  const idx = existing.codeFiles.findIndex(f => f.path === oldPath)
  if (idx !== -1) existing.codeFiles[idx] = shape
  else existing.codeFiles.push(shape)
}

/**
 * Remove a single code file from its code-drift entry. Removes the entry entirely if empty.
 */
function removeCodeFileFromEntry(state, kbTarget, codePath) {
  const existing = state.entries.find(e => e.kbTarget === kbTarget)
  if (!existing) return
  existing.codeFiles = existing.codeFiles.filter(f => f.path !== codePath)
  if (existing.codeFiles.length === 0) {
    state.entries = state.entries.filter(e => e.kbTarget !== kbTarget)
  }
}

// ── Shared queue helpers ──────────────────────────────────────────────────────

function ensureHeader(filePath, header) {
  if (!fs.existsSync(filePath)) {
    fs.mkdirSync(path.dirname(filePath), { recursive: true })
    fs.writeFileSync(filePath, header, 'utf8')
    return
  }
  const content = fs.readFileSync(filePath, 'utf8')
  if (content.startsWith('<!-- AUTO-GENERATED')) return

  // Sentinel is missing — rewrite from template, but preserve any pre-existing
  // baseline line so we don't lose the anchor.
  const preserved = parseBaseline(content)
  const newHeader = preserved ? setBaseline(header, preserved) : header
  fs.writeFileSync(filePath, newHeader + content, 'utf8')
}

function appendToDriftLog(entries) {
  if (!fs.existsSync(DRIFT_LOG_DIR)) fs.mkdirSync(DRIFT_LOG_DIR, { recursive: true })
  const logPath = getDriftLogPath()
  ensureHeader(logPath, DRIFT_LOG_HEADER)
  const date = new Date().toISOString().split('T')[0]
  let block = ''
  for (const entry of entries) {
    if (entry.event_type === 'purged') {
      const shaDisplay = entry.baseline ? entry.baseline.slice(0, 7) : '(unchanged)'
      block += `\n## ${date} · PURGE\n`
      block += `\n- **New baseline:** \`${shaDisplay}\``
      block += `\n- **Code entries cleared:** ${entry.code_count || 0}`
      block += `\n- **KB entries cleared:** ${entry.kb_count || 0}`
      block += '\n- **Pre-purge code-drift.md body:**\n\n```markdown\n' + (entry.code_body || '(empty)') + '\n```\n'
      block += '\n- **Pre-purge kb-drift.md body:**\n\n```markdown\n' + (entry.kb_body || '(empty)') + '\n```\n'
      continue
    }
    if (entry.event_type === 're-bootstrap') {
      const oldShort = entry.old_sha ? entry.old_sha.slice(0, 7) : '?'
      const newShort = entry.new_sha ? entry.new_sha.slice(0, 7) : '(none)'
      block += `\n## ${date} · RE-BOOTSTRAP · ${entry.repo} (old ${oldShort}, new ${newShort})\n`
      block += `\n- **Queue:** ${entry.queue || 'both'}`
      block += `\n- **Old baseline:** \`${entry.old_sha || '(unknown)'}\``
      block += `\n- **New baseline:** \`${entry.new_sha || '(none — skipped)'}\``
      block += `\n- **Resolver:** ${entry.resolver_used || '(n/a)'}\n`
      continue
    }
    block += `\n## ${date} · RESOLVED · ${entry.direction}\n`
    if (entry.kb_target) block += `\n- **KB target:** \`${entry.kb_target}\``
    if (entry.kb_file) block += `\n- **KB file:** \`${entry.kb_file}\``
    if (entry.code_file) block += `\n- **Code file:** \`${entry.code_file}\``
    if (entry.code_files) block += `\n- **Code files:** ${entry.code_files.map(f => `\`${f}\``).join(', ')}`
    block += `\n- **Resolution:** ${entry.resolution}`
    if (entry.renamed_from) block += `\n- **Renamed from:** \`${entry.renamed_from}\``
    if (entry.unmapped) block += `\n- **⚠ Unmapped:** no code_path_patterns entry — drift detection inactive for this KB file`
    if (entry.summary) block += `\n- **Summary:** ${entry.summary}`
    block += '\n'
  }
  if (block) fs.appendFileSync(logPath, block)
}

// ── kb→code reverse mapping ───────────────────────────────────────────────────

function reverseMapKbTarget(kbRelative, patterns) {
  const codePaths = []
  for (const pattern of patterns) {
    if (matchesKbTargetPattern(pattern.kb_target, kbRelative)) {
      codePaths.push(...(pattern.paths || []))
    }
  }
  return [...new Set(codePaths)]
}

function matchesKbTargetPattern(patternTarget, actualPath) {
  const regexStr = patternTarget
    .replace(/\./g, '\\.')
    .replace(/\{name\}/g, '[^/]+')
  try {
    return new RegExp(`^${regexStr}$`).test(actualPath)
  } catch {
    return patternTarget === actualPath
  }
}

function isKbContentFile(file) {
  if (!file.startsWith('knowledge/')) return false
  const rel = file.replace(/^knowledge\//, '')
  if (rel.startsWith('_') || rel.startsWith('sync/') || rel.startsWith('exports/') || rel.startsWith('assets/')) return false
  return file.endsWith('.md')
}

// ── git helpers ───────────────────────────────────────────────────────────────

/**
 * Get the submodule's commit SHA as recorded in the parent repo at a given commit.
 * Uses git ls-tree to read the submodule pointer (mode 160000) without checking out.
 * Returns null if the submodule didn't exist at that commit.
 */
async function getSubmodulePointerAt(git, commitSha, subPath) {
  try {
    const line = (await git.raw(['ls-tree', commitSha, subPath])).trim()
    const match = line.match(/^160000 commit ([a-f0-9]+)/)
    return match ? match[1] : null
  } catch { return null }
}

/**
 * Bootstrap fallback — only invoked when a queue header has no baseline line yet
 * (first deployment, or a queue manually cleared), or when a stored baseline
 * is unreachable and we re-bootstrap. Graduated fallback:
 * upstream tracking → remote branch → closest parent branch → null.
 * Returns null when no reliable baseline exists (caller skips with warning).
 * Optional `meta` out-param: caller can pass `{}` and read `meta.via` to learn
 * which resolver branch produced the ref — used by the re-bootstrap audit log.
 */
async function resolveLastSyncRef(git, remote, meta) {
  try {
    const upstream = await git.raw(['rev-parse', '--abbrev-ref', '@{upstream}'])
    if (upstream && upstream.trim()) {
      if (meta) meta.via = 'upstream'
      return upstream.trim()
    }
  } catch { /* no upstream configured */ }

  let validRemote = remote
  if (remote) {
    try {
      const remotes = (await git.raw(['remote'])).split('\n').filter(r => r.trim())
      if (!remotes.includes(remote)) {
        const cwd = git._executor?.cwd || 'unknown'
        process.stderr.write(`[kb-drift] warning: remote '${remote}' not found in ${cwd} — available remotes: ${remotes.join(', ') || 'none'}. Skipping drift detection.\n`)
        process.stderr.write(`[kb-drift]   fix: git -C ${cwd} remote rename <correct> ${remote}\n`)
        validRemote = null
      }
    } catch { validRemote = null }
  }

  if (validRemote) {
    try {
      const branch = (await git.raw(['symbolic-ref', '--short', 'HEAD'])).trim()
      const remoteBranch = `${validRemote}/${branch}`
      await git.raw(['rev-parse', remoteBranch])
      if (meta) meta.via = 'remote-branch'
      return remoteBranch
    } catch { /* remote branch doesn't exist yet */ }
  }

  if (validRemote) {
    try {
      const remoteBranches = (await git.raw(['for-each-ref', '--format=%(refname:short)', `refs/remotes/${validRemote}/`]))
        .split('\n')
        .filter(b => b.trim() && !b.includes('/HEAD'))
      let closest = null
      let minDistance = Infinity
      for (const rb of remoteBranches) {
        try {
          const mb = (await git.raw(['merge-base', 'HEAD', rb])).trim()
          if (!mb) continue
          const count = parseInt((await git.raw(['rev-list', '--count', `${mb}..HEAD`])).trim(), 10)
          if (count < minDistance) {
            minDistance = count
            closest = mb
          }
        } catch { /* skip branches with no common ancestor */ }
      }
      if (closest) {
        if (minDistance > 20) {
          process.stderr.write(`[kb-drift] hint: ${minDistance} commits since parent branch — consider pulling/rebasing to reduce drift noise\n`)
        }
        if (meta) meta.via = 'closest-parent'
        return closest
      }
    } catch { /* no remote branches available */ }
  }

  if (meta) meta.via = null
  return null
}

function parseNameStatus(output) {
  return output.split('\n').filter(l => l.trim()).map(line => {
    const parts = line.split('\t')
    const statusCode = parts[0].trim()
    if (statusCode.startsWith('R') || statusCode.startsWith('C')) {
      const similarity = parseInt(statusCode.slice(1), 10) || 0
      return { status: statusCode.charAt(0), oldPath: parts[1], path: parts[2], similarity }
    }
    return { status: statusCode.charAt(0), path: parts[1] }
  })
}

/**
 * Check whether a SHA/ref resolves to a real commit in this repo. Used to
 * guard against stored baselines that have been GC'd after a squash-merge or
 * that were never fetched locally — those cases otherwise fall through to
 * getChangedFiles's empty-tree fallback and surface every file as changed.
 */
async function baselineReachable(git, sha) {
  if (!sha) return false
  try {
    await git.raw(['cat-file', '-e', `${sha}^{commit}`])
    return true
  } catch { return false }
}

async function getChangedFiles(git, ref) {
  try {
    const result = await git.diff(['--name-status', '-M', ref, 'HEAD'])
    return parseNameStatus(result)
  } catch {
    try {
      const result = await git.diff(['--name-status', '-M', '4b825dc642cb6eb9a060e54bf899d15f7dcb6820', 'HEAD'])
      return parseNameStatus(result)
    } catch {
      return []
    }
  }
}

// Build Map<path, [{sha, date}, ...]> in chronological order for baseline..HEAD.
// One `git log` call. A rename commit attributes to the new path (what git's
// --name-status reports on that line); pre-rename history under the old path
// is retained under the old path key — resolveCommitRange merges both.
// Returns an empty Map when the range has no commits or git fails.
async function buildCommitIndex(git, baseline) {
  if (!baseline) return new Map()
  const index = new Map()
  let output
  try {
    output = await git.raw(['log', '--name-status', '-M', '--reverse',
      '--pretty=format:__C %H %cI', `${baseline}..HEAD`])
  } catch { return index }
  if (!output) return index

  let currentSha = null
  let currentDate = null
  for (const line of output.split('\n')) {
    if (line.startsWith('__C ')) {
      const m = line.match(/^__C ([a-f0-9]+) (.+)$/)
      if (m) {
        currentSha = m[1]
        currentDate = m[2].split('T')[0]
      }
      continue
    }
    if (!line.trim() || !currentSha) continue
    const parts = line.split('\t')
    const code = parts[0].trim()
    if (!code) continue
    const entry = { sha: currentSha, date: currentDate }
    if (code.startsWith('R') || code.startsWith('C')) {
      const newPath = parts[2]
      if (newPath) appendCommit(index, newPath, entry)
    } else {
      const p = parts[1]
      if (p) appendCommit(index, p, entry)
    }
  }
  return index
}

function appendCommit(index, key, entry) {
  const list = index.get(key)
  if (list) list.push(entry)
  else index.set(key, [entry])
}

// Merge chronologies for new+old paths, return earliest/latest commit pair.
// `oldPath` lets renamed files pick up commits from before the rename.
// Returns null if no commits found — caller should fall back to HEAD info.
function resolveCommitRange(index, newPath, oldPath) {
  const commits = []
  if (index.has(newPath)) commits.push(...index.get(newPath))
  if (oldPath && oldPath !== newPath && index.has(oldPath)) commits.push(...index.get(oldPath))
  if (commits.length === 0) return null
  commits.sort((a, b) => a.date.localeCompare(b.date))
  const first = commits[0]
  const last = commits[commits.length - 1]
  const sinceCommit = first.sha.slice(0, 7)
  const latestCommit = last.sha.slice(0, 7)
  return {
    sinceCommit,
    sinceDate: first.date,
    latestCommit: latestCommit !== sinceCommit ? latestCommit : null,
    latestDate: latestCommit !== sinceCommit ? last.date : null
  }
}

// ── Pre-fetched diffs ────────────────────────────────────────────────────────
// Returns a structured `_diffs` payload with per-file unified diffs, stats,
// and commit subjects so consuming agents don't have to re-run git themselves
// (and skip the step). Every file carries a reproducible `cmd` — truncation
// or errors never leave the agent without a way to re-fetch.

function resolveGitTarget(filePath, submodules) {
  for (const sub of submodules) {
    const prefix = sub.path.endsWith('/') ? sub.path : sub.path + '/'
    if (filePath === sub.path || filePath.startsWith(prefix)) {
      return {
        cwd: sub.fullPath,
        relativePath: filePath.slice(prefix.length),
        submodule: sub.path,
        isShared: !!sub.isShared
      }
    }
  }
  return { cwd: process.cwd(), relativePath: filePath, submodule: null, isShared: false }
}

function buildCmd({ submodule, op, since, latest, relativePath }) {
  const prefix = submodule ? `git -C ${submodule}` : 'git'
  const to = latest || 'HEAD'
  if (op === 'show') return `${prefix} show ${since} -- ${relativePath}`
  if (op === 'log') return `${prefix} log --pretty="%h  %s" ${since}~1..${to} -- ${relativePath}`
  return `${prefix} diff ${since}~1..${to} -- ${relativePath}`
}

// v2: rename-aware log command for code-drift entries with `renamedFrom`.
// Plain `git diff <since>~1..HEAD -- <newPath>` can hide the rename's content
// when baseline predates the rename; --follow (log-only) traces across it.
function buildFollowCmd({ submodule, since, latest, relativePath }) {
  const prefix = submodule ? `git -C ${submodule}` : 'git'
  const to = latest || 'HEAD'
  return `${prefix} log --follow -p --stat ${since}~1..${to} -- ${relativePath}`
}

// v2: reproducible grep cmd for a list of files. Pathspecs are submodule-
// relative when submodule is set (same convention as buildCmd). Pattern is
// pre-built ERE with alternation and \b word boundaries.
function buildGrepCmd({ submodule, pattern, files }) {
  const prefix = submodule ? `git -C ${submodule}` : 'git'
  const esc = (s) => `'${s.replace(/'/g, `'\\''`)}'`
  const paths = files.map(esc).join(' ')
  return `${prefix} grep -nE ${esc(pattern)} -- ${paths}`
}

// v2: extract likely code identifiers from a unified diff. Pure regex over
// +/- body lines only (headers and hunk lines excluded). Returns up to
// IDENTIFIER_CAP tokens sorted by length desc — longer identifiers anchor
// grep better. No LLM, no AST.
const IDENTIFIER_STOPWORDS = new Set([
  'Required', 'Must', 'Displayed', 'Example', 'Note', 'Yes', 'No', 'None', 'True', 'False',
  'String', 'Number', 'Boolean', 'Object', 'Array', 'Date', 'Null', 'Undefined',
  'TODO', 'FIXME', 'XXX', 'NOTE', 'TBD', 'TBA',
  'HTTP', 'HTTPS', 'URL', 'URI', 'API', 'JSON', 'XML', 'HTML', 'CSS', 'SQL',
  'GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'HEAD', 'OPTIONS'
])

function extractChangedIdentifiers(diffText) {
  if (!diffText || typeof diffText !== 'string') return []
  const bodyLines = []
  for (const line of diffText.split('\n')) {
    if (line.startsWith('+++') || line.startsWith('---') || line.startsWith('@@')) continue
    if (line.startsWith('+') || line.startsWith('-')) bodyLines.push(line.slice(1))
  }
  const text = bodyLines.join('\n').replace(/\|/g, ' ')

  const out = new Set()
  // PascalCase: TrUserRole, UserDefinition
  for (const m of text.matchAll(/\b[A-Z][a-z0-9]+(?:[A-Z][a-zA-Z0-9]*)+\b/g)) out.add(m[0])
  // camelCase starting lowercase: linestopMail, userId, maxLength
  for (const m of text.matchAll(/\b[a-z][a-z0-9]*(?:[A-Z][a-zA-Z0-9]*)+\b/g)) out.add(m[0])
  // UPPER_SNAKE_CASE: SADM_ROLE, MAX_LENGTH
  for (const m of text.matchAll(/\b[A-Z][A-Z0-9]+(?:_[A-Z0-9]+)+\b/g)) out.add(m[0])
  // Quoted/code-spanned field names: "roleType", `userId`, 'email'
  for (const m of text.matchAll(/["'`]([a-zA-Z_][\w\-]{1,40})["'`]/g)) out.add(m[1])
  // Numeric thresholds with comparator or max/min/size keyword
  for (const m of text.matchAll(/(?:max|min|size|length|len|>=?|<=?)\s*[:=(\s]\s*(\d{1,6})/gi) || []) out.add(m[1])

  const filtered = [...out].filter(x => {
    if (!x) return false
    if (IDENTIFIER_STOPWORDS.has(x)) return false
    // drop pure-numeric 1-2 digit (likely noise: line numbers, small constants)
    if (/^\d+$/.test(x) && x.length < 3) return false
    return true
  })
  filtered.sort((a, b) => b.length - a.length || a.localeCompare(b))
  return filtered.slice(0, IDENTIFIER_CAP)
}

function buildIdentifierRegex(identifiers) {
  const esc = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const parts = identifiers.map(id => {
    const e = esc(id)
    // Word-boundary wrap when the identifier starts/ends with a word char.
    const left = /^\w/.test(id) ? '\\b' : ''
    const right = /\w$/.test(id) ? '\\b' : ''
    return `${left}${e}${right}`
  })
  return `(${parts.join('|')})`
}

function computeStat(diffText) {
  if (!diffText) return '+0 -0 (0 hunks)'
  let adds = 0, dels = 0, hunks = 0
  for (const line of diffText.split('\n')) {
    if (line.startsWith('@@')) hunks++
    else if (line.startsWith('+') && !line.startsWith('+++')) adds++
    else if (line.startsWith('-') && !line.startsWith('---')) dels++
  }
  return `+${adds} -${dels} (${hunks} hunk${hunks === 1 ? '' : 's'})`
}

function detectBinaryMarker(diffText) {
  if (!diffText) return null
  const m = diffText.match(/^Binary files .* differ$/m)
  return m ? m[0] : null
}

function truncateDiff(diffText, cap) {
  if (!diffText) return { text: '', lines: 0, truncated: false }
  const lines = diffText.split('\n')
  if (lines.length <= cap) return { text: diffText, lines: lines.length, truncated: false }
  return { text: lines.slice(0, cap).join('\n'), lines: cap, truncated: true }
}

async function fetchFileDiff({ cwd, submodule, since, latest, relativePath }) {
  const cmd = buildCmd({ submodule, op: 'diff', since, latest, relativePath })
  const to = latest || 'HEAD'
  const git = simpleGit(cwd)

  // Guard: the SHA must exist in the local history. For submodules this may
  // fail after a shallow fetch or squash-merge upstream. Preserve `cmd` so
  // the agent can retry once they've fetched.
  try {
    await git.raw(['cat-file', '-e', `${since}^{commit}`])
  } catch {
    return { cmd, diff: null, stat: null, lines: 0, truncated: false, binary: false,
      error: `commit ${since} not in local${submodule ? ' submodule' : ''} history` }
  }

  let raw
  let actualCmd = cmd
  try {
    raw = await git.diff([`${since}~1..${to}`, '--', relativePath])
  } catch {
    // First-commit fallback: <since>~1 doesn't exist, so show the
    // introducing commit instead.
    try {
      actualCmd = buildCmd({ submodule, op: 'show', since, relativePath })
      raw = await git.show([since, '--', relativePath])
    } catch (e) {
      return { cmd, diff: null, stat: null, lines: 0, truncated: false, binary: false,
        error: e.message || 'git invocation failed' }
    }
  }

  if (!raw || !raw.trim()) {
    return { cmd: actualCmd, diff: '', stat: '+0 -0 (0 hunks)', lines: 0, truncated: false, binary: false }
  }

  const binaryMarker = detectBinaryMarker(raw)
  if (binaryMarker) {
    return { cmd: actualCmd, diff: binaryMarker, stat: 'binary', lines: 0, truncated: false, binary: true }
  }

  const stat = computeStat(raw)
  const { text, lines, truncated } = truncateDiff(raw, PER_FILE_LINE_CAP)
  return { cmd: actualCmd, diff: text, stat, lines, truncated, binary: false }
}

async function fetchCommitSubjects({ cwd, submodule, since, latest, relativePath }) {
  const to = latest || 'HEAD'
  const cmd = buildCmd({ submodule, op: 'log', since, latest, relativePath })
  const git = simpleGit(cwd)
  let raw
  try {
    raw = await git.raw(['log', '--pretty=format:%h%x09%s', `${since}~1..${to}`, '--', relativePath])
  } catch {
    try {
      raw = await git.raw(['log', '--pretty=format:%h%x09%s', '-1', since, '--', relativePath])
    } catch {
      return { commits: [], total: 0, cmd, error: 'git log failed' }
    }
  }
  if (!raw || !raw.trim()) return { commits: [], total: 0, cmd }
  const all = raw.split('\n').filter(Boolean).map(line => {
    const [sha, ...rest] = line.split('\t')
    return { sha: sha.trim(), subject: rest.join('\t') }
  })
  const commits = all.slice(0, COMMIT_CAP)
  return { commits, total: all.length, cmd }
}

// v2: run `git grep -nE` over a pre-expanded file list. Returns ranked hits
// (per-file match counts descending, top HITS_PER_AREA_CAP total). `cmd` is
// always preserved for manual re-run. Per-call timeout protects against a
// pathological regex; on timeout we return empty hits + error, not throw.
async function grepFiles({ cwd, submodule, identifiers, files, pattern }) {
  const cmd = buildGrepCmd({ submodule, pattern, files })
  if (!files || files.length === 0 || !identifiers || identifiers.length === 0) {
    return { hits: [], cmd }
  }
  const git = simpleGit(cwd)

  const run = git.raw(['grep', '-n', '-E', pattern, '--', ...files])
    .then(raw => ({ ok: true, raw }))
    .catch(err => {
      // git grep exits 1 when no matches — simple-git surfaces as error.
      const msg = err && (err.message || String(err))
      if (msg && /exit\s*code\s*1\b/i.test(msg)) return { ok: true, raw: '' }
      return { ok: false, err: msg || 'git grep failed' }
    })
  const timer = new Promise(resolve => setTimeout(() => resolve({ ok: false, err: 'grep timeout' }), GREP_TIMEOUT_MS))
  const res = await Promise.race([run, timer])
  if (!res.ok) return { hits: [], cmd, error: res.err }

  const raw = res.raw || ''
  if (!raw.trim()) return { hits: [], cmd }

  const byFile = new Map()
  for (const line of raw.split('\n')) {
    if (!line) continue
    const firstColon = line.indexOf(':')
    if (firstColon === -1) continue
    const secondColon = line.indexOf(':', firstColon + 1)
    if (secondColon === -1) continue
    const file = line.slice(0, firstColon)
    const lineNo = parseInt(line.slice(firstColon + 1, secondColon), 10)
    if (!Number.isFinite(lineNo)) continue
    let snippet = line.slice(secondColon + 1)
    if (snippet.length > SNIPPET_MAX_CHARS) snippet = snippet.slice(0, SNIPPET_MAX_CHARS) + '…'
    // Attribute hit to the first matching identifier in the snippet (best-effort).
    const hitIdent = identifiers.find(id => snippet.includes(id)) || identifiers[0]
    if (!byFile.has(file)) byFile.set(file, [])
    byFile.get(file).push({ file, line: lineNo, identifier: hitIdent, snippet: snippet.trim() })
  }

  const ranked = [...byFile.entries()]
    .sort((a, b) => b[1].length - a[1].length || a[0].localeCompare(b[0]))
  const hits = []
  for (const [, fileHits] of ranked) {
    for (const h of fileHits.slice(0, HITS_PER_FILE_CAP)) {
      hits.push(h)
      if (hits.length >= HITS_PER_AREA_CAP) return { hits, cmd }
    }
  }
  return { hits, cmd }
}

// v2: orchestrate identifier extraction, glob expansion, and grep intersection
// for one kb-drift entry. Produces `code_areas[]` shape; idempotent; never
// throws. Caller gates via budget.grep_budget_left (decremented per hit).
async function buildCodeAreasPayload({ diffText, codeAreas, submodules, budget }) {
  const identifiers = extractChangedIdentifiers(diffText)
  if (!codeAreas || codeAreas.length === 0) {
    return { identifiers: identifiers.length > 0 ? identifiers : null, areas: null }
  }

  const areas = []
  const pattern = identifiers.length > 0 ? buildIdentifierRegex(identifiers) : null

  for (const glob of codeAreas) {
    const { files, matchedCount, truncated } = expandGlob(glob, { fileCap: FILES_PER_AREA_CAP })
    const area = {
      pattern: glob,
      matched_count: matchedCount,
      matched_sample: files.slice(0, FILES_PER_AREA_CAP),
      truncated,
      hits_top: [],
      grep_cmd: null
    }

    if (files.length === 0) {
      area.skipped_reason = 'pattern_no_match'
      areas.push(area)
      continue
    }

    const groups = groupFilesBySubmodule(files, submodules)

    if (!pattern) {
      // Expansion-only: scoped file list still helps the agent narrow search.
      area.grep_cmd = null
      area.skipped_reason = 'no_identifiers'
      areas.push(area)
      continue
    }

    if (budget.grep_budget_left <= 0) {
      area.grep_cmd = groups.map(g => buildGrepCmd({ submodule: g.submodule,
        pattern, files: g.relativeFiles })).join(' && ')
      area.skipped_reason = 'budget'
      areas.push(area)
      continue
    }

    const perFileCounts = new Map()
    const allHits = []
    const cmds = []
    let anyError = null
    for (const g of groups) {
      const { hits, cmd, error } = await grepFiles({
        cwd: g.cwd, submodule: g.submodule, identifiers,
        files: g.relativeFiles, pattern
      })
      cmds.push(cmd)
      if (error) anyError = error
      for (const h of hits) {
        const parentPath = g.submodule ? `${g.submodule}/${h.file}` : h.file
        perFileCounts.set(parentPath, (perFileCounts.get(parentPath) || 0) + 1)
        allHits.push({ ...h, file: parentPath })
      }
    }
    allHits.sort((a, b) => {
      const cDiff = (perFileCounts.get(b.file) || 0) - (perFileCounts.get(a.file) || 0)
      if (cDiff !== 0) return cDiff
      if (a.file !== b.file) return a.file.localeCompare(b.file)
      return a.line - b.line
    })
    area.hits_top = allHits.slice(0, HITS_PER_AREA_CAP)
    area.grep_cmd = cmds.join(' && ')
    if (anyError) area.skipped_reason = 'grep_failed'
    budget.grep_budget_left -= area.hits_top.length
    areas.push(area)
  }

  return { identifiers: identifiers.length > 0 ? identifiers : [], areas }
}

function groupFilesBySubmodule(files, submodules) {
  const byKey = new Map()
  for (const f of files) {
    const tgt = resolveGitTarget(f, submodules)
    const key = tgt.submodule || ''
    if (!byKey.has(key)) {
      byKey.set(key, { submodule: tgt.submodule, cwd: tgt.cwd, relativeFiles: [] })
    }
    byKey.get(key).relativeFiles.push(tgt.relativePath)
  }
  return [...byKey.values()]
}

function dedupCommits(lists) {
  const seen = new Set()
  const out = []
  let total = 0
  for (const list of lists) {
    total += list.total
    for (const c of list.commits) {
      if (seen.has(c.sha)) continue
      seen.add(c.sha)
      out.push(c)
      if (out.length >= COMMIT_CAP) return { commits: out, total }
    }
  }
  return { commits: out, total }
}

async function buildCodeDiffEntry(entry, submodules, budget) {
  const fileList = []
  const commitLists = []
  for (const f of entry.codeFiles) {
    const tgt = resolveGitTarget(f.path, submodules)
    const since = f.sinceCommit
    const latest = f.latestCommit || null

    const entryBudgetLeft = PER_ENTRY_LINE_CAP - (budget.entryUsed || 0)
    const totalBudgetLeft = TOTAL_LINE_CAP - budget.used_lines
    const canFetchDiff = entryBudgetLeft > 0 && totalBudgetLeft > 0

    const fileObj = {
      path: f.path,
      submodule: tgt.submodule,
      isShared: tgt.isShared,
      since,
      ...(latest && { latest }),
      ...(f.renamedFrom && { renamed: true, renamedFrom: f.renamedFrom })
    }

    if (canFetchDiff) {
      const res = await fetchFileDiff({ cwd: tgt.cwd, submodule: tgt.submodule,
        since, latest, relativePath: tgt.relativePath })
      fileObj.stat = res.stat
      fileObj.diff = res.diff
      fileObj.diff_lines = res.lines
      fileObj.truncated = res.truncated
      fileObj.binary = res.binary
      fileObj.cmd = res.cmd
      if (res.error) fileObj.error = res.error
      if (!res.binary && res.lines > 0) {
        budget.used_lines += res.lines
        budget.entryUsed = (budget.entryUsed || 0) + res.lines
      }
    } else {
      fileObj.stat = null
      fileObj.diff = null
      fileObj.diff_lines = 0
      fileObj.truncated = true
      fileObj.binary = false
      fileObj.cmd = f.renamedFrom
        ? buildFollowCmd({ submodule: tgt.submodule, since, latest, relativePath: tgt.relativePath })
        : buildCmd({ submodule: tgt.submodule, op: 'diff', since, latest, relativePath: tgt.relativePath })
      budget.skipped.push({ kind: 'code', key: `${entry.kbTarget} :: ${f.path}`, reason: 'budget', cmd: fileObj.cmd })
    }
    // v2: renamed files get --follow-aware cmd so re-fetch traces the rename.
    if (f.renamedFrom && canFetchDiff) {
      fileObj.cmd = buildFollowCmd({ submodule: tgt.submodule, since, latest, relativePath: tgt.relativePath })
    }

    const subj = await fetchCommitSubjects({ cwd: tgt.cwd, submodule: tgt.submodule,
      since, latest, relativePath: tgt.relativePath })
    commitLists.push(subj)

    fileList.push(fileObj)
  }
  const { commits, total } = dedupCommits(commitLists)
  return { kb_target: entry.kbTarget, commits, total_commits: total, files: fileList }
}

async function buildKbDiffEntry(entry, budget, submodules) {
  const relativePath = path.posix.join(KB_ROOT, entry.kbFile)
  const since = entry.sinceCommit
  const latest = entry.latestCommit || null
  const obj = {
    kb_file: entry.kbFile,
    since,
    ...(latest && { latest }),
    ...(entry.renamedFrom && { renamed: true, renamedFrom: entry.renamedFrom })
  }

  const totalBudgetLeft = TOTAL_LINE_CAP - budget.used_lines
  if (totalBudgetLeft > 0 && since) {
    const res = await fetchFileDiff({ cwd: process.cwd(), submodule: null,
      since, latest, relativePath })
    obj.stat = res.stat
    obj.diff = res.diff
    obj.diff_lines = res.lines
    obj.truncated = res.truncated
    obj.binary = res.binary
    obj.cmd = res.cmd
    if (res.error) obj.error = res.error
    if (!res.binary && res.lines > 0) budget.used_lines += res.lines
  } else {
    obj.stat = null
    obj.diff = null
    obj.diff_lines = 0
    obj.truncated = true
    obj.binary = false
    obj.cmd = since ? buildCmd({ submodule: null, op: 'diff', since, latest, relativePath }) : null
    if (since) budget.skipped.push({ kind: 'kb', key: entry.kbFile, reason: 'budget', cmd: obj.cmd })
  }

  if (since) {
    const subj = await fetchCommitSubjects({ cwd: process.cwd(), submodule: null,
      since, latest, relativePath })
    obj.commits = subj.commits
    obj.total_commits = subj.total
  } else {
    obj.commits = []
    obj.total_commits = 0
  }

  // v2: identifier extraction + glob expansion + grep intersection.
  // Skip when the KB diff is empty, binary, or missing — no signal to extract.
  if (obj.diff && !obj.binary && entry.codeAreas && entry.codeAreas.length > 0) {
    const { identifiers, areas } = await buildCodeAreasPayload({
      diffText: obj.diff,
      codeAreas: entry.codeAreas,
      submodules: submodules || [],
      budget
    })
    if (identifiers !== null) obj.changed_identifiers = identifiers
    if (areas !== null) obj.code_areas = areas
  }
  return obj
}

async function buildDiffsPayload({ codeState, kbState, submodules }) {
  const budget = { used_lines: 0, cap_lines: TOTAL_LINE_CAP, skipped: [],
    grep_budget_left: GREP_BUDGET_TOTAL }
  const code = []
  for (const entry of codeState.entries) {
    budget.entryUsed = 0
    code.push(await buildCodeDiffEntry(entry, submodules, budget))
  }
  const kb = []
  for (const entry of kbState.entries) {
    const hadRoom = TOTAL_LINE_CAP - budget.used_lines > 0
    if (!hadRoom) {
      // No budget left: emit command-only record.
      const relativePath = path.posix.join(KB_ROOT, entry.kbFile)
      const cmd = entry.sinceCommit ? buildCmd({ submodule: null, op: 'diff',
        since: entry.sinceCommit, latest: entry.latestCommit || null, relativePath }) : null
      kb.push({ kb_file: entry.kbFile, since: entry.sinceCommit || null,
        ...(entry.latestCommit && { latest: entry.latestCommit }),
        stat: null, diff: null, diff_lines: 0, truncated: true, binary: false,
        cmd, commits: [], total_commits: 0 })
      if (cmd) budget.skipped.push({ kind: 'kb', key: entry.kbFile, reason: 'budget', cmd })
      continue
    }
    kb.push(await buildKbDiffEntry(entry, budget, submodules))
  }
  delete budget.entryUsed
  delete budget.grep_budget_left
  return { code, kb, budget }
}

async function detectSubmodules() {
  const gitmodulesPath = path.join(process.cwd(), '.gitmodules')
  if (!fs.existsSync(gitmodulesPath)) return []
  const content = fs.readFileSync(gitmodulesPath, 'utf8')
  const submodules = []
  const blocks = content.split(/(?=\[submodule\s+"[^"]+"\])/).filter(b => b.trim())
  for (const block of blocks) {
    const nameMatch = block.match(/\[submodule\s+"([^"]+)"\]/)
    const pathMatch = block.match(/path\s*=\s*(.+)/)
    if (!nameMatch || !pathMatch) continue
    const name = nameMatch[1].trim()
    const subPath = pathMatch[1].trim()
    const fullPath = path.join(process.cwd(), subPath)
    const isShared = /kb-shared\s*=\s*true/.test(block)
    if (fs.existsSync(fullPath)) submodules.push({ name, path: subPath, fullPath, isShared })
  }
  return submodules
}

module.exports = {
  runTool,
  definition: {
    name: 'kb_drift',
    description: 'Bidirectional drift detection. Phase 1: writes entries to sync/code-drift.md (keyed by KB target, tracks all code files + since-commit) and sync/kb-drift.md (keyed by KB file). Multiple commits accumulate automatically. The response includes `_diffs` with pre-fetched unified diffs, stats, and commit subjects for every open entry — read those directly before resolving. Phase 2: summaries=KB updated, reverted=code file reverted, kb_confirmed=kb→code reviewed.',
    inputSchema: {
      type: 'object',
      properties: {
        since: { type: 'string', description: 'Commit SHA or "last-sync"', default: 'last-sync' },
        summaries: { type: 'array', description: 'Phase 2a: code correct — write KB notes and close code-drift.md entries', items: { type: 'object', properties: { kb_target: { type: 'string' }, summary: { type: 'string' } }, required: ['kb_target', 'summary'] } },
        reverted: { type: 'array', description: 'Phase 2b: code reverted — close code-drift.md entries without writing KB notes', items: { type: 'object', properties: { code_file: { type: 'string' } }, required: ['code_file'] } },
        kb_confirmed: { type: 'array', description: 'Phase 2c: kb→code reviewed — close kb-drift.md entries', items: { type: 'object', properties: { kb_file: { type: 'string' } }, required: ['kb_file'] } },
        force_baseline: { type: 'string', description: 'Admin escape hatch: reset both queue baselines to this SHA (or "HEAD"). Use when the queue has gone stale and needs a manual reset.' },
        purge: { type: 'boolean', description: 'With force_baseline: also clear all queue entries. Default: false.' },
        include_diffs: { type: 'boolean', description: 'Include `_diffs` with pre-fetched git diffs, stats, and commit subjects for every open entry. Default: true. Set false for quick status scans.', default: true }
      }
    }
  }
}
