const fs = require('fs')
const path = require('path')
const simpleGit = require('simple-git')
const { loadRules } = require('../lib/rules')
const { globMatch, matchAllPatterns, resolveKbTarget, extractName } = require('../lib/patterns')
const { loadGraph, getDependents } = require('../lib/graph')

const KB_ROOT = 'knowledge'
const CODE_DRIFT_PATH = path.join(KB_ROOT, 'sync/code-drift.md')
const KB_DRIFT_PATH = path.join(KB_ROOT, 'sync/kb-drift.md')
const DRIFT_LOG_DIR = path.join(KB_ROOT, 'sync/drift-log')

function getDriftLogPath() {
  const d = new Date()
  const month = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`
  return path.join(DRIFT_LOG_DIR, `${month}.md`)
}

// Merge protocol guidance shared between both queue headers. The files are
// merged with `merge=union` (see .gitattributes): different entries coalesce
// cleanly, same-entry conflicts are real and intentional, and duplicate
// baseline lines are collapsed by the post-merge hook (or manually — keep
// the descendant SHA).
const MERGE_PROTOCOL_NOTE = `> **On merge conflicts:** queue files use \`merge=union\` — different entries from different branches coalesce automatically. If the same entry appears twice, dedupe by merging the two: keep the earlier \`Since\` commit (the true drift anchor) and the later \`Latest\` commit (the most recent touch). The post-merge git hook collapses duplicate \`<!-- baseline: -->\` lines automatically; if it didn't run, keep whichever SHA is the descendant of the other.`

const CODE_DRIFT_HEADER = `<!-- AUTO-GENERATED by kb-mcp — resolve via kb_drift in Claude. Do not delete entries manually. -->

# Code Drift Queue

Code changed without matching KB update. PM/tech lead reviews with Claude — approve (update KB) or reject (revert code) per KB document.

> **Before opening a PR:** resolve entries for files you touched.
> Wrote KB first? Already clean. Wrote code first? Run \`kb_drift\`, update KB, commit.
> Pulled entries from main? Not yours unless you touched those files.

${MERGE_PROTOCOL_NOTE}

`

const KB_DRIFT_HEADER = `<!-- AUTO-GENERATED by kb-mcp — resolve via kb_drift in Claude. Do not delete entries manually. -->

# KB Drift Queue

KB spec changed — developer reviews with Claude whether code still matches.

> **Before opening a PR:** confirm entries for specs you changed.
> Run \`kb_drift\` with \`kb_confirmed\` for each entry once code matches.

${MERGE_PROTOCOL_NOTE}

`

const DRIFT_LOG_HEADER = `<!-- AUTO-GENERATED audit trail — do not edit manually. -->

# Drift Log

Resolved drift events. Append-only.

`

// Baseline SHA lives inside the queue header as an HTML comment. Survives the
// existing `indexOf('\n## ')` header/body split because it has no `##` prefix.
// Queue files are merged with `merge=union` (.gitattributes), so after a
// branch merge the header can carry multiple baseline lines. parseBaseline
// returns the *last* one as a conservative default (unioned files append the
// incoming side after ours, so the later line is usually the descendant) and
// setBaseline strips all existing lines before inserting one. The post-merge
// hook runs dedupBaselines to pick the true descendant when both survive.
const BASELINE_RE = /<!--\s*baseline:\s*([a-f0-9]+)\s*-->/gi

function parseBaseline(header) {
  const matches = [...header.matchAll(BASELINE_RE)]
  return matches.length > 0 ? matches[matches.length - 1][1] : null
}

function setBaseline(header, sha) {
  const stripped = header.replace(BASELINE_RE, '').replace(/\n{3,}/g, '\n\n')
  if (/<!-- AUTO-GENERATED[^\n]*-->\n/.test(stripped)) {
    return stripped.replace(/(<!-- AUTO-GENERATED[^\n]*-->\n)/, `$1<!-- baseline: ${sha} -->\n`)
  }
  return `<!-- baseline: ${sha} -->\n` + stripped
}

/**
 * kb_drift — Bidirectional drift detection.
 *
 * Phase 1 (no resolution params):
 *   code→kb: code files changed → upsert entries in sync/code-drift.md
 *            keyed by KB target, tracks all code files + since-commit per file
 *   kb→code: KB files changed → upsert entries in sync/kb-drift.md
 *            keyed by KB file, tracks since-commit
 *   Each queue file carries its own baseline SHA in its header; both advance
 *   to HEAD on every successful run, regardless of whether anything drained.
 *
 * Phase 2 resolutions:
 *   summaries:    [{ kb_target, summary }]  PM approved — KB updated
 *   reverted:     [{ code_file }]            PM rejected — code file reverted
 *   kb_confirmed: [{ kb_file }]              developer confirmed code matches
 *
 * Admin escape hatch:
 *   force_baseline: 'HEAD'|<sha> — reset both queue baselines
 *   purge:         boolean        — with force_baseline, also clear all entries
 *
 * Merge-housekeeping (called by the post-merge git hook):
 *   dedup_baselines: boolean — collapse duplicate baseline lines in queue
 *     files (introduced by `merge=union` when two branches each wrote their
 *     own baseline). Keeps the descendant SHA; warns on diverged histories.
 */
async function runTool({ since = 'last-sync', summaries, reverted, kb_confirmed, remote, force_baseline, purge, dedup_baselines } = {}) {
  if (dedup_baselines) return dedupBaselines()
  if (force_baseline || purge) return resetBaselines({ force_baseline, purge })
  if (summaries && Array.isArray(summaries)) return resolveWithSummaries(summaries)
  if (reverted && Array.isArray(reverted)) return resolveReverted(reverted)
  if (kb_confirmed && Array.isArray(kb_confirmed)) return resolveKbConfirmed(kb_confirmed)
  return detectDrift(since, remote)
}

// ── Phase 1: detect drift ─────────────────────────────────────────────────────

async function detectDrift(since, remote) {
  const mainGit = simpleGit(process.cwd())
  const rules = loadRules(KB_ROOT)

  // Parse both queue files once up front; all mutations happen in memory.
  const codeState = readCodeDriftEntries()
  const kbState = readKbDriftEntries()

  // Resolve per-queue baselines. Explicit `since` overrides both; otherwise
  // read from the header, falling back to resolveLastSyncRef for bootstrap.
  let bCode, bKb
  if (since !== 'last-sync') {
    bCode = since
    bKb = since
  } else {
    bCode = parseBaseline(codeState.header)
    bKb = parseBaseline(kbState.header)

    // Stored baselines can become unreachable — squash-merges on the remote
    // or a checkout that never fetched the originating branch. Falling through
    // to getChangedFiles's empty-tree diff surfaces every file as "changed";
    // re-bootstrap instead and warn loudly.
    if (bCode && !(await baselineReachable(mainGit, bCode))) {
      const old = bCode
      const meta = {}
      bCode = await resolveLastSyncRef(mainGit, remote, meta)
      process.stderr.write(`[kb-drift] warning: code-drift baseline ${old} unreachable in parent repo (likely squash-merged or never fetched); re-bootstrapping. New baseline: ${bCode || '(none — skipping)'}\n`)
      appendToDriftLog([{ event_type: 're-bootstrap', repo: 'parent', queue: 'code-drift', old_sha: old, new_sha: bCode, resolver_used: meta.via }])
    }
    if (bKb && !(await baselineReachable(mainGit, bKb))) {
      const old = bKb
      const meta = {}
      bKb = await resolveLastSyncRef(mainGit, remote, meta)
      process.stderr.write(`[kb-drift] warning: kb-drift baseline ${old} unreachable in parent repo (likely squash-merged or never fetched); re-bootstrapping. New baseline: ${bKb || '(none — skipping)'}\n`)
      appendToDriftLog([{ event_type: 're-bootstrap', repo: 'parent', queue: 'kb-drift', old_sha: old, new_sha: bKb, resolver_used: meta.via }])
    }

    if (!bCode) bCode = await resolveLastSyncRef(mainGit, remote)
    if (!bKb) bKb = await resolveLastSyncRef(mainGit, remote)
  }

  // HEAD info — used for sinceCommit display, submodule anchoring, and the
  // post-run baseline advance.
  let headCommit = 'unknown'
  let headDate = new Date().toISOString().split('T')[0]
  let headSha = null
  try {
    const log = await mainGit.log({ maxCount: 1 })
    if (log.latest) {
      headCommit = log.latest.hash.slice(0, 7)
      headDate = log.latest.date.split('T')[0]
      headSha = log.latest.hash
    }
  } catch { /* non-fatal */ }

  const patterns = rules.getCodePathPatterns()
  let codeEntriesNew = 0
  let codeEntriesReDetected = 0
  let kbEntriesNew = 0
  let kbEntriesReDetected = 0
  const stalePatterns = []

  // ── code→KB pass (B_code, main + submodules, non-KB files only) ───────────
  const submodules = await detectSubmodules()
  let codeChanges = []
  let mainCodeIndex = new Map()
  if (bCode === null) {
    process.stderr.write('[kb-drift] warning: no sync baseline for code-drift — skipping code→KB detection\n')
  } else {
    try {
      const mainFiles = await getChangedFiles(mainGit, bCode)
      mainCodeIndex = await buildCommitIndex(mainGit, bCode)
      codeChanges.push(...mainFiles.map(f => ({
        file: f.path, oldFile: f.oldPath || null, status: f.status,
        indexPath: f.path, indexOldPath: f.oldPath || null,
        fallbackCommit: headCommit, fallbackDate: headDate,
        index: mainCodeIndex, isShared: false
      })))
    } catch (e) {
      return { code_entries: 0, kb_entries: 0, error: e.message }
    }

    for (const sub of submodules) {
      try {
        const subGit = simpleGit(sub.fullPath)
        let subCommit = 'unknown'
        let subDate = headDate
        try {
          const subLog = await subGit.log({ maxCount: 1 })
          if (subLog.latest) {
            subCommit = subLog.latest.hash.slice(0, 7)
            subDate = subLog.latest.date.split('T')[0]
          }
        } catch { /* non-fatal */ }
        // Parent's B_code is the anchor for submodule drift. Read the submodule
        // pointer at B_code; fall back to per-submodule bootstrap if unavailable
        // or unreachable in the local submodule clone.
        let subRef = null
        if (bCode) subRef = await getSubmodulePointerAt(mainGit, bCode, sub.path)
        if (subRef && !(await baselineReachable(subGit, subRef))) {
          const old = subRef
          const meta = {}
          try { subRef = await resolveLastSyncRef(subGit, remote, meta) } catch { subRef = null }
          process.stderr.write(`[kb-drift] warning: submodule ${sub.path} baseline ${old} unreachable (likely squash-merged or never fetched); re-bootstrapping. New baseline: ${subRef || '(none — skipping)'}\n`)
          appendToDriftLog([{ event_type: 're-bootstrap', repo: `submodule:${sub.path}`, queue: 'code-drift', old_sha: old, new_sha: subRef, resolver_used: meta.via }])
        }
        if (subRef === null) {
          try { subRef = await resolveLastSyncRef(subGit, remote) } catch { subRef = null }
        }
        if (subRef === null) {
          process.stderr.write(`[kb-drift] warning: no sync baseline for submodule ${sub.path} — skipping\n`)
          continue
        }
        const subFiles = await getChangedFiles(subGit, subRef)
        const subIndex = await buildCommitIndex(subGit, subRef)
        codeChanges.push(...subFiles.map(f => ({
          file: `${sub.path}/${f.path}`,
          oldFile: f.oldPath ? `${sub.path}/${f.oldPath}` : null,
          status: f.status,
          // Index keys are submodule-relative (what `git log` inside the submodule
          // reports) — keep the unprefixed path for lookup, prefix only for display.
          indexPath: f.path,
          indexOldPath: f.oldPath || null,
          fallbackCommit: subCommit,
          fallbackDate: subDate,
          index: subIndex,
          isShared: sub.isShared
        })))
      } catch { /* submodule may not have enough history */ }
    }
  }

  for (const entry of codeChanges) {
    const { file, oldFile, status, indexPath, indexOldPath, fallbackCommit, fallbackDate, index, isShared } = entry
    // code→KB only cares about non-KB new paths. KB files belong to the kb pass.
    if (isKbContentFile(file)) continue
    if (status === 'D') continue

    const range = resolveCommitRange(index, indexPath, indexOldPath)
        || { sinceCommit: fallbackCommit, sinceDate: fallbackDate, latestCommit: null, latestDate: null }
    const { sinceCommit, sinceDate, latestCommit, latestDate } = range

    if (status === 'R' && oldFile) {
      const result = handleCodeRename(codeState, file, oldFile, sinceCommit, sinceDate, latestCommit, latestDate, isShared, patterns)
      if (result.outcome === 'new') codeEntriesNew++
      else if (result.outcome === 're_detected') codeEntriesReDetected++
      if (result.stalePattern) stalePatterns.push(result.stalePattern)
      continue
    }

    const matches = matchAllPatterns(file, patterns)
    if (matches.length > 0) {
      const kbTarget = resolveKbTarget(matches[0], file)
      const outcome = upsertCodeDriftEntry(codeState, kbTarget, file, sinceCommit, sinceDate, latestCommit, latestDate, isShared)
      if (outcome === 'new') codeEntriesNew++
      else if (outcome === 're_detected') codeEntriesReDetected++
    }
  }

  // ── kb→code pass (B_kb, main repo only, KB files only) ────────────────────
  let kbChanges = []
  let mainKbIndex = new Map()
  if (bKb === null) {
    process.stderr.write('[kb-drift] warning: no sync baseline for kb-drift — skipping kb→code detection\n')
  } else {
    try {
      const mainFiles = await getChangedFiles(mainGit, bKb)
      // Reuse mainCodeIndex when bKb === bCode to avoid a duplicate git log.
      mainKbIndex = (bKb === bCode && mainCodeIndex.size > 0)
        ? mainCodeIndex
        : await buildCommitIndex(mainGit, bKb)
      kbChanges.push(...mainFiles.map(f => ({
        file: f.path, oldFile: f.oldPath || null, status: f.status,
        indexPath: f.path, indexOldPath: f.oldPath || null,
        fallbackCommit: headCommit, fallbackDate: headDate,
        index: mainKbIndex
      })))
    } catch { /* non-fatal — kb pass is main-only and its failure shouldn't abort */ }
  }

  for (const entry of kbChanges) {
    const { file, oldFile, status, indexPath, indexOldPath, fallbackCommit, fallbackDate, index } = entry
    if (!isKbContentFile(file)) continue
    if (status === 'D') continue

    const range = resolveCommitRange(index, indexPath, indexOldPath)
        || { sinceCommit: fallbackCommit, sinceDate: fallbackDate, latestCommit: null, latestDate: null }
    const { sinceCommit, sinceDate, latestCommit, latestDate } = range

    if (status === 'R' && oldFile && isKbContentFile(oldFile)) {
      const result = handleKbRename(kbState, file, oldFile, sinceCommit, sinceDate, latestCommit, latestDate, patterns)
      if (result.outcome === 'new') kbEntriesNew++
      else if (result.outcome === 're_detected') kbEntriesReDetected++
      continue
    }

    // Normal add/modify — or cross-boundary rename where old was non-KB:
    // treat the new KB path as a fresh add (matches the prior behavior).
    const relative = file.replace(/^knowledge\//, '')
    const codePaths = reverseMapKbTarget(relative, patterns)
    const outcome = upsertKbDriftEntry(kbState, relative, codePaths, sinceCommit, sinceDate, latestCommit, latestDate)
    if (outcome === 'new') kbEntriesNew++
    else if (outcome === 're_detected') kbEntriesReDetected++
  }

  // Advance both baselines to HEAD (always — cleanliness lives in the queue,
  // not in the baseline) and write both files once.
  if (headSha) {
    codeState.header = setBaseline(codeState.header, headSha)
    kbState.header = setBaseline(kbState.header, headSha)
  }
  writeCodeDriftEntries(codeState.header, codeState.entries)
  writeKbDriftEntries(kbState.header, kbState.entries)

  const codeEntriesWritten = codeEntriesNew + codeEntriesReDetected
  const kbEntriesWritten = kbEntriesNew + kbEntriesReDetected
  const noDrift = codeEntriesWritten === 0 && kbEntriesWritten === 0
  const ownedSubs = submodules.filter(s => !s.isShared).map(s => s.path)
  const sharedSubs = submodules.filter(s => s.isShared).map(s => s.path)
  const subParts = []
  if (ownedSubs.length > 0) subParts.push(`owned: ${ownedSubs.join(', ')}`)
  if (sharedSubs.length > 0) subParts.push(`shared: ${sharedSubs.join(', ')}`)
  const subInfo = subParts.length > 0 ? ` (submodules — ${subParts.join('; ')})` : ''

  const reDetectedTotal = codeEntriesReDetected + kbEntriesReDetected
  const reDetectedNote = reDetectedTotal > 0 ? ` (${reDetectedTotal} re-detected)` : ''

  const result = {
    code_entries: codeEntriesWritten,
    code_entries_new: codeEntriesNew,
    code_entries_re_detected: codeEntriesReDetected,
    kb_entries: kbEntriesWritten,
    kb_entries_new: kbEntriesNew,
    kb_entries_re_detected: kbEntriesReDetected,
    submodules_owned: ownedSubs,
    submodules_shared: sharedSubs,
    ...(stalePatterns.length > 0 && { stale_patterns: stalePatterns }),
    message: noDrift
      ? `No drift detected.${subInfo}`
      : `${codeEntriesWritten} code→KB entry(s) in sync/code-drift.md, ${kbEntriesWritten} KB→code entry(s) in sync/kb-drift.md${reDetectedNote}.${subInfo}`
  }

  const hasUnmappedKbEntries = kbEntriesWritten > 0 && (() => {
    try {
      const raw = fs.readFileSync(KB_DRIFT_PATH, 'utf8')
      return raw.includes('no mapped code paths')
    } catch { return false }
  })()

  if (!noDrift) {
    let instruction = 'To resolve drift entries:\n\n'
      + '1. Read sync/code-drift.md or sync/kb-drift.md to see pending entries\n'
      + '2. For each entry, read the KB target file\n'
      + '3. Update the KB file to reflect the code change (Edit / kb_write)\n'
      + '4. Read the KB file again to confirm the edit landed\n'
      + '5. THEN call kb_drift(summaries=[...]) to close the entry\n\n'
      + 'Do NOT call kb_drift(summaries) before verifying the KB file was actually updated. '
      + 'The tool only closes the queue entry — it does not write to the KB.'

    if (hasUnmappedKbEntries) {
      instruction += '\n\n⚠ One or more KB entries have no mapped code paths ("review manually"). '
        + 'Do NOT limit review to code you already know about. For each unmapped entry:\n'
        + '  a. Search the entire codebase for all files related to the KB feature (backend, frontend, DB, tests).\n'
        + '  b. Check every layer: controllers, services, DTOs, entities, FE components, forms, i18n, DB schema.\n'
        + '  c. Only confirm the entry after verifying ALL layers are consistent with the KB spec.'
    }

    if (submodules.length > 0) {
      const subHints = submodules.map(s => `  - Files under ${s.path}/ → git -C ${s.path} diff <sha> -- <relative-path>`).join('\n')
      instruction += '\n\nSubmodule git commands:\n'
        + 'Commit SHAs in the drift queue belong to submodule git histories, not the parent repo. '
        + 'Running git diff <sha> from the root will fail with "fatal: bad revision". Use:\n'
        + subHints
    }

    result._instruction = instruction
  }

  return result
}

// ── Phase 2a: code→kb resolved — KB updated ──────────────────────────────────

async function resolveWithSummaries(summaries) {
  const resolved = []

  for (const { kb_target, summary } of summaries) {
    if (!summary || !kb_target) continue
    resolved.push({ direction: 'code→kb', resolution: 'kb-updated', kb_target, summary })
  }

  const { entries, header } = readCodeDriftEntries()
  const kbTargets = summaries.map(s => s.kb_target)
  const remaining = entries.filter(e => !kbTargets.includes(e.kbTarget))
  writeCodeDriftEntries(header, remaining)

  appendToDriftLog(resolved)

  const kbTargetList = resolved.map(r => r.kb_target).join(', ')
  return {
    resolved: resolved.length,
    _instruction: `Queue entries closed for: ${kbTargetList}. `
      + 'Verify that each KB file above was actually updated before this call. '
      + 'If not, the drift queue is now clean but the KB is stale — '
      + 'read the KB file(s) to confirm, and use kb_write to fix any that were missed.'
  }
}

// ── Phase 2b: code→kb resolved — code file reverted ──────────────────────────

async function resolveReverted(reverted) {
  const codeFiles = reverted.map(r => r.code_file || r)
  const { entries, header } = readCodeDriftEntries()
  const resolved = []

  const updated = entries.map(entry => {
    const before = entry.codeFiles.length
    entry.codeFiles = entry.codeFiles.filter(f => !codeFiles.includes(f.path))
    if (entry.codeFiles.length < before) {
      resolved.push({ direction: 'code→kb', resolution: 'code-reverted', kb_target: entry.kbTarget, code_files: codeFiles })
    }
    return entry
  }).filter(entry => entry.codeFiles.length > 0)

  writeCodeDriftEntries(header, updated)
  appendToDriftLog(resolved)
  return { reverted: codeFiles.length }
}

// ── Phase 2c: kb→code resolved ────────────────────────────────────────────────

async function resolveKbConfirmed(kb_confirmed) {
  const kbFiles = kb_confirmed.map(r => r.kb_file || r)
  const rules = loadRules(KB_ROOT)
  const patterns = rules.getCodePathPatterns()

  const warnings = []
  const resolved = kbFiles.map(kb_file => {
    const codePaths = reverseMapKbTarget(kb_file, patterns)
    const unmapped = codePaths.length === 0
    if (unmapped) {
      warnings.push(`drift confirmed for "${kb_file}" but no code_path_patterns mapping exists in _rules.md. Future KB changes to this file will not trigger automatic drift detection. Recommended: add a code_path_patterns entry for this file.`)
    }
    return { direction: 'kb→code', resolution: 'confirmed', kb_file, ...(unmapped && { unmapped: true }) }
  })

  const { header, entries } = readKbDriftEntries()
  const remaining = entries.filter(e => !kbFiles.includes(e.kbFile))
  writeKbDriftEntries(header, remaining)

  appendToDriftLog(resolved)

  const result = { confirmed: kbFiles.length }
  if (warnings.length > 0) result.warnings = warnings
  return result
}

// ── Admin escape hatch: force_baseline / purge ───────────────────────────────

async function resetBaselines({ force_baseline, purge }) {
  const git = simpleGit(process.cwd())
  let sha = null
  if (force_baseline) {
    const arg = force_baseline === 'HEAD' ? 'HEAD' : force_baseline
    try {
      sha = (await git.revparse([arg])).trim()
    } catch {
      return { error: `cannot resolve force_baseline="${force_baseline}" via git rev-parse` }
    }
  }

  const codeState = readCodeDriftEntries()
  const kbState = readKbDriftEntries()

  // Capture raw pre-purge queue bodies before any writes. These get logged
  // verbatim so a purge is reconstructable without leaning on `git show`.
  let codeBodyBefore = ''
  let kbBodyBefore = ''
  if (purge) {
    codeBodyBefore = extractQueueBody(CODE_DRIFT_PATH)
    kbBodyBefore = extractQueueBody(KB_DRIFT_PATH)
  }
  const codeCountBefore = codeState.entries.length
  const kbCountBefore = kbState.entries.length

  if (sha) {
    codeState.header = setBaseline(codeState.header, sha)
    kbState.header = setBaseline(kbState.header, sha)
  }

  const codeEntries = purge ? [] : codeState.entries
  const kbEntries = purge ? [] : kbState.entries

  writeCodeDriftEntries(codeState.header, codeEntries)
  writeKbDriftEntries(kbState.header, kbEntries)

  if (purge) {
    appendToDriftLog([{
      event_type: 'purged',
      baseline: sha,
      code_count: codeCountBefore,
      kb_count: kbCountBefore,
      code_body: codeBodyBefore,
      kb_body: kbBodyBefore
    }])
  }

  return {
    baseline: sha,
    purged: !!purge,
    message: purge
      ? `Queue files cleared; both baselines set to ${sha ? sha.slice(0, 7) : '(unchanged)'}.`
      : `Both baselines set to ${sha ? sha.slice(0, 7) : '(unchanged)'}; queue entries preserved.`
  }
}

// ── Merge housekeeping: deduplicate baseline lines ───────────────────────────
//
// The queue files have `merge=union` in .gitattributes, which concatenates
// both sides on merge. Entry-level unions are intentional (different entries
// from different branches coalesce cleanly). But if both branches wrote
// baseline lines, the merged header ends up with multiple <!-- baseline: -->
// comments — and until deduped, parseBaseline returns only the last one while
// the older orphan lingers as noise. Called by the post-merge git hook.
async function dedupBaselines() {
  const git = simpleGit(process.cwd())
  const results = []
  const queues = [
    { filePath: CODE_DRIFT_PATH, read: readCodeDriftEntries, write: writeCodeDriftEntries },
    { filePath: KB_DRIFT_PATH, read: readKbDriftEntries, write: writeKbDriftEntries }
  ]
  for (const { filePath, read, write } of queues) {
    if (!fs.existsSync(filePath)) continue
    const content = fs.readFileSync(filePath, 'utf8')
    const shas = [...content.matchAll(BASELINE_RE)].map(m => m[1])
    if (shas.length < 2) continue

    let winner = shas[0]
    for (let i = 1; i < shas.length; i++) {
      const candidate = shas[i]
      if (candidate === winner) continue
      try {
        await git.raw(['merge-base', '--is-ancestor', winner, candidate])
        winner = candidate
      } catch {
        try {
          await git.raw(['merge-base', '--is-ancestor', candidate, winner])
        } catch {
          process.stderr.write(`[kb-drift] warning: diverged baseline SHAs in ${filePath} (${winner.slice(0, 7)} vs ${candidate.slice(0, 7)}); keeping ${candidate.slice(0, 7)}\n`)
          winner = candidate
        }
      }
    }

    const state = read()
    state.header = setBaseline(state.header, winner)
    write(state.header, state.entries)
    results.push({ file: filePath, kept: winner, dropped: shas.length - 1 })
    process.stderr.write(`[kb-drift] deduped ${shas.length} baseline lines in ${filePath}; kept ${winner.slice(0, 7)}\n`)
  }
  return { deduped: results }
}

// Extract the body (everything after the header) of a queue file as a raw
// string. Used to capture pre-purge content into the drift-log.
function extractQueueBody(filePath) {
  if (!fs.existsSync(filePath)) return ''
  const content = fs.readFileSync(filePath, 'utf8')
  const headerEnd = content.indexOf('\n## ')
  if (headerEnd === -1) return ''
  return content.slice(headerEnd + 1).trimEnd()
}

// ── code-drift.md parse / serialize ──────────────────────────────────────────

function readCodeDriftEntries() {
  ensureHeader(CODE_DRIFT_PATH, CODE_DRIFT_HEADER)
  const content = fs.readFileSync(CODE_DRIFT_PATH, 'utf8')
  const headerEnd = content.indexOf('\n## ')
  const header = headerEnd === -1 ? content : content.slice(0, headerEnd)
  const entriesStr = headerEnd === -1 ? '' : content.slice(headerEnd + 1)
  const blocks = entriesStr.split(/\n(?=## )/).filter(b => b.trim())

  const entries = blocks.map(block => {
    const headingMatch = block.match(/^## (.+)/)
    const kbTarget = headingMatch ? headingMatch[1].trim() : null
    const hasShared = /\*\*Shared module:\*\*\s*true/.test(block)
    const codeFiles = []
    for (const line of block.split('\n')) {
      const m = line.match(/^\s+-\s+`([^`]+)`(?:\s+←\s+renamed from\s+`([^`]+)`)?\s+—\s+since\s+`([^`]+)`\s+\(([^)]+)\)(?:,\s+latest\s+`([^`]+)`\s+\(([^)]+)\))?/)
      if (m) {
        codeFiles.push({
          path: m[1],
          ...(m[2] && { renamedFrom: m[2] }),
          sinceCommit: m[3],
          sinceDate: m[4],
          ...(m[5] && { latestCommit: m[5], latestDate: m[6] })
        })
      }
    }
    return { kbTarget, codeFiles, hasShared }
  }).filter(e => e.kbTarget)

  return { header, entries }
}

function writeCodeDriftEntries(header, entries) {
  const body = entries.map(entry => {
    const fileLines = entry.codeFiles.map(f => {
      const renameNote = f.renamedFrom ? ` ← renamed from \`${f.renamedFrom}\`` : ''
      const latestNote = f.latestCommit && f.latestCommit !== f.sinceCommit
        ? `, latest \`${f.latestCommit}\` (${f.latestDate})`
        : ''
      return `  - \`${f.path}\`${renameNote} — since \`${f.sinceCommit}\` (${f.sinceDate})${latestNote}`
    })
    const sharedLine = entry.hasShared ? '\n- **Shared module:** true' : ''
    // Detect when kb_target doesn't exist on disk but sibling files in the same
    // folder do — likely means the project uses a consolidated file instead of
    // one-file-per-table. Emit a hint so the agent updates the right file.
    const targetAbs = path.join(KB_ROOT, entry.kbTarget)
    let consolidatedHint = ''
    if (!fs.existsSync(targetAbs)) {
      const dir = path.dirname(targetAbs)
      if (fs.existsSync(dir)) {
        const siblings = fs.readdirSync(dir).filter(f => f.endsWith('.md'))
        if (siblings.length > 0) {
          const siblingList = siblings.map(s => `\`${path.join(path.dirname(entry.kbTarget), s)}\``).join(', ')
          consolidatedHint = `\n- **⚠ Target file does not exist.** The \`${path.dirname(entry.kbTarget)}/\` folder already contains: ${siblingList}. Check whether the content belongs in one of these existing files before creating a new one.`
        }
      }
    }
    return `## ${entry.kbTarget}\n\n- **KB target:** \`${entry.kbTarget}\`\n- **Code files:**\n${fileLines.join('\n')}${sharedLine}${consolidatedHint}`
  }).join('\n\n')
  fs.writeFileSync(CODE_DRIFT_PATH, header + (body ? '\n' + body + '\n' : ''), 'utf8')
}

/**
 * Upsert a code file into the in-memory code-drift state.
 * Returns 'new' when a file is added (new entry or new file under existing entry),
 * 're_detected' when an existing file's Latest was bumped to a newer commit,
 * or null when no change was made.
 */
function upsertCodeDriftEntry(state, kbTarget, codeFile, sinceCommit, sinceDate, latestCommit, latestDate, isShared, renamedFrom) {
  const existing = state.entries.find(e => e.kbTarget === kbTarget)
  const fileShape = {
    path: codeFile,
    sinceCommit,
    sinceDate,
    ...(latestCommit && { latestCommit, latestDate }),
    ...(renamedFrom && { renamedFrom })
  }

  if (existing) {
    const existingFile = existing.codeFiles.find(f => f.path === codeFile)
    if (existingFile) {
      // Re-edit under an existing entry — bump Latest to the newest commit we
      // saw in this run, keep Since pinned as the drift anchor.
      const latestToRecord = latestCommit || sinceCommit
      const latestDateToRecord = latestCommit ? latestDate : sinceDate
      const currentLatest = existingFile.latestCommit || existingFile.sinceCommit
      if (latestToRecord !== currentLatest) {
        existingFile.latestCommit = latestToRecord
        existingFile.latestDate = latestDateToRecord
        if (isShared) existing.hasShared = true
        return 're_detected'
      }
      return null
    }
    existing.codeFiles.push(fileShape)
    if (isShared) existing.hasShared = true
    return 'new'
  }

  state.entries.push({
    kbTarget,
    codeFiles: [fileShape],
    hasShared: !!isShared
  })
  return 'new'
}

// ── kb-drift.md parse / serialize ────────────────────────────────────────────

function readKbDriftEntries() {
  ensureHeader(KB_DRIFT_PATH, KB_DRIFT_HEADER)
  const content = fs.readFileSync(KB_DRIFT_PATH, 'utf8')
  const headerEnd = content.indexOf('\n## ')
  const header = headerEnd === -1 ? content : content.slice(0, headerEnd)
  const entriesStr = headerEnd === -1 ? '' : content.slice(headerEnd + 1)
  const blocks = entriesStr.split(/\n(?=## )/).filter(b => b.trim())

  const entries = blocks.map(block => {
    const headingMatch = block.match(/^## (.+)/)
    const kbFile = headingMatch ? headingMatch[1].trim() : null
    const renamedMatch = block.match(/\*\*Renamed from:\*\*\s*`([^`]+)`/)
    const sinceMatch = block.match(/\*\*Since:\*\*\s*`([^`]+)`\s*\(([^)]+)\)/)
    const latestMatch = block.match(/\*\*Latest:\*\*\s*`([^`]+)`\s*\(([^)]+)\)/)
    const unmapped = /KB spec changed without mapped code paths/.test(block)

    const codeAreas = []
    let inCodeAreas = false
    let inRefs = false
    const references = []
    let refCount = null
    const lines = block.split('\n')
    for (const line of lines) {
      if (/^- \*\*Code areas to review:\*\*/.test(line)) { inCodeAreas = true; inRefs = false; continue }
      if (/^- \*\*References to update:\*\*/.test(line)) {
        inCodeAreas = false; inRefs = true
        const countMatch = line.match(/\*\*References to update:\*\*\s*(\d+)\s*file\(s\)\s*contain\s*`\[\[([^\]]+)\]\]`/)
        if (countMatch) refCount = { count: parseInt(countMatch[1], 10), anchor: countMatch[2] }
        else if (/none found/.test(line)) refCount = { count: 0, anchor: null }
        continue
      }
      if (/^- \*\*/.test(line)) { inCodeAreas = false; inRefs = false; continue }
      if (inCodeAreas) {
        const m = line.match(/^\s+-\s+`([^`]+)`/)
        if (m) codeAreas.push(m[1])
      }
      if (inRefs) {
        const m = line.match(/^\s+-\s+`([^`]+)`/)
        if (m) references.push(m[1])
      }
    }

    return {
      kbFile,
      ...(renamedMatch && { renamedFrom: renamedMatch[1] }),
      codeAreas,
      ...(refCount && { refCount }),
      references,
      ...(sinceMatch && { sinceCommit: sinceMatch[1], sinceDate: sinceMatch[2] }),
      ...(latestMatch && { latestCommit: latestMatch[1], latestDate: latestMatch[2] }),
      unmapped
    }
  }).filter(e => e.kbFile)

  return { header, entries }
}

function writeKbDriftEntries(header, entries) {
  const body = entries.map(entry => {
    const areaLines = entry.codeAreas.length > 0
      ? entry.codeAreas.map(p => `  - \`${p}\``).join('\n')
      : '  - _(no mapped code paths — review manually)_'
    const renamedLine = entry.renamedFrom ? `\n- **Renamed from:** \`${entry.renamedFrom}\`` : ''
    let refsLine = ''
    if (entry.refCount) {
      if (entry.refCount.count > 0 && entry.refCount.anchor) {
        refsLine = `\n- **References to update:** ${entry.refCount.count} file(s) contain \`[[${entry.refCount.anchor}]]\``
        if (entry.references.length > 0) {
          refsLine += '\n  - ' + entry.references.map(f => `\`${f}\``).join('\n  - ')
        }
      } else {
        refsLine = '\n- **References to update:** none found'
      }
    }
    const sinceLine = entry.sinceCommit ? `\n- **Since:** \`${entry.sinceCommit}\` (${entry.sinceDate})` : ''
    const latestLine = entry.latestCommit && entry.latestCommit !== entry.sinceCommit
      ? `\n- **Latest:** \`${entry.latestCommit}\` (${entry.latestDate})`
      : ''
    const unmappedHint = entry.unmapped
      ? `\n- **⚠ KB spec changed without mapped code paths.** Verify that the implementation still matches this spec. To enable automatic code-area tracking, add a \`code_path_patterns\` entry in \`_rules.md\` for this file.`
      : ''
    return `## ${entry.kbFile}\n\n- **KB file:** \`${entry.kbFile}\`${renamedLine}${refsLine}\n- **Code areas to review:**\n${areaLines}${sinceLine}${latestLine}${unmappedHint}`
  }).join('\n\n')
  fs.writeFileSync(KB_DRIFT_PATH, header + (body ? '\n' + body + '\n' : ''), 'utf8')
}

/**
 * Upsert a KB file into the in-memory kb-drift state.
 * Returns 'new' when a fresh entry is created, 're_detected' when an existing
 * entry's Latest was bumped to a newer commit, or null when no change.
 */
function upsertKbDriftEntry(state, kbFile, codeAreas, sinceCommit, sinceDate, latestCommit, latestDate) {
  const existing = state.entries.find(e => e.kbFile === kbFile)
  if (existing) {
    const latestToRecord = latestCommit || sinceCommit
    const latestDateToRecord = latestCommit ? latestDate : sinceDate
    const currentLatest = existing.latestCommit || existing.sinceCommit
    if (latestToRecord !== currentLatest) {
      existing.latestCommit = latestToRecord
      existing.latestDate = latestDateToRecord
      return 're_detected'
    }
    return null
  }

  state.entries.push({
    kbFile,
    codeAreas: [...codeAreas],
    references: [],
    sinceCommit,
    sinceDate,
    ...(latestCommit && { latestCommit, latestDate }),
    unmapped: codeAreas.length === 0
  })
  return 'new'
}

// ── Rename/move handling ─────────────────────────────────────────────────────

/**
 * Handle a code file rename. Resolves KB targets for both old and new paths.
 * - Same target: replace old path with new in existing entry
 * - Different targets: remove from old, add to new with rename annotation
 * - No match for new: flag stale pattern warning
 * Returns { outcome: 'new'|'re_detected'|null, stalePattern }.
 */
function handleCodeRename(state, newPath, oldPath, sinceCommit, sinceDate, latestCommit, latestDate, isShared, patterns) {
  const oldMatches = matchAllPatterns(oldPath, patterns)
  const newMatches = matchAllPatterns(newPath, patterns)
  const oldTarget = oldMatches.length > 0 ? resolveKbTarget(oldMatches[0], oldPath) : null
  const newTarget = newMatches.length > 0 ? resolveKbTarget(newMatches[0], newPath) : null

  let outcome = null
  let stalePattern = null

  if (oldTarget && newTarget && oldTarget === newTarget) {
    replaceCodeFileInEntry(state, oldTarget, oldPath, newPath, sinceCommit, sinceDate, latestCommit, latestDate)
    outcome = 'new'
  } else {
    if (oldTarget) removeCodeFileFromEntry(state, oldTarget, oldPath)
    if (newTarget) {
      outcome = upsertCodeDriftEntry(state, newTarget, newPath, sinceCommit, sinceDate, latestCommit, latestDate, isShared, oldPath)
    }
  }

  if (!newTarget && oldTarget) {
    stalePattern = {
      intent: oldMatches[0].intent,
      kb_target: oldTarget,
      moved: { from: oldPath, to: newPath }
    }
  }

  return { outcome, stalePattern }
}

/**
 * Handle a KB file rename. Finds files that reference the old path and
 * creates a kb-drift entry with rename metadata.
 * Returns { outcome: 'new'|'re_detected'|null }.
 */
function handleKbRename(state, newPath, oldPath, sinceCommit, sinceDate, latestCommit, latestDate, patterns) {
  const oldRelative = oldPath.replace(/^knowledge\//, '')
  const newRelative = newPath.replace(/^knowledge\//, '')

  if (state.entries.some(e => e.kbFile === newRelative)) {
    return { outcome: null }
  }

  const graph = loadGraph(KB_ROOT)
  const oldWithoutExt = oldRelative.replace(/\.md$/, '')
  const dependents = getDependents(graph, oldWithoutExt)
  const refCount = dependents.length
  const refFiles = dependents.map(d => d.path)

  const codePaths = reverseMapKbTarget(newRelative, patterns)

  state.entries.push({
    kbFile: newRelative,
    renamedFrom: oldRelative,
    codeAreas: codePaths,
    refCount: { count: refCount, anchor: refCount > 0 ? oldWithoutExt : null },
    references: refFiles,
    sinceCommit,
    sinceDate,
    ...(latestCommit && { latestCommit, latestDate }),
    unmapped: false
  })
  return { outcome: 'new' }
}

/**
 * Replace a code file path in an existing code-drift entry (same KB target rename).
 */
function replaceCodeFileInEntry(state, kbTarget, oldPath, newPath, sinceCommit, sinceDate, latestCommit, latestDate) {
  const existing = state.entries.find(e => e.kbTarget === kbTarget)
  const shape = {
    path: newPath,
    sinceCommit,
    sinceDate,
    ...(latestCommit && { latestCommit, latestDate }),
    renamedFrom: oldPath
  }
  if (!existing) {
    upsertCodeDriftEntry(state, kbTarget, newPath, sinceCommit, sinceDate, latestCommit, latestDate, false, oldPath)
    return
  }
  const idx = existing.codeFiles.findIndex(f => f.path === oldPath)
  if (idx !== -1) existing.codeFiles[idx] = shape
  else existing.codeFiles.push(shape)
}

/**
 * Remove a single code file from its code-drift entry. Removes the entry entirely if empty.
 */
function removeCodeFileFromEntry(state, kbTarget, codePath) {
  const existing = state.entries.find(e => e.kbTarget === kbTarget)
  if (!existing) return
  existing.codeFiles = existing.codeFiles.filter(f => f.path !== codePath)
  if (existing.codeFiles.length === 0) {
    state.entries = state.entries.filter(e => e.kbTarget !== kbTarget)
  }
}

// ── Shared queue helpers ──────────────────────────────────────────────────────

function ensureHeader(filePath, header) {
  if (!fs.existsSync(filePath)) {
    fs.mkdirSync(path.dirname(filePath), { recursive: true })
    fs.writeFileSync(filePath, header, 'utf8')
    return
  }
  const content = fs.readFileSync(filePath, 'utf8')
  if (content.startsWith('<!-- AUTO-GENERATED')) return

  // Sentinel is missing — rewrite from template, but preserve any pre-existing
  // baseline line so we don't lose the anchor.
  const preserved = parseBaseline(content)
  const newHeader = preserved ? setBaseline(header, preserved) : header
  fs.writeFileSync(filePath, newHeader + content, 'utf8')
}

function appendToDriftLog(entries) {
  if (!fs.existsSync(DRIFT_LOG_DIR)) fs.mkdirSync(DRIFT_LOG_DIR, { recursive: true })
  const logPath = getDriftLogPath()
  ensureHeader(logPath, DRIFT_LOG_HEADER)
  const date = new Date().toISOString().split('T')[0]
  let block = ''
  for (const entry of entries) {
    if (entry.event_type === 'purged') {
      const shaDisplay = entry.baseline ? entry.baseline.slice(0, 7) : '(unchanged)'
      block += `\n## ${date} · PURGE\n`
      block += `\n- **New baseline:** \`${shaDisplay}\``
      block += `\n- **Code entries cleared:** ${entry.code_count || 0}`
      block += `\n- **KB entries cleared:** ${entry.kb_count || 0}`
      block += '\n- **Pre-purge code-drift.md body:**\n\n```markdown\n' + (entry.code_body || '(empty)') + '\n```\n'
      block += '\n- **Pre-purge kb-drift.md body:**\n\n```markdown\n' + (entry.kb_body || '(empty)') + '\n```\n'
      continue
    }
    if (entry.event_type === 're-bootstrap') {
      const oldShort = entry.old_sha ? entry.old_sha.slice(0, 7) : '?'
      const newShort = entry.new_sha ? entry.new_sha.slice(0, 7) : '(none)'
      block += `\n## ${date} · RE-BOOTSTRAP · ${entry.repo} (old ${oldShort}, new ${newShort})\n`
      block += `\n- **Queue:** ${entry.queue || 'both'}`
      block += `\n- **Old baseline:** \`${entry.old_sha || '(unknown)'}\``
      block += `\n- **New baseline:** \`${entry.new_sha || '(none — skipped)'}\``
      block += `\n- **Resolver:** ${entry.resolver_used || '(n/a)'}\n`
      continue
    }
    block += `\n## ${date} · RESOLVED · ${entry.direction}\n`
    if (entry.kb_target) block += `\n- **KB target:** \`${entry.kb_target}\``
    if (entry.kb_file) block += `\n- **KB file:** \`${entry.kb_file}\``
    if (entry.code_file) block += `\n- **Code file:** \`${entry.code_file}\``
    if (entry.code_files) block += `\n- **Code files:** ${entry.code_files.map(f => `\`${f}\``).join(', ')}`
    block += `\n- **Resolution:** ${entry.resolution}`
    if (entry.renamed_from) block += `\n- **Renamed from:** \`${entry.renamed_from}\``
    if (entry.unmapped) block += `\n- **⚠ Unmapped:** no code_path_patterns entry — drift detection inactive for this KB file`
    if (entry.summary) block += `\n- **Summary:** ${entry.summary}`
    block += '\n'
  }
  if (block) fs.appendFileSync(logPath, block)
}

// ── kb→code reverse mapping ───────────────────────────────────────────────────

function reverseMapKbTarget(kbRelative, patterns) {
  const codePaths = []
  for (const pattern of patterns) {
    if (matchesKbTargetPattern(pattern.kb_target, kbRelative)) {
      codePaths.push(...(pattern.paths || []))
    }
  }
  return [...new Set(codePaths)]
}

function matchesKbTargetPattern(patternTarget, actualPath) {
  const regexStr = patternTarget
    .replace(/\./g, '\\.')
    .replace(/\{name\}/g, '[^/]+')
  try {
    return new RegExp(`^${regexStr}$`).test(actualPath)
  } catch {
    return patternTarget === actualPath
  }
}

function isKbContentFile(file) {
  if (!file.startsWith('knowledge/')) return false
  const rel = file.replace(/^knowledge\//, '')
  if (rel.startsWith('_') || rel.startsWith('sync/') || rel.startsWith('exports/') || rel.startsWith('assets/')) return false
  return file.endsWith('.md')
}

// ── git helpers ───────────────────────────────────────────────────────────────

/**
 * Get the submodule's commit SHA as recorded in the parent repo at a given commit.
 * Uses git ls-tree to read the submodule pointer (mode 160000) without checking out.
 * Returns null if the submodule didn't exist at that commit.
 */
async function getSubmodulePointerAt(git, commitSha, subPath) {
  try {
    const line = (await git.raw(['ls-tree', commitSha, subPath])).trim()
    const match = line.match(/^160000 commit ([a-f0-9]+)/)
    return match ? match[1] : null
  } catch { return null }
}

/**
 * Bootstrap fallback — only invoked when a queue header has no baseline line yet
 * (first deployment, or a queue manually cleared), or when a stored baseline
 * is unreachable and we re-bootstrap. Graduated fallback:
 * upstream tracking → remote branch → closest parent branch → null.
 * Returns null when no reliable baseline exists (caller skips with warning).
 * Optional `meta` out-param: caller can pass `{}` and read `meta.via` to learn
 * which resolver branch produced the ref — used by the re-bootstrap audit log.
 */
async function resolveLastSyncRef(git, remote, meta) {
  try {
    const upstream = await git.raw(['rev-parse', '--abbrev-ref', '@{upstream}'])
    if (upstream && upstream.trim()) {
      if (meta) meta.via = 'upstream'
      return upstream.trim()
    }
  } catch { /* no upstream configured */ }

  let validRemote = remote
  if (remote) {
    try {
      const remotes = (await git.raw(['remote'])).split('\n').filter(r => r.trim())
      if (!remotes.includes(remote)) {
        const cwd = git._executor?.cwd || 'unknown'
        process.stderr.write(`[kb-drift] warning: remote '${remote}' not found in ${cwd} — available remotes: ${remotes.join(', ') || 'none'}. Skipping drift detection.\n`)
        process.stderr.write(`[kb-drift]   fix: git -C ${cwd} remote rename <correct> ${remote}\n`)
        validRemote = null
      }
    } catch { validRemote = null }
  }

  if (validRemote) {
    try {
      const branch = (await git.raw(['symbolic-ref', '--short', 'HEAD'])).trim()
      const remoteBranch = `${validRemote}/${branch}`
      await git.raw(['rev-parse', remoteBranch])
      if (meta) meta.via = 'remote-branch'
      return remoteBranch
    } catch { /* remote branch doesn't exist yet */ }
  }

  if (validRemote) {
    try {
      const remoteBranches = (await git.raw(['for-each-ref', '--format=%(refname:short)', `refs/remotes/${validRemote}/`]))
        .split('\n')
        .filter(b => b.trim() && !b.includes('/HEAD'))
      let closest = null
      let minDistance = Infinity
      for (const rb of remoteBranches) {
        try {
          const mb = (await git.raw(['merge-base', 'HEAD', rb])).trim()
          if (!mb) continue
          const count = parseInt((await git.raw(['rev-list', '--count', `${mb}..HEAD`])).trim(), 10)
          if (count < minDistance) {
            minDistance = count
            closest = mb
          }
        } catch { /* skip branches with no common ancestor */ }
      }
      if (closest) {
        if (minDistance > 20) {
          process.stderr.write(`[kb-drift] hint: ${minDistance} commits since parent branch — consider pulling/rebasing to reduce drift noise\n`)
        }
        if (meta) meta.via = 'closest-parent'
        return closest
      }
    } catch { /* no remote branches available */ }
  }

  if (meta) meta.via = null
  return null
}

function parseNameStatus(output) {
  return output.split('\n').filter(l => l.trim()).map(line => {
    const parts = line.split('\t')
    const statusCode = parts[0].trim()
    if (statusCode.startsWith('R') || statusCode.startsWith('C')) {
      const similarity = parseInt(statusCode.slice(1), 10) || 0
      return { status: statusCode.charAt(0), oldPath: parts[1], path: parts[2], similarity }
    }
    return { status: statusCode.charAt(0), path: parts[1] }
  })
}

/**
 * Check whether a SHA/ref resolves to a real commit in this repo. Used to
 * guard against stored baselines that have been GC'd after a squash-merge or
 * that were never fetched locally — those cases otherwise fall through to
 * getChangedFiles's empty-tree fallback and surface every file as changed.
 */
async function baselineReachable(git, sha) {
  if (!sha) return false
  try {
    await git.raw(['cat-file', '-e', `${sha}^{commit}`])
    return true
  } catch { return false }
}

async function getChangedFiles(git, ref) {
  try {
    const result = await git.diff(['--name-status', '-M', ref, 'HEAD'])
    return parseNameStatus(result)
  } catch {
    try {
      const result = await git.diff(['--name-status', '-M', '4b825dc642cb6eb9a060e54bf899d15f7dcb6820', 'HEAD'])
      return parseNameStatus(result)
    } catch {
      return []
    }
  }
}

// Build Map<path, [{sha, date}, ...]> in chronological order for baseline..HEAD.
// One `git log` call. A rename commit attributes to the new path (what git's
// --name-status reports on that line); pre-rename history under the old path
// is retained under the old path key — resolveCommitRange merges both.
// Returns an empty Map when the range has no commits or git fails.
async function buildCommitIndex(git, baseline) {
  if (!baseline) return new Map()
  const index = new Map()
  let output
  try {
    output = await git.raw(['log', '--name-status', '-M', '--reverse',
      '--pretty=format:__C %H %cI', `${baseline}..HEAD`])
  } catch { return index }
  if (!output) return index

  let currentSha = null
  let currentDate = null
  for (const line of output.split('\n')) {
    if (line.startsWith('__C ')) {
      const m = line.match(/^__C ([a-f0-9]+) (.+)$/)
      if (m) {
        currentSha = m[1]
        currentDate = m[2].split('T')[0]
      }
      continue
    }
    if (!line.trim() || !currentSha) continue
    const parts = line.split('\t')
    const code = parts[0].trim()
    if (!code) continue
    const entry = { sha: currentSha, date: currentDate }
    if (code.startsWith('R') || code.startsWith('C')) {
      const newPath = parts[2]
      if (newPath) appendCommit(index, newPath, entry)
    } else {
      const p = parts[1]
      if (p) appendCommit(index, p, entry)
    }
  }
  return index
}

function appendCommit(index, key, entry) {
  const list = index.get(key)
  if (list) list.push(entry)
  else index.set(key, [entry])
}

// Merge chronologies for new+old paths, return earliest/latest commit pair.
// `oldPath` lets renamed files pick up commits from before the rename.
// Returns null if no commits found — caller should fall back to HEAD info.
function resolveCommitRange(index, newPath, oldPath) {
  const commits = []
  if (index.has(newPath)) commits.push(...index.get(newPath))
  if (oldPath && oldPath !== newPath && index.has(oldPath)) commits.push(...index.get(oldPath))
  if (commits.length === 0) return null
  commits.sort((a, b) => a.date.localeCompare(b.date))
  const first = commits[0]
  const last = commits[commits.length - 1]
  const sinceCommit = first.sha.slice(0, 7)
  const latestCommit = last.sha.slice(0, 7)
  return {
    sinceCommit,
    sinceDate: first.date,
    latestCommit: latestCommit !== sinceCommit ? latestCommit : null,
    latestDate: latestCommit !== sinceCommit ? last.date : null
  }
}

async function detectSubmodules() {
  const gitmodulesPath = path.join(process.cwd(), '.gitmodules')
  if (!fs.existsSync(gitmodulesPath)) return []
  const content = fs.readFileSync(gitmodulesPath, 'utf8')
  const submodules = []
  const blocks = content.split(/(?=\[submodule\s+"[^"]+"\])/).filter(b => b.trim())
  for (const block of blocks) {
    const nameMatch = block.match(/\[submodule\s+"([^"]+)"\]/)
    const pathMatch = block.match(/path\s*=\s*(.+)/)
    if (!nameMatch || !pathMatch) continue
    const name = nameMatch[1].trim()
    const subPath = pathMatch[1].trim()
    const fullPath = path.join(process.cwd(), subPath)
    const isShared = /kb-shared\s*=\s*true/.test(block)
    if (fs.existsSync(fullPath)) submodules.push({ name, path: subPath, fullPath, isShared })
  }
  return submodules
}

module.exports = {
  runTool,
  definition: {
    name: 'kb_drift',
    description: 'Bidirectional drift detection. Phase 1: writes entries to sync/code-drift.md (keyed by KB target, tracks all code files + since-commit) and sync/kb-drift.md (keyed by KB file). Multiple commits accumulate automatically. Phase 2: summaries=KB updated, reverted=code file reverted, kb_confirmed=kb→code reviewed. To review pending entries: read the queue files then fetch diffs with git show.',
    inputSchema: {
      type: 'object',
      properties: {
        since: { type: 'string', description: 'Commit SHA or "last-sync"', default: 'last-sync' },
        summaries: { type: 'array', description: 'Phase 2a: code correct — write KB notes and close code-drift.md entries', items: { type: 'object', properties: { kb_target: { type: 'string' }, summary: { type: 'string' } }, required: ['kb_target', 'summary'] } },
        reverted: { type: 'array', description: 'Phase 2b: code reverted — close code-drift.md entries without writing KB notes', items: { type: 'object', properties: { code_file: { type: 'string' } }, required: ['code_file'] } },
        kb_confirmed: { type: 'array', description: 'Phase 2c: kb→code reviewed — close kb-drift.md entries', items: { type: 'object', properties: { kb_file: { type: 'string' } }, required: ['kb_file'] } },
        force_baseline: { type: 'string', description: 'Admin escape hatch: reset both queue baselines to this SHA (or "HEAD"). Use when the queue has gone stale and needs a manual reset.' },
        purge: { type: 'boolean', description: 'With force_baseline: also clear all queue entries. Default: false.' }
      }
    }
  }
}
