import * as fs from 'fs'
import * as path from 'path'
import matter from 'gray-matter'
import * as yaml from 'js-yaml'
import { runTool as reindex } from './reindex'
import { runTool as autotag } from './autotag'
import { loadRules } from '../lib/rules'
import type { ToolDefinition } from '../src/types/tool'

const KB_ROOT = 'knowledge'

interface RelatedFile { path: string; id?: string; shared_tags: string[] }

// Folders that are not KB content — skip folder validation
const NON_CONTENT_DIRS = new Set([
  '_mcp', '_templates', 'exports', 'assets', 'sync',
  '.obsidian', 'node_modules', 'drift-log'
])

function validateKbPath(filePath: string): string | null {
  const resolved = path.resolve(filePath)
  const kbDir = path.resolve(KB_ROOT)
  if (!resolved.startsWith(kbDir + path.sep) && resolved !== kbDir) {
    return 'file_path must be inside the knowledge/ directory'
  }
  return null
}

function validateFolder(filePath: string): string | null {
  const relative = path.relative(KB_ROOT, filePath)
  const topFolder = relative.split(path.sep)[0]

  // Skip validation for non-content directories and root-level files
  if (!topFolder || NON_CONTENT_DIRS.has(topFolder) || !relative.includes(path.sep)) {
    return null
  }

  const rules = loadRules(KB_ROOT)
  const validFolders = Object.keys(rules.getDepthPolicy().overrides || {})

  if (!validFolders.includes(topFolder)) {
    return `Unknown KB folder: '${topFolder}'. Valid content folders: ${validFolders.join(', ')}. Use kb_scaffold to create files in the correct location, or update _rules.md depth_policy if this is a new folder.`
  }
  return null
}

function findRelatedFiles(filePath: string, content: string): RelatedFile[] {
  try {
    const parsed = matter(content)
    const data = parsed.data as Record<string, unknown>
    const fileTags = (data.tags as string[]) || []
    const fileDeps = (data.depends_on as string[]) || []
    const fileId = (data.id as string) || path.basename(filePath, '.md')

    if (fileTags.length === 0) return []

    const indexPath = path.join(KB_ROOT, '_index.yaml')
    if (!fs.existsSync(indexPath)) return []

    const raw = fs.readFileSync(indexPath, 'utf8').replace(/^#[^\n]*\n/, '')
    const index = yaml.load(raw) as { files?: Record<string, { id?: string; tags?: string[] }> }

    const candidates: RelatedFile[] = []
    for (const [fp, entry] of Object.entries(index.files || {})) {
      if (entry.id === fileId) continue
      if ((entry.id && fileDeps.includes(entry.id)) || fileDeps.includes(fp.replace(/\.md$/, ''))) continue

      const overlap = (entry.tags || []).filter(t => fileTags.includes(t))
      if (overlap.length >= 2) {
        candidates.push({ path: fp, id: entry.id, shared_tags: overlap })
      }
    }

    return candidates
      .sort((a, b) => b.shared_tags.length - a.shared_tags.length)
      .slice(0, 3)
  } catch {
    return []
  }
}

async function runTool({ file_path, content }: { file_path?: string; content?: string } = {}): Promise<Record<string, unknown>> {
  if (!file_path) return { error: 'file_path is required' }
  if (!content) return { error: 'content is required' }

  // Path traversal guard — must stay inside knowledge/
  const pathError = validateKbPath(file_path)
  if (pathError) return { error: pathError }

  // Never write Tier 1 auto-generated files directly
  if (file_path.endsWith('_index.yaml')) {
    return { error: '_index.yaml is auto-generated by kb_reindex. Let reindex run automatically.' }
  }
  if (file_path.includes('sync/drift-log/')) {
    return { error: 'sync/drift-log/ files are an auto-generated audit trail. Use kb_drift({ summaries/reverted/kb_confirmed }) to resolve entries.' }
  }
  if (file_path.includes('sync/code-drift.md') || file_path.includes('sync/kb-drift.md')) {
    return { error: 'Drift queue files are managed by kb_drift. Use kb_drift({ summaries/reverted/kb_confirmed }) to resolve entries.' }
  }
  if (file_path.includes('sync/standards-drift.md') || file_path.includes('sync/standards-backlog.md')) {
    return { error: 'Standards conformance queue files are managed by kb_conform. Use kb_conform({ submit_judgments / applied / exempted / promoted / dismissed }) to resolve entries.' }
  }

  // Validate folder against _rules.md depth_policy
  const folderError = validateFolder(file_path)
  if (folderError) return { error: folderError }

  // Ensure parent directory exists (only for validated folders)
  const dir = path.dirname(file_path)
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true })
  }

  // Write the file
  fs.writeFileSync(file_path, content, 'utf8')

  // Always call reindex as final step
  const reindexResult = await reindex({}) as Record<string, unknown> & { lint_errors?: number; lint_warnings?: number }

  // Auto-tag the written file (fast mode, single file)
  await autotag({ file_path, mode: 'fast', skipReindex: true })

  // Build guidance hints from lint results
  const guidance: string[] = []
  if ((reindexResult.lint_errors ?? 0) > 0) {
    guidance.push('Fix lint errors before proceeding — they indicate structural problems in the written file.')
  }
  if ((reindexResult.lint_warnings ?? 0) > 0) {
    guidance.push('Review lint warnings — they may indicate stale references, type mismatches, or unfilled placeholders.')
  }

  // Find related files for cross-referencing
  const suggestions = findRelatedFiles(file_path, content)

  const result: Record<string, unknown> = {
    written: true,
    file_path,
    lint_errors: reindexResult.lint_errors,
    lint_warnings: reindexResult.lint_warnings,
    reindex_result: reindexResult
  }

  // Post-write hook for standards/** — synchronous aspirational sweep so the
  // user immediately sees what got queued. Reindex above already rebuilt
  // _index.yaml with the new rules, so conform's standards index sees them.
  // Skipped on lint errors: a malformed standard would produce noisy or
  // wrong queue entries; better to fail loudly via lint and let the user fix
  // it before the sweep runs.
  if (isStandardFile(file_path)) {
    // Skip-decision is scoped to THIS file's lint errors, not the global KB
    // count — a pre-existing broken file elsewhere must not block sweeps for
    // a clean write here.
    const { runTool: lint } = require('./lint') as typeof import('./lint')
    const fileLint = await lint({ file_path })
    const fileLintErrors = fileLint.error_count

    if (fileLintErrors > 0) {
      // Surface the skip explicitly so the user isn't left guessing why
      // the field is missing or empty.
      result.aspirational_sweep = {
        skipped: 'lint_errors',
        lint_errors: fileLintErrors,
        note: 'Aspirational sweep skipped because the standard has lint errors. Fix them and rewrite to trigger the sweep.'
      }
    } else {
      try {
        // conform is still CJS (converts later this phase); typed result slice.
        const { runTool: conform } = require('./conform') as {
          runTool: (args: Record<string, unknown>) => Promise<{
            error?: string
            requested_evaluations?: unknown[]
            files_checked?: number
            n_a_count?: number
            sprawl_warnings?: unknown[]
          }>
        }
        const sweepResult = await conform({
          mode: 'aspirational',
          scope: file_path.replace(/^knowledge\//, ''),
          include_diffs: false
        })
        if (sweepResult && !sweepResult.error) {
          result.aspirational_sweep = {
            mode: 'aspirational',
            requested_evaluations: sweepResult.requested_evaluations || [],
            files_checked: sweepResult.files_checked || 0,
            n_a_count: sweepResult.n_a_count || 0,
            ...(sweepResult.sprawl_warnings && sweepResult.sprawl_warnings.length > 0 && { sprawl_warnings: sweepResult.sprawl_warnings }),
            note: ((sweepResult.requested_evaluations || []).length > 0
              ? 'Run kb_conform({ mode: "aspirational", submit_judgments: [...] }) to evaluate; failures land in sync/standards-backlog.md (advisory).'
              : 'Aspirational sweep ran; no evaluations needed (deterministic rules only or no matching files).')
          }
        } else if (sweepResult && sweepResult.error) {
          result.aspirational_sweep = { error: sweepResult.error }
        }
      } catch (e) {
        // Non-fatal: write succeeded, sweep failed. Surface the error but don't
        // make the write fail — the user can rerun kb_conform manually.
        result.aspirational_sweep = { error: `sweep failed: ${(e as Error).message}` }
      }
    }
  }

  if (guidance.length > 0) result.guidance = guidance
  if (suggestions.length > 0) {
    result.related_suggestions = suggestions
    result._hint = `Consider adding [[wikilinks]] to these related files: ${suggestions.map(s => s.id).join(', ')}`
  }

  return result
}

function isStandardFile(filePath: string): boolean {
  // Match knowledge/standards/<group>/<id>.md (any depth allowed under group)
  const norm = filePath.replace(/\\/g, '/')
  return /^knowledge\/standards\/[^/]+\/.+\.md$/.test(norm)
}

const definition: ToolDefinition = {
  name: 'kb_write',
  description: 'Write a KB file and automatically reindex. Never write _index.yaml directly.',
  inputSchema: {
    type: 'object',
    required: ['file_path', 'content'],
    properties: {
      file_path: { type: 'string', description: 'Path to the KB file (e.g. knowledge/specs/features/my-feature.md)' },
      content: { type: 'string', description: 'Full file content including YAML front-matter' }
    }
  }
}

export { runTool, definition }
