const fs = require('fs')
const path = require('path')
const { runTool: reindex } = require('./reindex')

function validateKbPath(filePath) {
  const resolved = path.resolve(filePath)
  const kbDir = path.resolve('knowledge')
  if (!resolved.startsWith(kbDir + path.sep) && resolved !== kbDir) {
    return 'file_path must be inside the knowledge/ directory'
  }
  return null
}

async function runTool({ file_path, content }) {
  if (!file_path) return { error: 'file_path is required' }
  if (!content) return { error: 'content is required' }

  // Path traversal guard — must stay inside knowledge/
  const pathError = validateKbPath(file_path)
  if (pathError) return { error: pathError }

  // Never write Tier 1 auto-generated files directly
  if (file_path.endsWith('_index.yaml')) {
    return { error: '_index.yaml is auto-generated by kb_reindex. Let reindex run automatically.' }
  }
  if (file_path.includes('sync/drift-log/')) {
    return { error: 'sync/drift-log/ files are an auto-generated audit trail. Use kb_drift({ summaries/reverted/kb_confirmed }) to resolve entries.' }
  }
  if (file_path.includes('sync/code-drift.md') || file_path.includes('sync/kb-drift.md')) {
    return { error: 'Drift queue files are managed by kb_drift. Use kb_drift({ summaries/reverted/kb_confirmed }) to resolve entries.' }
  }

  // Ensure parent directory exists
  const dir = path.dirname(file_path)
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true })
  }

  // Write the file
  fs.writeFileSync(file_path, content, 'utf8')

  // Always call reindex as final step
  const reindexResult = await reindex({})

  return {
    written: true,
    file_path,
    lint_errors: reindexResult.lint_errors,
    lint_warnings: reindexResult.lint_warnings,
    reindex_result: reindexResult
  }
}

module.exports = { runTool }
