// Drift queue I/O: read/write/upsert/mutate for code-drift.md and kb-drift.md,
// header constants, acknowledgement markers, audit log, fingerprint
// stamping, and post-merge baseline dedup. Everything that touches the queue
// files on disk lives here.

const fs = require('fs')
const path = require('path')
const simpleGit = require('simple-git')
const { matchAllPatterns, resolveKbTarget } = require('../../lib/patterns')
const { loadGraph, getDependents } = require('../../lib/graph')
const { KB_ROOT } = require('../../lib/kb-constants')
const { BASELINE_RE, parseBaseline, setBaseline } = require('./baseline')
const { reverseMapKbTarget } = require('./kb-match')

const CODE_DRIFT_PATH = path.join(KB_ROOT, 'sync/code-drift.md')
const KB_DRIFT_PATH = path.join(KB_ROOT, 'sync/kb-drift.md')
const DRIFT_LOG_DIR = path.join(KB_ROOT, 'sync/drift-log')

function getDriftLogPath() {
  const d = new Date()
  const month = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`
  return path.join(DRIFT_LOG_DIR, `${month}.md`)
}

// ── Headers ──────────────────────────────────────────────────────────────────
//
// Merge protocol guidance shared between both queue headers. The files are
// merged with `merge=union` (see .gitattributes): different entries coalesce
// cleanly, same-entry conflicts are real and intentional, and duplicate
// baseline lines are collapsed by the post-merge hook (or manually — keep
// the descendant SHA).
const MERGE_PROTOCOL_NOTE = `> **On merge conflicts:** queue files use \`merge=union\` — different entries from different branches coalesce automatically. If the same entry appears twice, dedupe by merging the two: keep the earlier \`Since\` commit (the true drift anchor) and the later \`Latest\` commit (the most recent touch). The post-merge git hook collapses duplicate \`<!-- baseline: -->\` lines automatically; if it didn't run, keep whichever SHA is the descendant of the other.`

const CODE_DRIFT_HEADER = `<!-- AUTO-GENERATED by kb-mcp — resolve via kb_drift in Claude. Do not delete entries manually. -->

# Code Drift Queue

Code changed without matching KB update. PM/tech lead reviews with Claude — approve (update KB) or reject (revert code) per KB document.

> **Before opening a PR:** resolve entries for files you touched.
> Wrote KB first? Already clean. Wrote code first? Run \`kb_drift\`, update KB, commit.
> Pulled entries from main? Not yours unless you touched those files.

${MERGE_PROTOCOL_NOTE}

`

const KB_DRIFT_HEADER = `<!-- AUTO-GENERATED by kb-mcp — resolve via kb_drift in Claude. Do not delete entries manually. -->

# KB Drift Queue

KB spec changed — developer reviews with Claude whether code still matches.

> **Before opening a PR:** confirm entries for specs you changed.
> Run \`kb_drift\` with \`kb_confirmed\` for each entry once code matches.

${MERGE_PROTOCOL_NOTE}

`

const DRIFT_LOG_HEADER = `<!-- AUTO-GENERATED audit trail — do not edit manually. -->

# Drift Log

Resolved drift events. Append-only.

`

// ── Acknowledgement marker — shared format across both queues ────────────────
//
// Acknowledged entries stay in the queue but render with an `**Acknowledged**`
// badge. Same syntax in code-drift.md and kb-drift.md so reviewers learn one
// shape; standards-drift uses the same line in conform.js.

const ACK_LINE_RE = /\*\*Acknowledged\*\*:\s*@(\S+)\s+at\s+`([^`]+)`\s+\(([^)]+)\)\s+—\s+"([^"]+)"/

function parseAcknowledgement(block) {
  const m = block.match(ACK_LINE_RE)
  if (!m) return null
  return { by: m[1], atCommit: m[2], atDate: m[3], reason: m[4] }
}

function formatAcknowledgement(ack) {
  const reason = (ack.reason || '').replace(/"/g, '\\"')
  return `- **Acknowledged**: @${ack.by} at \`${ack.atCommit}\` (${ack.atDate}) — "${reason}"`
}

function extractQueueBody(filePath) {
  if (!fs.existsSync(filePath)) return ''
  const content = fs.readFileSync(filePath, 'utf8')
  const headerEnd = content.indexOf('\n## ')
  if (headerEnd === -1) return ''
  return content.slice(headerEnd + 1).trimEnd()
}

// ── code-drift.md parse / serialize ──────────────────────────────────────────

function readCodeDriftEntries() {
  ensureHeader(CODE_DRIFT_PATH, CODE_DRIFT_HEADER)
  const content = fs.readFileSync(CODE_DRIFT_PATH, 'utf8')
  const headerEnd = content.indexOf('\n## ')
  const header = headerEnd === -1 ? content : content.slice(0, headerEnd)
  const entriesStr = headerEnd === -1 ? '' : content.slice(headerEnd + 1)
  const blocks = entriesStr.split(/\n(?=## )/).filter(b => b.trim())

  const entries = blocks.map(block => {
    const headingMatch = block.match(/^## (.+)/)
    const kbTarget = headingMatch ? headingMatch[1].trim() : null
    const hasShared = /\*\*Shared module:\*\*\s*true/.test(block)
    const acknowledgement = parseAcknowledgement(block)
    const fingerprintMatch = block.match(/<!--\s*fingerprint:\s*(sha256:[a-f0-9]+)\s*-->/)
    const codeFiles = []
    for (const line of block.split('\n')) {
      const m = line.match(/^\s+-\s+`([^`]+)`(?:\s+←\s+renamed from\s+`([^`]+)`)?\s+—\s+since\s+`([^`]+)`\s+\(([^)]+)\)(?:,\s+latest\s+`([^`]+)`\s+\(([^)]+)\))?(?:\s+—\s+by\s+@(\S+))?/)
      if (m) {
        codeFiles.push({
          path: m[1],
          ...(m[2] && { renamedFrom: m[2] }),
          sinceCommit: m[3],
          sinceDate: m[4],
          ...(m[5] && { latestCommit: m[5], latestDate: m[6] }),
          ...(m[7] && { author: m[7] })
        })
      }
    }
    return {
      kbTarget, codeFiles, hasShared,
      ...(acknowledgement && { acknowledgement }),
      ...(fingerprintMatch && { fingerprint: fingerprintMatch[1] }),
    }
  }).filter(e => e.kbTarget)

  return { header, entries }
}

function writeCodeDriftEntries(header, entries) {
  const body = entries.map(entry => {
    const fileLines = entry.codeFiles.map(f => {
      const renameNote = f.renamedFrom ? ` ← renamed from \`${f.renamedFrom}\`` : ''
      const latestNote = f.latestCommit && f.latestCommit !== f.sinceCommit
        ? `, latest \`${f.latestCommit}\` (${f.latestDate})`
        : ''
      const authorNote = f.author ? ` — by @${f.author}` : ''
      return `  - \`${f.path}\`${renameNote} — since \`${f.sinceCommit}\` (${f.sinceDate})${latestNote}${authorNote}`
    })
    const sharedLine = entry.hasShared ? '\n- **Shared module:** true' : ''
    const ackLine = entry.acknowledgement ? `\n${formatAcknowledgement(entry.acknowledgement)}` : ''
    // Detect when kb_target doesn't exist on disk but sibling files in the same
    // folder do — likely means the project uses a consolidated file instead of
    // one-file-per-table. Emit a hint so the agent updates the right file.
    const targetAbs = path.join(KB_ROOT, entry.kbTarget)
    let consolidatedHint = ''
    if (!fs.existsSync(targetAbs)) {
      const dir = path.dirname(targetAbs)
      if (fs.existsSync(dir)) {
        const siblings = fs.readdirSync(dir).filter(f => f.endsWith('.md'))
        if (siblings.length > 0) {
          const siblingList = siblings.map(s => `\`${path.join(path.dirname(entry.kbTarget), s)}\``).join(', ')
          consolidatedHint = `\n- **⚠ Target file does not exist.** The \`${path.dirname(entry.kbTarget)}/\` folder already contains: ${siblingList}. Check whether the content belongs in one of these existing files before creating a new one.`
        }
      }
    }
    const fpLine = entry.fingerprint ? `\n<!-- fingerprint: ${entry.fingerprint} -->` : ''
    return `## ${entry.kbTarget}${fpLine}\n\n- **KB target:** \`${entry.kbTarget}\`\n- **Code files:**\n${fileLines.join('\n')}${sharedLine}${ackLine}${consolidatedHint}`
  }).join('\n\n')
  fs.writeFileSync(CODE_DRIFT_PATH, header + (body ? '\n' + body + '\n' : ''), 'utf8')
}

/**
 * Upsert a code file into the in-memory code-drift state.
 * Returns 'new' when a file is added (new entry or new file under existing entry),
 * 're_detected' when an existing file's Latest was bumped to a newer commit,
 * or null when no change was made.
 */
function upsertCodeDriftEntry(state, kbTarget, codeFile, sinceCommit, sinceDate, latestCommit, latestDate, isShared, renamedFrom, author, opts = {}) {
  const { source } = opts
  const existing = state.entries.find(e => e.kbTarget === kbTarget)
  const fileShape = {
    path: codeFile,
    sinceCommit,
    sinceDate,
    ...(latestCommit && { latestCommit, latestDate }),
    ...(renamedFrom && { renamedFrom }),
    ...(author && { author }),
    ...(source && { source })
  }

  if (existing) {
    const existingFile = existing.codeFiles.find(f => f.path === codeFile)
    if (existingFile) {
      // Re-edit under an existing entry — bump Latest to the newest commit we
      // saw in this run, keep Since pinned as the drift anchor.
      const latestToRecord = latestCommit || sinceCommit
      const latestDateToRecord = latestCommit ? latestDate : sinceDate
      const currentLatest = existingFile.latestCommit || existingFile.sinceCommit
      let changed = false
      if (latestToRecord !== currentLatest) {
        existingFile.latestCommit = latestToRecord
        existingFile.latestDate = latestDateToRecord
        if (author) existingFile.author = author
        changed = true
      }
      if (source && existingFile.source !== source) {
        existingFile.source = source
        if (source === 'working-tree') existing.source = 'working-tree'
        changed = true
      }
      if (isShared) existing.hasShared = true
      return changed ? 're_detected' : null
    }
    existing.codeFiles.push(fileShape)
    if (isShared) existing.hasShared = true
    if (source === 'working-tree') existing.source = 'working-tree'
    return 'new'
  }

  state.entries.push({
    kbTarget,
    codeFiles: [fileShape],
    hasShared: !!isShared,
    ...(source && { source })
  })
  return 'new'
}

// ── kb-drift.md parse / serialize ────────────────────────────────────────────

function readKbDriftEntries() {
  ensureHeader(KB_DRIFT_PATH, KB_DRIFT_HEADER)
  const content = fs.readFileSync(KB_DRIFT_PATH, 'utf8')
  const headerEnd = content.indexOf('\n## ')
  const header = headerEnd === -1 ? content : content.slice(0, headerEnd)
  const entriesStr = headerEnd === -1 ? '' : content.slice(headerEnd + 1)
  const blocks = entriesStr.split(/\n(?=## )/).filter(b => b.trim())

  const entries = blocks.map(block => {
    const headingMatch = block.match(/^## (.+)/)
    const kbFile = headingMatch ? headingMatch[1].trim() : null
    const renamedMatch = block.match(/\*\*Renamed from:\*\*\s*`([^`]+)`/)
    const sinceMatch = block.match(/\*\*Since:\*\*\s*`([^`]+)`\s*\(([^)]+)\)/)
    const latestMatch = block.match(/\*\*Latest:\*\*\s*`([^`]+)`\s*\(([^)]+)\)(?:\s+—\s+by\s+@(\S+))?/)
    const unmapped = /KB spec changed without mapped code paths/.test(block)
    const acknowledgement = parseAcknowledgement(block)
    // Fingerprint storage: HTML comment per entry, parallel to the top-of-file
    // `<!-- baseline: ... -->` convention. Missing on entries written before P3
    // shipped — handled via lazy migration in the recompute pass.
    const fingerprintMatch = block.match(/<!--\s*fingerprint:\s*(sha256:[a-f0-9]+)\s*-->/)

    const codeAreas = []
    let inCodeAreas = false
    let inRefs = false
    const references = []
    let refCount = null
    const lines = block.split('\n')
    for (const line of lines) {
      if (/^- \*\*Code areas to review:\*\*/.test(line)) { inCodeAreas = true; inRefs = false; continue }
      if (/^- \*\*References to update:\*\*/.test(line)) {
        inCodeAreas = false; inRefs = true
        const countMatch = line.match(/\*\*References to update:\*\*\s*(\d+)\s*file\(s\)\s*contain\s*`\[\[([^\]]+)\]\]`/)
        if (countMatch) refCount = { count: parseInt(countMatch[1], 10), anchor: countMatch[2] }
        else if (/none found/.test(line)) refCount = { count: 0, anchor: null }
        continue
      }
      if (/^- \*\*/.test(line)) { inCodeAreas = false; inRefs = false; continue }
      if (inCodeAreas) {
        const m = line.match(/^\s+-\s+`([^`]+)`/)
        if (m) codeAreas.push(m[1])
      }
      if (inRefs) {
        const m = line.match(/^\s+-\s+`([^`]+)`/)
        if (m) references.push(m[1])
      }
    }

    return {
      kbFile,
      ...(renamedMatch && { renamedFrom: renamedMatch[1] }),
      codeAreas,
      ...(refCount && { refCount }),
      references,
      ...(sinceMatch && { sinceCommit: sinceMatch[1], sinceDate: sinceMatch[2] }),
      ...(latestMatch && { latestCommit: latestMatch[1], latestDate: latestMatch[2] }),
      ...(latestMatch && latestMatch[3] && { author: latestMatch[3] }),
      ...(acknowledgement && { acknowledgement }),
      ...(fingerprintMatch && { fingerprint: fingerprintMatch[1] }),
      unmapped
    }
  }).filter(e => e.kbFile)

  return { header, entries }
}

function writeKbDriftEntries(header, entries) {
  const body = entries.map(entry => {
    const areaLines = entry.codeAreas.length > 0
      ? entry.codeAreas.map(p => `  - \`${p}\``).join('\n')
      : '  - _(no mapped code paths — review manually)_'
    const renamedLine = entry.renamedFrom ? `\n- **Renamed from:** \`${entry.renamedFrom}\`` : ''
    let refsLine = ''
    if (entry.refCount) {
      if (entry.refCount.count > 0 && entry.refCount.anchor) {
        refsLine = `\n- **References to update:** ${entry.refCount.count} file(s) contain \`[[${entry.refCount.anchor}]]\``
        if (entry.references.length > 0) {
          refsLine += '\n  - ' + entry.references.map(f => `\`${f}\``).join('\n  - ')
        }
      } else {
        refsLine = '\n- **References to update:** none found'
      }
    }
    const sinceLine = entry.sinceCommit ? `\n- **Since:** \`${entry.sinceCommit}\` (${entry.sinceDate})` : ''
    const latestAuthor = entry.author ? ` — by @${entry.author}` : ''
    const latestLine = entry.latestCommit && entry.latestCommit !== entry.sinceCommit
      ? `\n- **Latest:** \`${entry.latestCommit}\` (${entry.latestDate})${latestAuthor}`
      : ''
    const unmappedHint = entry.unmapped
      ? `\n- **⚠ KB spec changed without mapped code paths.** Verify that the implementation still matches this spec. To enable automatic code-area tracking, add a \`code_path_patterns\` entry in \`_rules.md\` for this file.`
      : ''
    const ackLine = entry.acknowledgement ? `\n${formatAcknowledgement(entry.acknowledgement)}` : ''
    const fpLine = entry.fingerprint ? `\n<!-- fingerprint: ${entry.fingerprint} -->` : ''
    return `## ${entry.kbFile}${fpLine}\n\n- **KB file:** \`${entry.kbFile}\`${renamedLine}${refsLine}\n- **Code areas to review:**\n${areaLines}${sinceLine}${latestLine}${ackLine}${unmappedHint}`
  }).join('\n\n')
  fs.writeFileSync(KB_DRIFT_PATH, header + (body ? '\n' + body + '\n' : ''), 'utf8')
}

/**
 * Upsert a KB file into the in-memory kb-drift state.
 * Returns 'new' when a fresh entry is created, 're_detected' when an existing
 * entry's Latest was bumped to a newer commit, or null when no change.
 */
function upsertKbDriftEntry(state, kbFile, codeAreas, sinceCommit, sinceDate, latestCommit, latestDate, author, opts = {}) {
  const { source } = opts
  const existing = state.entries.find(e => e.kbFile === kbFile)
  if (existing) {
    const latestToRecord = latestCommit || sinceCommit
    const latestDateToRecord = latestCommit ? latestDate : sinceDate
    const currentLatest = existing.latestCommit || existing.sinceCommit
    let changed = false
    if (latestToRecord !== currentLatest) {
      existing.latestCommit = latestToRecord
      existing.latestDate = latestDateToRecord
      if (author) existing.author = author
      changed = true
    }
    if (source && existing.source !== source) {
      existing.source = source
      changed = true
    }
    return changed ? 're_detected' : null
  }

  state.entries.push({
    kbFile,
    codeAreas: [...codeAreas],
    references: [],
    sinceCommit,
    sinceDate,
    ...(latestCommit && { latestCommit, latestDate }),
    ...(author && { author }),
    unmapped: codeAreas.length === 0,
    ...(source && { source })
  })
  return 'new'
}

// ── Rename/move handling ─────────────────────────────────────────────────────

/**
 * Handle a code file rename. With fan-out, a single file may map to multiple
 * KB targets in both old and new positions. Compute the target sets, then:
 * - Targets in (old ∩ new): rename path inside the entry (replaceCodeFileInEntry)
 * - Targets in (old \ new): drop the old path from those entries
 * - Targets in (new \ old): add the new path to those entries with renamedFrom annotation
 *
 * `stalePattern` still fires when newTargets is empty AND oldTargets is non-empty —
 * same semantic as before, just over sets.
 *
 * Returns { outcomes: { new, re_detected }, stalePattern }. Caller increments
 * counters by the totals.
 */
function handleCodeRename(state, newPath, oldPath, sinceCommit, sinceDate, latestCommit, latestDate, isShared, patterns, author, opts = {}) {
  const { source } = opts
  const oldMatches = matchAllPatterns(oldPath, patterns)
  const newMatches = matchAllPatterns(newPath, patterns)
  const oldTargets = new Set(oldMatches.map(p => resolveKbTarget(p, oldPath)))
  const newTargets = new Set(newMatches.map(p => resolveKbTarget(p, newPath)))

  const outcomes = { new: 0, re_detected: 0 }

  // Intersection: rename inside same kb_target's entry.
  for (const target of oldTargets) {
    if (newTargets.has(target)) {
      replaceCodeFileInEntry(state, target, oldPath, newPath, sinceCommit, sinceDate, latestCommit, latestDate, author, { source })
      outcomes.new += 1
    }
  }
  // Old-only: drop the file from those entries.
  for (const target of oldTargets) {
    if (!newTargets.has(target)) removeCodeFileFromEntry(state, target, oldPath)
  }
  // New-only: add the file to those entries (with renamedFrom annotation).
  for (const target of newTargets) {
    if (!oldTargets.has(target)) {
      const outcome = upsertCodeDriftEntry(state, target, newPath, sinceCommit, sinceDate, latestCommit, latestDate, isShared, oldPath, author, { source })
      if (outcome === 'new') outcomes.new += 1
      else if (outcome === 're_detected') outcomes.re_detected += 1
    }
  }

  // Stale: had patterns before, none now. Surface the orphaned targets so the
  // caller can warn the user that _rules.md is out of date.
  let stalePattern = null
  if (newTargets.size === 0 && oldTargets.size > 0) {
    const firstOld = oldMatches[0]
    stalePattern = {
      intent: firstOld?.intent,
      kb_target: [...oldTargets][0],
      moved: { from: oldPath, to: newPath }
    }
  }

  return { outcomes, stalePattern }
}

/**
 * Handle a KB file rename. Finds files that reference the old path and
 * creates a kb-drift entry with rename metadata.
 * Returns { outcome: 'new'|'re_detected'|null }.
 */
function handleKbRename(state, newPath, oldPath, sinceCommit, sinceDate, latestCommit, latestDate, patterns, author, opts = {}) {
  const { source } = opts
  const oldRelative = oldPath.replace(/^knowledge\//, '')
  const newRelative = newPath.replace(/^knowledge\//, '')

  if (state.entries.some(e => e.kbFile === newRelative)) {
    return { outcome: null }
  }

  const graph = loadGraph(KB_ROOT)
  const oldWithoutExt = oldRelative.replace(/\.md$/, '')
  const dependents = getDependents(graph, oldWithoutExt)
  const refCount = dependents.length
  const refFiles = dependents.map(d => d.path)

  const codePaths = reverseMapKbTarget(newRelative, patterns)

  state.entries.push({
    kbFile: newRelative,
    renamedFrom: oldRelative,
    codeAreas: codePaths,
    refCount: { count: refCount, anchor: refCount > 0 ? oldWithoutExt : null },
    references: refFiles,
    sinceCommit,
    sinceDate,
    ...(latestCommit && { latestCommit, latestDate }),
    ...(author && { author }),
    unmapped: false,
    ...(source && { source })
  })
  return { outcome: 'new' }
}

/**
 * Replace a code file path in an existing code-drift entry (same KB target rename).
 */
function replaceCodeFileInEntry(state, kbTarget, oldPath, newPath, sinceCommit, sinceDate, latestCommit, latestDate, author, opts = {}) {
  const { source } = opts
  const existing = state.entries.find(e => e.kbTarget === kbTarget)
  const shape = {
    path: newPath,
    sinceCommit,
    sinceDate,
    ...(latestCommit && { latestCommit, latestDate }),
    ...(author && { author }),
    renamedFrom: oldPath,
    ...(source && { source })
  }
  if (!existing) {
    upsertCodeDriftEntry(state, kbTarget, newPath, sinceCommit, sinceDate, latestCommit, latestDate, false, oldPath, author, { source })
    return
  }
  const idx = existing.codeFiles.findIndex(f => f.path === oldPath)
  if (idx !== -1) existing.codeFiles[idx] = shape
  else existing.codeFiles.push(shape)
  if (source === 'working-tree') existing.source = 'working-tree'
}

/**
 * Remove a single code file from its code-drift entry. Removes the entry entirely if empty.
 */
function removeCodeFileFromEntry(state, kbTarget, codePath) {
  const existing = state.entries.find(e => e.kbTarget === kbTarget)
  if (!existing) return
  existing.codeFiles = existing.codeFiles.filter(f => f.path !== codePath)
  if (existing.codeFiles.length === 0) {
    state.entries = state.entries.filter(e => e.kbTarget !== kbTarget)
  }
}

// ── Shared queue helpers ──────────────────────────────────────────────────────

function ensureHeader(filePath, header) {
  if (!fs.existsSync(filePath)) {
    fs.mkdirSync(path.dirname(filePath), { recursive: true })
    fs.writeFileSync(filePath, header, 'utf8')
    return
  }
  const content = fs.readFileSync(filePath, 'utf8')
  if (content.startsWith('<!-- AUTO-GENERATED')) return

  // Sentinel is missing — rewrite from template, but preserve any pre-existing
  // baseline line so we don't lose the anchor.
  const preserved = parseBaseline(content)
  const newHeader = preserved ? setBaseline(header, preserved) : header
  fs.writeFileSync(filePath, newHeader + content, 'utf8')
}

/**
 * P3: walk every open entry in the given state. Two passes:
 *
 * - Lazy migration: entries with no `fingerprint` field (written before P3)
 *   get the current pattern's fingerprint stamped on them. No close.
 * - Recompute: entries with a `fingerprint` get the current pattern's
 *   fingerprint recomputed. Mismatches → drop from state, push an
 *   AUTO-CLOSED-PATTERN-CHANGED record into `autoCloseRecords`.
 *
 * `keyFn` extracts the queue key (kb_target for code-drift, kb_file for
 * kb-drift) used both to look up the matching pattern and to populate the
 * audit-log record. `queueKind` is "code-drift" or "kb-drift".
 */
function stampAndRecomputeFingerprints(state, patterns, queueKind, autoCloseRecords, keyFn) {
  const { computePatternFingerprint, findPatternForKbTarget } = require('../../lib/pattern-audit')
  const surviving = []
  for (const entry of state.entries) {
    const queueKey = keyFn(entry)
    const matchedPattern = findPatternForKbTarget(queueKey, patterns)
    const currentFp = matchedPattern ? computePatternFingerprint(matchedPattern) : null

    if (!entry.fingerprint) {
      // Lazy migration: stamp now, never auto-close on this run. If the pattern
      // no longer matches the queue key, leave the entry without a fingerprint —
      // the next run with a matching pattern will stamp it then.
      if (currentFp) entry.fingerprint = currentFp
      surviving.push(entry)
      continue
    }

    if (currentFp && currentFp === entry.fingerprint) {
      // Still matches. Keep entry as-is.
      surviving.push(entry)
      continue
    }

    // Either no matching pattern (pattern removed) or fingerprint mismatch
    // (pattern semantically changed). Drop the entry, audit-log the close.
    autoCloseRecords.push({
      event_type: 'auto-closed-pattern-changed',
      queue: queueKind,
      queue_key: queueKey,
      old_fingerprint: entry.fingerprint,
      new_fingerprint: currentFp || null,
      reason: currentFp
        ? 'pattern fingerprint changed in _rules.md'
        : 'pattern removed from _rules.md',
    })
  }
  state.entries = surviving
}

function appendToDriftLog(entries) {
  if (!fs.existsSync(DRIFT_LOG_DIR)) fs.mkdirSync(DRIFT_LOG_DIR, { recursive: true })
  const logPath = getDriftLogPath()
  ensureHeader(logPath, DRIFT_LOG_HEADER)
  const date = new Date().toISOString().split('T')[0]
  let block = ''
  for (const entry of entries) {
    if (entry.event_type === 'purged') {
      const shaDisplay = entry.baseline ? entry.baseline.slice(0, 7) : '(unchanged)'
      block += `\n## ${date} · PURGE\n`
      block += `\n- **New baseline:** \`${shaDisplay}\``
      block += `\n- **Code entries cleared:** ${entry.code_count || 0}`
      block += `\n- **KB entries cleared:** ${entry.kb_count || 0}`
      block += '\n- **Pre-purge code-drift.md body:**\n\n```markdown\n' + (entry.code_body || '(empty)') + '\n```\n'
      block += '\n- **Pre-purge kb-drift.md body:**\n\n```markdown\n' + (entry.kb_body || '(empty)') + '\n```\n'
      continue
    }
    if (entry.event_type === 're-bootstrap') {
      const oldShort = entry.old_sha ? entry.old_sha.slice(0, 7) : '?'
      const newShort = entry.new_sha ? entry.new_sha.slice(0, 7) : '(none)'
      block += `\n## ${date} · RE-BOOTSTRAP · ${entry.repo} (old ${oldShort}, new ${newShort})\n`
      block += `\n- **Queue:** ${entry.queue || 'both'}`
      block += `\n- **Old baseline:** \`${entry.old_sha || '(unknown)'}\``
      block += `\n- **New baseline:** \`${entry.new_sha || '(none — skipped)'}\``
      block += `\n- **Resolver:** ${entry.resolver_used || '(n/a)'}\n`
      continue
    }
    if (entry.event_type === 'dismissed') {
      block += `\n## ${date} · DISMISSED · ${entry.queue}\n`
      block += `\n- **Queue key:** \`${entry.queue_key}\``
      block += `\n- **Reason:** ${entry.reason}\n`
      continue
    }
    if (entry.event_type === 'acknowledged') {
      block += `\n## ${date} · ACKNOWLEDGED · ${entry.queue}\n`
      block += `\n- **Queue key:** \`${entry.queue_key}\``
      if (entry.by) block += `\n- **By:** @${entry.by}`
      if (entry.at_commit) block += `\n- **At:** \`${entry.at_commit}\``
      block += `\n- **Reason:** ${entry.reason}\n`
      continue
    }
    if (entry.event_type === 'auto-closed-pattern-changed') {
      // P3 — fires when an open queue entry's pattern fingerprint no longer
      // matches the current _rules.md. Mirrors AUTO-CLOSED-PROMOTION on the
      // standards side.
      block += `\n## ${date} · AUTO-CLOSED-PATTERN-CHANGED · ${entry.queue}\n`
      block += `\n- **Queue key:** \`${entry.queue_key}\``
      block += `\n- **Old fingerprint:** \`${entry.old_fingerprint}\``
      block += `\n- **New fingerprint:** \`${entry.new_fingerprint || '(pattern removed)'}\``
      block += `\n- **Reason:** ${entry.reason}\n`
      continue
    }
    // Fold `resolution` into the heading so summaries vs reverted vs
    // kb_confirmed events on the same date+direction get distinct headings.
    // Without this, both summaries (resolution: kb-updated) and reverted
    // (resolution: code-reverted) produce identical `## DATE · RESOLVED · code→kb`
    // headings on the same day, and the Activity tab consolidates them.
    // Parser at packages/shared/src/parsers/drift-log.ts:48 still classifies
    // any `RESOLVED ...` heading as `drift-resolved`, so this stays backwards-compat.
    const subDisc = entry.resolution ? ` · ${entry.resolution.toUpperCase()}` : ''
    block += `\n## ${date} · RESOLVED · ${entry.direction}${subDisc}\n`
    if (entry.kb_target) block += `\n- **KB target:** \`${entry.kb_target}\``
    if (entry.kb_file) block += `\n- **KB file:** \`${entry.kb_file}\``
    if (entry.code_file) block += `\n- **Code file:** \`${entry.code_file}\``
    if (entry.code_files) block += `\n- **Code files:** ${entry.code_files.map(f => `\`${f}\``).join(', ')}`
    block += `\n- **Resolution:** ${entry.resolution}`
    if (entry.renamed_from) block += `\n- **Renamed from:** \`${entry.renamed_from}\``
    if (entry.unmapped) block += `\n- **⚠ Unmapped:** no code_path_patterns entry — drift detection inactive for this KB file`
    if (entry.summary) block += `\n- **Summary:** ${entry.summary}`
    block += '\n'
  }
  if (block) fs.appendFileSync(logPath, block)
}

// ── Merge housekeeping: deduplicate baseline lines ───────────────────────────
//
// The queue files have `merge=union` in .gitattributes, which concatenates
// both sides on merge. Entry-level unions are intentional (different entries
// from different branches coalesce cleanly). But if both branches wrote
// baseline lines, the merged header ends up with multiple <!-- baseline: -->
// comments — and until deduped, parseBaseline returns only the last one while
// the older orphan lingers as noise. Called by the post-merge git hook.
async function dedupBaselines() {
  const git = simpleGit(process.cwd())
  const results = []
  const queues = [
    { filePath: CODE_DRIFT_PATH, read: readCodeDriftEntries, write: writeCodeDriftEntries },
    { filePath: KB_DRIFT_PATH, read: readKbDriftEntries, write: writeKbDriftEntries }
  ]
  for (const { filePath, read, write } of queues) {
    if (!fs.existsSync(filePath)) continue
    const content = fs.readFileSync(filePath, 'utf8')
    const shas = [...content.matchAll(BASELINE_RE)].map(m => m[1])
    if (shas.length < 2) continue

    let winner = shas[0]
    for (let i = 1; i < shas.length; i++) {
      const candidate = shas[i]
      if (candidate === winner) continue
      try {
        await git.raw(['merge-base', '--is-ancestor', winner, candidate])
        winner = candidate
      } catch {
        try {
          await git.raw(['merge-base', '--is-ancestor', candidate, winner])
        } catch {
          process.stderr.write(`[kb-drift] warning: diverged baseline SHAs in ${filePath} (${winner.slice(0, 7)} vs ${candidate.slice(0, 7)}); keeping ${candidate.slice(0, 7)}\n`)
          winner = candidate
        }
      }
    }

    const state = read()
    state.header = setBaseline(state.header, winner)
    write(state.header, state.entries)
    results.push({ file: filePath, kept: winner, dropped: shas.length - 1 })
    process.stderr.write(`[kb-drift] deduped ${shas.length} baseline lines in ${filePath}; kept ${winner.slice(0, 7)}\n`)
  }
  return { deduped: results }
}

module.exports = {
  // Paths + headers
  CODE_DRIFT_PATH,
  KB_DRIFT_PATH,
  DRIFT_LOG_DIR,
  CODE_DRIFT_HEADER,
  KB_DRIFT_HEADER,
  DRIFT_LOG_HEADER,
  MERGE_PROTOCOL_NOTE,
  getDriftLogPath,
  // Acks
  parseAcknowledgement,
  formatAcknowledgement,
  // Body extraction
  extractQueueBody,
  // Code-drift
  readCodeDriftEntries,
  writeCodeDriftEntries,
  upsertCodeDriftEntry,
  // KB-drift
  readKbDriftEntries,
  writeKbDriftEntries,
  upsertKbDriftEntry,
  // Renames + mutations
  handleCodeRename,
  handleKbRename,
  replaceCodeFileInEntry,
  removeCodeFileFromEntry,
  // Shared
  ensureHeader,
  stampAndRecomputeFingerprints,
  appendToDriftLog,
  // Merge housekeeping
  dedupBaselines
}
