const fs = require('fs')
const path = require('path')
const crypto = require('crypto')

const KB_ROOT = 'knowledge'
const STANDARDS_PROMOTIONS_PATH = path.join(KB_ROOT, 'sync/standards-promotions.md')

const STANDARDS_PROMOTIONS_HEADER = `<!-- AUTO-GENERATED by kb-mcp — do not edit manually. Closes automatically when the standard is updated; otherwise resolve via kb_conform's closed_promotion arg. -->

# Standards Promotions Ledger

Promoted (file, rule) pairs awaiting senior review. These are suppressed from
Phase 1 re-detection until either:

- The standard's rule definition changes (auto-close on fingerprint mismatch), or
- A senior reviewer calls \`kb_conform\` with \`closed_promotion: [...]\` (writes
  an exception to the rule and removes the entry).

> **On merge conflicts:** queue files use \`merge=union\` — different entries from different branches coalesce automatically.

`

// ── Fingerprint ──────────────────────────────────────────────────────────────

// Recursive key-sort so JSON.stringify produces deterministic output regardless
// of insertion order in the source YAML. Arrays preserve order (semantically
// meaningful for things like detect.pattern lists); objects don't.
function canonicalize(value) {
  if (Array.isArray(value)) return value.map(canonicalize)
  if (value && typeof value === 'object') {
    const sorted = {}
    for (const k of Object.keys(value).sort()) sorted[k] = canonicalize(value[k])
    return sorted
  }
  return value
}

/**
 * Stable hash of the rule's enforcement-relevant fields. Changes when a senior
 * reviewer meaningfully edits the rule: description, severity, the full detect
 * config, the rule's applies_to, or — for contracts — any party's
 * applies_to.paths. A fingerprint mismatch on a subsequent sweep means
 * "the standard has been updated" → auto-close.
 *
 * Deliberately excludes rule.title and rule.exceptions: title edits are cosmetic
 * and exception writebacks are how `closed_promotion` clears suppression
 * already.
 *
 * Note: changing the inputs to this function invalidates every existing
 * promotion entry (their stored fingerprint won't match the new computation),
 * which causes auto-close on the next sweep. That is a recovery path, not data
 * loss — re-promoting brings them back at the new fingerprint.
 *
 * @param {object} rule       - rule object from standardsIndex
 * @param {object} [standard] - parent standard (required if kind === 'contract')
 */
function computeRuleFingerprint(rule, standard) {
  const parts = {
    description: rule.description || '',
    severity: rule.severity || '',
    detect: canonicalize(rule.detect || null),
    applies_to: canonicalize(rule.applies_to || null)
  }
  if (standard && standard.kind === 'contract') {
    const partyPaths = []
    for (const [name, party] of Object.entries(standard.parties || {})) {
      const paths = (party.applies_to && party.applies_to.paths) || []
      partyPaths.push([name, [...paths].sort().join('|')])
    }
    partyPaths.sort()
    parts.party_paths = partyPaths
  }
  const canonical = JSON.stringify(parts)
  return 'sha256:' + crypto.createHash('sha256').update(canonical).digest('hex').slice(0, 16)
}

// ── Read / write ─────────────────────────────────────────────────────────────

function ensureFile() {
  if (!fs.existsSync(STANDARDS_PROMOTIONS_PATH)) {
    fs.mkdirSync(path.dirname(STANDARDS_PROMOTIONS_PATH), { recursive: true })
    fs.writeFileSync(STANDARDS_PROMOTIONS_PATH, STANDARDS_PROMOTIONS_HEADER, 'utf8')
  }
}

function readLedger() {
  ensureFile()
  const content = fs.readFileSync(STANDARDS_PROMOTIONS_PATH, 'utf8')
  const headerEnd = content.indexOf('\n## ')
  const hdr = headerEnd === -1 ? content : content.slice(0, headerEnd)
  const entriesStr = headerEnd === -1 ? '' : content.slice(headerEnd + 1)
  const blocks = entriesStr.split(/\n(?=## )/).filter(b => b.trim())

  const entries = blocks.map(block => {
    const headingMatch = block.match(/^## (.+)/)
    const queueKey = headingMatch ? headingMatch[1].trim() : null
    const stdMatch = block.match(/\*\*Standard:\*\*\s*`([^`]+)`(?:\s*\(([^)]+)\))?/)
    const ruleMatch = block.match(/\*\*Rule:\*\*\s*`([^`]+)`\s*—\s*(\w+)/)
    const fpMatch = block.match(/\*\*Rule fingerprint:\*\*\s*`([^`]+)`/)

    const files = []
    const lines = block.split('\n')
    let inFiles = false
    for (const line of lines) {
      if (/^- \*\*Files:\*\*/.test(line)) { inFiles = true; continue }
      if (/^- \*\*/.test(line)) { inFiles = false; continue }
      if (!inFiles) continue
      const m = line.match(/^\s+-\s+`([^`]+)`\s+—\s+promoted\s+`([^`]+)`(?:,\s+note:\s+"((?:[^"\\]|\\.)*)")?/)
      if (m) {
        files.push({
          path: m[1],
          promotedAt: m[2],
          ...(m[3] && { note: m[3].replace(/\\"/g, '"') })
        })
      }
    }
    if (!queueKey) return null
    const [standardId, ruleId] = queueKey.split('.')
    return {
      queueKey,
      standardId: stdMatch ? stdMatch[1] : standardId,
      standardKind: stdMatch ? (stdMatch[2] || null) : null,
      ruleId: ruleMatch ? ruleMatch[1] : ruleId,
      severity: ruleMatch ? ruleMatch[2] : null,
      ruleFingerprint: fpMatch ? fpMatch[1] : null,
      files
    }
  }).filter(Boolean)

  return { header: hdr, entries }
}

function writeLedger(state) {
  const body = state.entries.map(entry => {
    const fileLines = entry.files.length > 0
      ? entry.files.map(f => {
          const noteSuffix = f.note ? `, note: "${f.note.replace(/"/g, '\\"')}"` : ''
          return `  - \`${f.path}\` — promoted \`${f.promotedAt}\`${noteSuffix}`
        }).join('\n')
      : '  - _(empty)_'
    const kindNote = entry.standardKind ? ` (${entry.standardKind})` : ''
    const severity = entry.severity || 'warn'
    return `## ${entry.queueKey}\n\n- **Standard:** \`${entry.standardId}\`${kindNote}\n- **Rule:** \`${entry.ruleId}\` — ${severity}\n- **Rule fingerprint:** \`${entry.ruleFingerprint || ''}\`\n- **Files:**\n${fileLines}`
  }).join('\n\n')

  fs.writeFileSync(STANDARDS_PROMOTIONS_PATH, state.header + (body ? '\n' + body + '\n' : ''), 'utf8')
}

// ── Mutations ────────────────────────────────────────────────────────────────

/**
 * Idempotent upsert. Each item: { queueKey, standardId, standardKind, ruleId,
 * severity, ruleFingerprint, files: [{path, promotedAt, note?}] }. Existing
 * file rows for the same (queueKey, path) are replaced with the new
 * promotedAt/note (so re-promoting refreshes the timestamp). Fingerprint is
 * always overwritten with the latest computed value.
 */
function addPromotions(state, items) {
  for (const it of items) {
    let entry = state.entries.find(e => e.queueKey === it.queueKey)
    if (!entry) {
      entry = {
        queueKey: it.queueKey,
        standardId: it.standardId,
        standardKind: it.standardKind || null,
        ruleId: it.ruleId,
        severity: it.severity || 'warn',
        ruleFingerprint: it.ruleFingerprint || null,
        files: []
      }
      state.entries.push(entry)
    } else {
      entry.ruleFingerprint = it.ruleFingerprint || entry.ruleFingerprint
      if (it.severity) entry.severity = it.severity
      if (it.standardKind) entry.standardKind = it.standardKind
    }
    for (const f of it.files || []) {
      const existing = entry.files.find(x => x.path === f.path)
      if (existing) {
        existing.promotedAt = f.promotedAt
        if (f.note) existing.note = f.note
      } else {
        entry.files.push({ path: f.path, promotedAt: f.promotedAt, ...(f.note && { note: f.note }) })
      }
    }
  }
}

/**
 * Remove specific (queueKey, file_paths) pairs. If a queueKey ends up with no
 * remaining files, drop the entry entirely. Returns the list of entries that
 * were fully removed (caller logs them).
 */
function removePromotions(state, items) {
  const fullyRemoved = []
  for (const it of items) {
    const entry = state.entries.find(e => e.queueKey === it.queueKey)
    if (!entry) continue
    const fileSet = new Set(it.file_paths || [])
    if (fileSet.size === 0) {
      state.entries = state.entries.filter(e => e.queueKey !== it.queueKey)
      fullyRemoved.push(entry.queueKey)
      continue
    }
    entry.files = entry.files.filter(f => !fileSet.has(f.path))
    if (entry.files.length === 0) {
      state.entries = state.entries.filter(e => e.queueKey !== it.queueKey)
      fullyRemoved.push(entry.queueKey)
    }
  }
  return fullyRemoved
}

/**
 * Remove entries whose queueKey is in the provided set. Used by auto-close on
 * standard removal and on fingerprint mismatch.
 */
function removeEntriesByKey(state, queueKeys) {
  const set = new Set(queueKeys)
  const removed = state.entries.filter(e => set.has(e.queueKey))
  state.entries = state.entries.filter(e => !set.has(e.queueKey))
  return removed
}

// ── Suppression lookup ───────────────────────────────────────────────────────

/**
 * Map<queueKey, Set<filePath>> for O(1) suppression checks in detect().
 */
function getSuppressedPairs(state) {
  const map = new Map()
  for (const entry of state.entries) {
    map.set(entry.queueKey, new Set(entry.files.map(f => f.path)))
  }
  return map
}

// ── File rename / delete propagation ─────────────────────────────────────────

/**
 * Mirrors conform.js applyFileChangesToQueue. Renames update the file path;
 * deletes drop the file row. An entry that loses all files is dropped entirely.
 */
function applyFileChangesToLedger(state, renamed, deleted) {
  const renameMap = new Map(renamed.map(r => [r.from, r.to]))
  const deletedSet = new Set(deleted)
  const surviving = []
  for (const entry of state.entries) {
    const updated = []
    for (const f of entry.files) {
      if (deletedSet.has(f.path)) continue
      if (renameMap.has(f.path)) updated.push({ ...f, path: renameMap.get(f.path) })
      else updated.push(f)
    }
    entry.files = updated
    if (updated.length > 0) surviving.push(entry)
  }
  state.entries = surviving
}

module.exports = {
  STANDARDS_PROMOTIONS_PATH,
  STANDARDS_PROMOTIONS_HEADER,
  computeRuleFingerprint,
  readLedger,
  writeLedger,
  addPromotions,
  removePromotions,
  removeEntriesByKey,
  getSuppressedPairs,
  applyFileChangesToLedger
}
