// AUTO-GENERATED by packages/shared/scripts/build-tool-catalog.cjs
// Sources: knowledge/_mcp/tools/*.js (definitions) + tool-catalog-prose.json (prose)
// Edit those files, then run `npm run build:catalog` in packages/shared.

import type { ToolCatalogEntry } from "./tool-catalog.js";

export const GENERATED_TOOL_CATALOG: ToolCatalogEntry[] = [
  {
    "name": "kb_get",
    "category": "authoring",
    "shortDescription": "Load relevant KB files for a task. Respects token budget and app_scope filtering. When working_paths is provided, returns a separate rules_in_scope field listing standards rules that apply to those files (capped, descriptions trimmed) plus any open backlog entries as advisory items.",
    "whenToUse": "Load the right KB slices into the agent's context before it writes or reviews code — token-budgeted, scope-aware retrieval.",
    "examplePrompts": [
      "Pull the KB context relevant to the auth flow before I edit it.",
      "What standards apply to files under src/api/? (working_paths)",
      "Export everything in scope 'frontend' for an offline review."
    ],
    "keyParams": [
      {
        "name": "task_type",
        "type": "string",
        "required": false,
        "hint": "Type of task (e.g. generate, review, export)"
      },
      {
        "name": "keywords",
        "type": "union",
        "required": false,
        "hint": "Keywords to match KB files"
      },
      {
        "name": "app_scope",
        "type": "string",
        "required": false,
        "hint": "Filter by app scope (e.g. frontend, backend). When working_paths is also set, this overrides path-based app_scope inference."
      },
      {
        "name": "scope",
        "type": "string",
        "required": false,
        "hint": "Export scope: domain name, feature id, or \"all\""
      },
      {
        "name": "max_tokens",
        "type": "number",
        "required": false,
        "hint": "Override token budget (default: 8000, or token_budget from _rules.md)"
      },
      {
        "name": "task_context",
        "type": "enum(creating|fixing|reviewing)",
        "required": false,
        "hint": "Adjusts relevance scoring: creating boosts same-type files, fixing boosts code standards, reviewing includes drift targets"
      },
      {
        "name": "working_paths",
        "type": "string[]",
        "required": false,
        "hint": "File paths the agent is about to edit. Triggers rules_in_scope injection — relevant standards rules (capped at working_paths_cap, default 10) are returned in a separate field. Independent of task_context and keywords."
      }
    ],
    "surfaces": [
      "mcp"
    ]
  },
  {
    "name": "kb_write",
    "category": "authoring",
    "shortDescription": "Write a KB file and automatically reindex. Never write _index.yaml directly.",
    "whenToUse": "Persist a new or updated KB file and let the indexer regenerate metadata in one step.",
    "examplePrompts": [
      "Save this drafted standard to knowledge/standards/code/api-errors.md.",
      "Write the new feature note we just discussed into the KB."
    ],
    "keyParams": [
      {
        "name": "file_path",
        "type": "string",
        "required": true,
        "hint": "Path to the KB file (e.g. knowledge/specs/features/my-feature.md)"
      },
      {
        "name": "content",
        "type": "string",
        "required": true,
        "hint": "Full file content including YAML front-matter"
      }
    ],
    "surfaces": [
      "mcp"
    ]
  },
  {
    "name": "kb_drift",
    "category": "sync",
    "shortDescription": "Bidirectional drift detection. Phase 1: writes entries to sync/code-drift.md (keyed by KB target, tracks all code files + since-commit) and sync/kb-drift.md (keyed by KB file). Multiple commits accumulate automatically. The response includes `_diffs` with pre-fetched unified diffs, stats, and commit subjects for every open entry — read those directly before resolving. Phase 2: summaries=KB updated (closes code-drift.md), reverted=code file reverted (closes code-drift.md), kb_confirmed=kb→code reviewed (closes kb-drift.md), dismiss=close a structurally-broken ghost entry whose kb_target/kb_file will never exist (logged separately as DISMISSED in the audit trail — use this when an upstream code_path_patterns rule produced a garbage name rather than hand-editing the queue file). Phase 2 responses include `closed` (what was actually removed) and `not_found` (inputs that matched no open entry, with a `hint` when the input matches the *other* queue — i.e. you called the wrong phase). When anything lands in `not_found`, an `error` field is set; trust `closed`, not the top-level count, to know what was written.",
    "whenToUse": "Detect code↔KB misalignment after recent edits and queue any findings for human review.",
    "examplePrompts": [
      "Check my KB for drift since the last release.",
      "Did the controller refactor touch anything the KB describes?",
      "Run a readonly drift scan and just tell me what would be added."
    ],
    "keyParams": [
      {
        "name": "since",
        "type": "string",
        "required": false,
        "hint": "Commit SHA or \"last-sync\""
      },
      {
        "name": "summaries",
        "type": "object[]",
        "required": false,
        "hint": "Phase 2a: code correct — write KB notes and close code-drift.md entries"
      },
      {
        "name": "reverted",
        "type": "object[]",
        "required": false,
        "hint": "Phase 2b: code reverted — close code-drift.md entries without writing KB notes"
      },
      {
        "name": "kb_confirmed",
        "type": "object[]",
        "required": false,
        "hint": "Phase 2c: kb→code reviewed — close kb-drift.md entries"
      },
      {
        "name": "dismiss",
        "type": "object[]",
        "required": false,
        "hint": "Phase 2d: close a structurally-broken ghost entry (kb_target/kb_file that points at a file that will never exist, typically because an upstream code_path_patterns rule captured a versioned/timestamped basename). Use the exact entry heading as `queue_key` and a human-readable `reason`. Logged as DISMISSED separately from RESOLVED so dismissals remain visible as a signal that upstream rules need attention."
      },
      {
        "name": "acknowledge",
        "type": "object[]",
        "required": false,
        "hint": "Phase 2e: stamp an entry as author-vetted (\"real change, doesn't affect KB\") without removing it. Renders as an `**Acknowledged**: @author at SHA — \"reason\"` badge on the entry block. The entry stays in the queue; a later resolving verdict (summaries / reverted / kb_confirmed / dismiss) overrides."
      },
      {
        "name": "force_baseline",
        "type": "string",
        "required": false,
        "hint": "Admin escape hatch: reset both queue baselines to this SHA (or \"HEAD\"). Use when the queue has gone stale and needs a manual reset."
      },
      {
        "name": "purge",
        "type": "boolean",
        "required": false,
        "hint": "With force_baseline: also clear all queue entries. Default: false."
      },
      {
        "name": "include_diffs",
        "type": "boolean",
        "required": false,
        "hint": "Include `_diffs` with pre-fetched git diffs, stats, and commit subjects for every open entry. Default: true. Set false for quick status scans."
      },
      {
        "name": "readonly",
        "type": "boolean",
        "required": false,
        "hint": "Compute results in memory but skip every fs write (queue files, drift-log, baseline advance). Returned `_state` carries the would-have-written entries. Used by the live watcher in the extension and the soft-mode CI check."
      }
    ],
    "surfaces": [
      "mcp"
    ]
  },
  {
    "name": "kb_conform",
    "category": "governance",
    "shortDescription": "Three-phase non-functional conformance check. Phase 1 (no resolution args): MCP runs cheap pre-filters and returns requested_evaluations + a prompt for the agent to evaluate. Phase 1.5 (submit_judgments): agent submits per-rule judgments — must cover every requested triple in a single call (partial submissions return gaps[] and are not persisted across calls). Phase 2 (applied/exempted/promoted/dismissed): close queue entries. Promoted (file, rule) pairs are suppressed from re-detection until the standard is updated (auto-close on rule fingerprint change) or a senior reviewer calls closed_promotion. Aspirational mode (mode: aspirational, scope: <standard-file>): retroactive sweep into a separate backlog queue; pass path_filter to chunk a large sweep by subtree.",
    "whenToUse": "Sweep code against standards rules; the LLM judge classifies each finding and the verdict step closes it out.",
    "examplePrompts": [
      "Run conform on the auth standard against src/auth/.",
      "Resolve the pending conform queue — read each triple and judge it.",
      "Conform every aspirational rule against the codebase."
    ],
    "keyParams": [
      {
        "name": "since",
        "type": "string",
        "required": false,
        "hint": "Override baseline SHA (default: read from queue header)"
      },
      {
        "name": "mode",
        "type": "enum(current|aspirational)",
        "required": false,
        "hint": "Detection mode (default: current)"
      },
      {
        "name": "scope",
        "type": "string",
        "required": false,
        "hint": "Glob filter on Phase 1 file set (current mode); or standard file path in aspirational mode"
      },
      {
        "name": "path_filter",
        "type": "string|array",
        "required": false,
        "hint": "Aspirational mode only: chunk a large sweep by intersecting with one or more path globs (e.g. \"src/admin\" or [\"src/admin\", \"src/customer\"]). Bare directory inputs auto-expand to \"<dir>/**\". Errors if used in current mode, or if the intersection with the standard's applies_to.paths is empty."
      },
      {
        "name": "submit_judgments",
        "type": "object[]",
        "required": false,
        "hint": "Phase 1.5: per-(file, standard, rule) judgments. Must include every triple from the pending session in one call — partial submissions return gaps[] and are not persisted across calls."
      },
      {
        "name": "applied",
        "type": "object[]",
        "required": false,
        "hint": "Phase 2: code was fixed"
      },
      {
        "name": "exempted",
        "type": "object[]",
        "required": false,
        "hint": "Phase 2: justified exception, written into rule.exceptions[]"
      },
      {
        "name": "promoted",
        "type": "object[]",
        "required": false,
        "hint": "Phase 2: standard should change (logged; no automatic edit)"
      },
      {
        "name": "dismissed",
        "type": "object[]",
        "required": false,
        "hint": "Phase 2: false positive"
      },
      {
        "name": "closed_promotion",
        "type": "object[]",
        "required": false,
        "hint": "Senior reviewer close-out: removes a previously-promoted (file, rule) from the suppression ledger AND writes an exception into the rule (so the file is permanently fine). Use when reviewer decided NOT to update the standard. If the reviewer DID update the standard, no call is needed — the next sweep auto-closes via fingerprint change."
      },
      {
        "name": "acknowledge",
        "type": "object[]",
        "required": false,
        "hint": "Non-resolving annotation: stamps the entry with `**Acknowledged**: @author at SHA — \"reason\"` and leaves it in the queue. CI still treats acked entries as pending; a later resolving verdict overrides."
      },
      {
        "name": "force_baseline",
        "type": "string",
        "required": false,
        "hint": "Admin: reset baseline to a SHA or \"HEAD\""
      },
      {
        "name": "purge",
        "type": "boolean",
        "required": false,
        "hint": "Admin: with force_baseline, also clear all entries"
      },
      {
        "name": "include_diffs",
        "type": "boolean",
        "required": false,
        "hint": "Phase 1: pre-fetch diffs into result._diffs (default: true)"
      },
      {
        "name": "readonly",
        "type": "boolean",
        "required": false,
        "hint": "Compute results in memory but skip every fs write. Used by the live watcher in the extension and the soft-mode CI check."
      },
      {
        "name": "include_working_tree",
        "type": "boolean",
        "required": false,
        "hint": "Phase 1: also evaluate uncommitted/untracked files matching the standard's applies_to (default: false). In current mode this unions working-tree changes with the committed diff. In aspirational mode it unions git-tracked files with untracked-non-ignored files. Useful when you want a verdict on a file before committing."
      },
      {
        "name": "prompt_mode",
        "type": "enum(inline|reference)",
        "required": false,
        "hint": "Phase 1 only. \"inline\" (default): the agent-facing prompt is included in the response — can exceed the MCP response cap on sweeps with many evaluations. \"reference\": the prompt is written to knowledge/sync/.prompts/conform-phase1-<mode>-<hash>.md and a `prompt_path` field is returned instead; the agent reads the file directly. Use this when the inline response is being truncated."
      }
    ],
    "surfaces": [
      "mcp"
    ]
  },
  {
    "name": "kb_inventory",
    "category": "introspection",
    "shortDescription": "Read-only signal report for senior devs. Surfaces stale_rules (standards rules matching no source files), uncovered_files (source files matching no rule), and pending_promotions (open entries from the suppression ledger awaiting senior review). Never writes. Use to inform manual kb_extract / kb_write decisions, or to close promotions via kb_conform.",
    "whenToUse": "Get a read-only health snapshot of the KB — stale rules, uncovered code paths, pending promotions — before a senior review.",
    "examplePrompts": [
      "Give me a KB inventory for the senior review tomorrow.",
      "Which rules look stale and which files are uncovered?"
    ],
    "keyParams": [
      {
        "name": "depth",
        "type": "number",
        "required": false,
        "hint": "Directory depth for source-file walk (default 6)"
      },
      {
        "name": "scope",
        "type": "string",
        "required": false,
        "hint": "Optional glob to restrict the source-file walk (e.g. \"ms-fe-web/**\")"
      }
    ],
    "surfaces": [
      "mcp"
    ]
  },
  {
    "name": "kb_scaffold",
    "category": "authoring",
    "shortDescription": "Create a new KB file from a template. With description: returns a fill prompt for the agent. With content: writes agent-filled content. Without either: writes template with placeholders.",
    "whenToUse": "Spin up a new KB file from the right template and (optionally) get a fill prompt so the agent can populate it.",
    "examplePrompts": [
      "Scaffold a new feature note for billing webhooks.",
      "Create an empty standard for testing conventions and give me the fill prompt."
    ],
    "keyParams": [
      {
        "name": "type",
        "type": "string",
        "required": true,
        "hint": "Template type: feature|flow|schema|validation|integration|decision|standard|group|component"
      },
      {
        "name": "id",
        "type": "string",
        "required": false,
        "hint": "File identifier (kebab-case)"
      },
      {
        "name": "group",
        "type": "string",
        "required": false,
        "hint": "Group/subfolder for standards: code|contracts|knowledge|process"
      },
      {
        "name": "description",
        "type": "string",
        "required": false,
        "hint": "Description — tool returns a fill prompt for the agent to process"
      },
      {
        "name": "content",
        "type": "string",
        "required": false,
        "hint": "Agent-filled content to write (use after processing the fill prompt)"
      },
      {
        "name": "app_scope",
        "type": "string",
        "required": false,
        "hint": "App scope for this standard (e.g. frontend, backend). Default: all"
      }
    ],
    "surfaces": [
      "mcp"
    ]
  },
  {
    "name": "kb_impact",
    "category": "introspection",
    "shortDescription": "Analyze impact of a change across the KB dependency graph. Returns proposals — does not write.",
    "whenToUse": "Trace which KB files (and code paths) a proposed change would ripple into — a dry-run dependency analysis with no writes.",
    "examplePrompts": [
      "What's the blast radius if I rename the order model?",
      "Show me what KB files depend on the api-errors standard."
    ],
    "keyParams": [
      {
        "name": "change_description",
        "type": "string",
        "required": true,
        "hint": "Description of the change to analyze"
      }
    ],
    "surfaces": [
      "mcp"
    ]
  },
  {
    "name": "kb_ask",
    "category": "introspection",
    "shortDescription": "Ask a question about the KB. Supports query, brainstorm, challenge, sync, onboard, and generate intents.",
    "whenToUse": "Ask free-form questions of the KB — query, brainstorm, challenge, sync-check, onboard, or generate from it.",
    "examplePrompts": [
      "Ask the KB: how do we handle idempotency keys?",
      "Onboard me to the payments domain using the KB.",
      "Challenge the assumptions in the api-errors standard."
    ],
    "keyParams": [
      {
        "name": "question",
        "type": "string",
        "required": true,
        "hint": "Your question. Prefix with \"sync [feature] [note-id]\" to resolve a sync note."
      }
    ],
    "surfaces": [
      "mcp"
    ]
  },
  {
    "name": "kb_init",
    "category": "governance",
    "shortDescription": "Bootstrap a new KB structure in the current monorepo. Pass regenerate_agent_rules: true to (re)generate CLAUDE.md/.cursorrules/.windsurfrules/.github/copilot-instructions.md in the project root.",
    "whenToUse": "Bootstrap a fresh KB layout in a repo — templates, rules, agent-rules files (CLAUDE.md / .cursorrules / copilot-instructions).",
    "examplePrompts": [
      "Initialise a kb-mcp knowledge base in this repo.",
      "Re-generate the agent rules files from the current KB."
    ],
    "keyParams": [
      {
        "name": "interactive",
        "type": "boolean",
        "required": false,
        "hint": "Run interactive setup prompts"
      },
      {
        "name": "config",
        "type": "object",
        "required": false,
        "hint": "Config object (skips interactive prompts)"
      },
      {
        "name": "regenerate_agent_rules",
        "type": "boolean",
        "required": false,
        "hint": "Only regenerate CLAUDE.md/.cursorrules/.windsurfrules/.github/copilot-instructions.md; skip the full bootstrap."
      },
      {
        "name": "force",
        "type": "boolean",
        "required": false,
        "hint": "With regenerate_agent_rules: overwrite existing files. Default: false (preserves customizations)."
      }
    ],
    "surfaces": [
      "mcp"
    ]
  },
  {
    "name": "kb_migrate",
    "category": "governance",
    "shortDescription": "Migrate KB files after _rules.md changes. Returns one prompt per KB file for the calling agent to review; the agent calls kb_write per file if an update is needed. Does not write directly.",
    "whenToUse": "After _rules.md changes, migrate existing KB files to match the new conventions and emit review prompts for the agent.",
    "examplePrompts": [
      "Migrate the KB — I just updated _rules.md.",
      "What review prompts come out of the latest rules change?"
    ],
    "keyParams": [
      {
        "name": "since",
        "type": "string",
        "required": false,
        "hint": "Commit SHA to diff _rules.md from. Auto-detected by walking git log for the last commit that touched _rules.md and diffing its parent..HEAD."
      }
    ],
    "surfaces": [
      "mcp"
    ]
  },
  {
    "name": "kb_import",
    "category": "authoring",
    "shortDescription": "Import a document into the KB. Auto-classify mode (recommended): Phase 1 extracts and classifies in batches (multi-label). Phase 2 returns an import plan with proposed files and cross-references. Phase 3 (approve: true) writes files. Classic mode: Phase 1 returns chunks, Phase 2 writes agent-generated files.",
    "whenToUse": "Bring outside docs into the KB — classic extract+classify, or paginated auto-classify with an approval gate.",
    "examplePrompts": [
      "Import this Notion export into the KB (auto-classify mode).",
      "Extract standards from these legacy markdown docs and ask me before writing."
    ],
    "keyParams": [
      {
        "name": "source",
        "type": "string",
        "required": false,
        "hint": "Path to the source document (PDF, DOCX, MD, TXT, HTML)"
      },
      {
        "name": "dry_run",
        "type": "boolean",
        "required": false,
        "hint": "Preview without writing"
      },
      {
        "name": "auto_classify",
        "type": "boolean",
        "required": false,
        "hint": "Paginated classification mode — returns chunks in batches for agent to classify, then returns import plan for approval"
      },
      {
        "name": "approve",
        "type": "boolean",
        "required": false,
        "hint": "Execute a previously generated import plan (requires auto_classify)"
      },
      {
        "name": "classifications",
        "type": "object[]",
        "required": false,
        "hint": "Agent multi-label classification results from previous batch"
      },
      {
        "name": "cursor",
        "type": "number",
        "required": false,
        "hint": "Current position in chunk list (returned by previous auto_classify call)"
      },
      {
        "name": "files_to_write",
        "type": "object[]",
        "required": false,
        "hint": "Classic Phase 2: agent-generated files to write"
      }
    ],
    "surfaces": [
      "mcp"
    ]
  },
  {
    "name": "kb_export",
    "category": "introspection",
    "shortDescription": "Export KB content. Supports optional purpose to guide tone/structure, type filter (e.g. \"flow\"), and multi-scope (array of ids/domains). Phase 1: Gathers KB content and returns an export prompt for the agent (or writes json directly). Large KBs are paginated automatically. Phase 2: Call with rendered_content to write agent-rendered output to disk.",
    "whenToUse": "Render the KB out to PDF, DOCX, Confluence, Notion, or static HTML for sharing or archive.",
    "examplePrompts": [
      "Export the security standards as a PDF for the audit.",
      "Render the full KB to static HTML for the wiki."
    ],
    "keyParams": [
      {
        "name": "scope",
        "type": "union",
        "required": false,
        "hint": "Domain name, feature/flow id, or \"all\". Accepts an array for multi-scope export."
      },
      {
        "name": "format",
        "type": "string",
        "required": false,
        "hint": "Output format: pdf|docx|markdown|confluence|notion|html|json"
      },
      {
        "name": "type",
        "type": "string",
        "required": false,
        "hint": "Filter by KB type: feature, flow, schema, validation, integration, decision, component"
      },
      {
        "name": "purpose",
        "type": "string",
        "required": false,
        "hint": "Optional: describe the purpose and desired style of the export (e.g. \"client-facing API overview\", \"onboarding guide for new backend engineers\")"
      },
      {
        "name": "app_scope",
        "type": "string",
        "required": false,
        "hint": "Filter by app scope"
      },
      {
        "name": "page",
        "type": "number",
        "required": false,
        "hint": "Page number for paginated exports of large KBs (returned by previous call)"
      },
      {
        "name": "dry_run",
        "type": "boolean",
        "required": false,
        "hint": "Preview without writing"
      },
      {
        "name": "rendered_content",
        "type": "string",
        "required": false,
        "hint": "Phase 2: agent-rendered content to write to disk"
      }
    ],
    "surfaces": [
      "mcp"
    ]
  },
  {
    "name": "kb_analyze",
    "category": "authoring",
    "shortDescription": "Analyze project source files and generate a KB coverage inventory. Groups source files by their KB target (using code_path_patterns from _rules.md) and optionally writes draft KB files for uncovered groups. Useful for bootstrapping KB on legacy projects.",
    "whenToUse": "Scan source files and group them into KB targets using code_path_patterns — a starting point for fresh documentation runs.",
    "examplePrompts": [
      "Analyse src/payments/ and propose KB targets.",
      "Group these files by their KB target and draft KB files where missing."
    ],
    "keyParams": [
      {
        "name": "depth",
        "type": "number",
        "required": false,
        "hint": "Max directory depth to scan (default: 4)"
      },
      {
        "name": "write_drafts",
        "type": "boolean",
        "required": false,
        "hint": "Write draft KB files for uncovered groups"
      },
      {
        "name": "summary_only",
        "type": "boolean",
        "required": false,
        "hint": "Return only kb_target, file_count, existing_kb_file, and suggested_action per group — no sample_files. Use when the inventory is hitting the response cap and you only need group-level shape."
      }
    ],
    "surfaces": [
      "mcp"
    ]
  },
  {
    "name": "kb_extract",
    "category": "authoring",
    "shortDescription": "Sample existing code or KB files and return a prompt to derive a standards document from observed patterns. Phase 1 (no content): returns prompt + sampled file contents. Phase 2 (content provided): writes the filled standard to disk.",
    "whenToUse": "Sample code or existing KB content and get back a prompt for deriving a standards doc from the pattern.",
    "examplePrompts": [
      "Extract a standard from how we write controllers under src/api/.",
      "Sample the test files in tests/integration and propose a testing standard."
    ],
    "keyParams": [
      {
        "name": "source",
        "type": "enum(code|knowledge)",
        "required": true,
        "hint": "What to sample: \"code\" for source files, \"knowledge\" for KB docs"
      },
      {
        "name": "target_id",
        "type": "string",
        "required": true,
        "hint": "ID for the output standards file (kebab-case)"
      },
      {
        "name": "target_group",
        "type": "enum(code|contracts|knowledge|process)",
        "required": true,
        "hint": "Standards subfolder to write into"
      },
      {
        "name": "paths",
        "type": "union",
        "required": false,
        "hint": "Glob patterns to filter source files (source=code), or KB subfolder name (source=knowledge, e.g. \"features\")"
      },
      {
        "name": "app_scope",
        "type": "string",
        "required": false,
        "hint": "App scope for the generated standard (default: all)"
      },
      {
        "name": "content",
        "type": "string",
        "required": false,
        "hint": "(Phase 2) Filled content to write to disk"
      }
    ],
    "surfaces": [
      "mcp"
    ]
  },
  {
    "name": "kb_issue",
    "category": "governance",
    "shortDescription": "Issue ↔ KB bridge. command: \"triage\" (two-phase; writes to sync/inbound/), \"plan\" (two-phase; writes to sync/outbound/), \"consult\" (single-phase; no write).",
    "whenToUse": "Bridge issue trackers and the KB — triage an issue against existing rules, plan from KB context, or consult before filing.",
    "examplePrompts": [
      "Triage this GitHub issue against the KB.",
      "Plan tasks for this Linear ticket using the KB context.",
      "Should we even file this? Consult the KB first."
    ],
    "keyParams": [
      {
        "name": "command",
        "type": "enum(triage|plan|consult)",
        "required": true,
        "hint": "triage: analyze an existing issue against the KB. plan: generate work items from KB docs. consult: advise before filing an issue."
      },
      {
        "name": "title",
        "type": "string",
        "required": false,
        "hint": "Issue title (triage, consult)"
      },
      {
        "name": "body",
        "type": "string",
        "required": false,
        "hint": "Issue description/body (triage, consult)"
      },
      {
        "name": "issue_id",
        "type": "string",
        "required": false,
        "hint": "External issue ID, e.g. PROJ-123 (triage)"
      },
      {
        "name": "source",
        "type": "string",
        "required": false,
        "hint": "PM tool name: jira, github, linear (triage)"
      },
      {
        "name": "labels",
        "type": "string[]",
        "required": false,
        "hint": "Issue labels/tags (triage)"
      },
      {
        "name": "priority",
        "type": "string",
        "required": false,
        "hint": "Issue priority (triage)"
      },
      {
        "name": "scope",
        "type": "string",
        "required": false,
        "hint": "Scope filter — folder name or \"all\" (plan)"
      },
      {
        "name": "type",
        "type": "string",
        "required": false,
        "hint": "KB doc type filter: feature, flow, decision (plan)"
      },
      {
        "name": "keywords",
        "type": "union",
        "required": false,
        "hint": "Keyword filter (plan)"
      },
      {
        "name": "target",
        "type": "string",
        "required": false,
        "hint": "Target PM tool: jira, github, linear (plan)"
      },
      {
        "name": "project_key",
        "type": "string",
        "required": false,
        "hint": "PM tool project key, e.g. PROJ (plan)"
      },
      {
        "name": "app_scope",
        "type": "string",
        "required": false,
        "hint": "Filter KB search to specific app scope"
      },
      {
        "name": "content",
        "type": "string",
        "required": false,
        "hint": "Phase 2: filled triage report (triage) or task breakdown YAML (plan) to write"
      }
    ],
    "surfaces": [
      "mcp"
    ]
  },
  {
    "name": "kb_sub",
    "category": "sync",
    "shortDescription": "Submodule coordination. status: shows parent + submodule branches, pointer changes, owned/shared types. push: pushes submodules first (correct order), then parent. merge_plan: returns correct merge sequence for feature-to-main.",
    "whenToUse": "Coordinate git submodules safely — status, ordered push plan, and feature→main merge planning.",
    "examplePrompts": [
      "What's the safe push order for my submodules right now?",
      "Plan the merge from feature into main across the submodules."
    ],
    "keyParams": [
      {
        "name": "command",
        "type": "enum(status|push|merge_plan)",
        "required": true,
        "hint": "Command to run"
      },
      {
        "name": "dry_run",
        "type": "boolean",
        "required": false,
        "hint": "For push: show plan without executing"
      },
      {
        "name": "target_branch",
        "type": "string",
        "required": false,
        "hint": "For merge_plan: target branch name"
      }
    ],
    "surfaces": [
      "mcp"
    ]
  },
  {
    "name": "kb_autotag",
    "category": "authoring",
    "shortDescription": "Auto-extract and manage tags for KB files. Tags are system-owned and overwritten on each run. Modes: \"fast\" (regex extraction, auto-applied), \"review\" (returns scored candidates for LLM validation), \"apply\" (writes LLM-reviewed tags to frontmatter).",
    "whenToUse": "Manage tags across KB files — fast regex auto-apply, scored review candidates, or LLM-validated apply.",
    "examplePrompts": [
      "Auto-tag the KB — fast pass, just apply the obvious ones.",
      "Give me a review queue of tag candidates I should look at."
    ],
    "keyParams": [
      {
        "name": "file_path",
        "type": "string",
        "required": false,
        "hint": "Path to a single KB file (e.g. knowledge/specs/features/auth.md), or \"all\" to tag the entire KB. Default: all. Used by fast and review modes."
      },
      {
        "name": "mode",
        "type": "enum(fast|review|apply)",
        "required": false,
        "hint": "fast: regex-extract and overwrite tags (default). review: return scored candidates grouped by confidence for LLM validation. apply: write LLM-reviewed tags from the tags parameter."
      },
      {
        "name": "tags",
        "type": "object",
        "required": false,
        "hint": "For mode=apply only. Map of file_path to tag array, e.g. { \"specs/features/auth.md\": [\"auth\", \"session\", \"jwt\"] }."
      }
    ],
    "surfaces": [
      "mcp"
    ]
  },
  {
    "name": "kb_autorelate",
    "category": "authoring",
    "shortDescription": "Discover semantic relations between KB files using keyword overlap and propose depends_on links. Use dry_run: true to preview before writing.",
    "whenToUse": "Discover related KB files via keyword overlap and propose depends_on links (dry-run by default).",
    "examplePrompts": [
      "Suggest depends_on links across the KB — don't write yet.",
      "Find KB files semantically related to the order-state standard."
    ],
    "keyParams": [
      {
        "name": "file_path",
        "type": "string",
        "required": false,
        "hint": "Analyze relations for a single file, or omit for all files."
      },
      {
        "name": "dry_run",
        "type": "boolean",
        "required": false,
        "hint": "Preview proposed relations without writing."
      },
      {
        "name": "threshold",
        "type": "number",
        "required": false,
        "hint": "Minimum overlap score to propose a relation (0–1). Default: 0.25"
      }
    ],
    "surfaces": [
      "mcp"
    ]
  },
  {
    "name": "kb_schema",
    "category": "introspection",
    "shortDescription": "Query database schema files (DBML format) with table-level extraction. Returns only relevant table/enum definitions.",
    "whenToUse": "Query DBML schema files in the KB — list or extract tables and enums by keyword or exact name.",
    "examplePrompts": [
      "Show me the orders table from the DBML.",
      "List every table that mentions 'invoice'."
    ],
    "keyParams": [
      {
        "name": "command",
        "type": "enum(query|list)",
        "required": true,
        "hint": "query: extract table definitions. list: list all tables and enums."
      },
      {
        "name": "file",
        "type": "string",
        "required": false,
        "hint": "Schema file path or bare name (e.g. \"postgres\" or \"data/schema/postgres.md\")"
      },
      {
        "name": "entities",
        "type": "string[]",
        "required": false,
        "hint": "Table names to extract (exact match)"
      },
      {
        "name": "keywords",
        "type": "union",
        "required": false,
        "hint": "Keywords for relevance-scored table extraction"
      }
    ],
    "surfaces": [
      "mcp"
    ]
  },
  {
    "name": "kb_upgrade",
    "category": "governance",
    "shortDescription": "Upgrade project KB templates and config after MCP server update. Auto-updates unmodified templates, returns merge prompts for customized ones, patches _rules.md with new keys.",
    "whenToUse": "After upgrading the kb-mcp package, patch templates and _rules.md so this repo picks up the new keys safely.",
    "examplePrompts": [
      "Upgrade my KB to the latest kb-mcp conventions.",
      "Patch _rules.md with whatever new keys this version added."
    ],
    "keyParams": [
      {
        "name": "dry_run",
        "type": "boolean",
        "required": false,
        "hint": "Preview changes without writing"
      },
      {
        "name": "force",
        "type": "boolean",
        "required": false,
        "hint": "Overwrite all templates including customized ones"
      }
    ],
    "surfaces": [
      "mcp"
    ]
  },
  {
    "name": "kb_history",
    "category": "introspection",
    "shortDescription": "Get the change history of a KB file: git commits that touched it + any drift-log entries that reference it. Call this when a decision depends on why or when something changed — not for routine reads.",
    "whenToUse": "Pull the change history of a KB file — git commits and drift-log references, optionally with patch bodies.",
    "examplePrompts": [
      "Show me the history of the api-errors standard.",
      "What drift events have touched knowledge/specs/features/billing.md?"
    ],
    "keyParams": [
      {
        "name": "file",
        "type": "string",
        "required": true,
        "hint": "KB file path (e.g. knowledge/decisions/auth.md or decisions/auth.md)"
      },
      {
        "name": "limit",
        "type": "number",
        "required": false,
        "hint": "Max number of commits (default: 20, max 200)"
      },
      {
        "name": "since",
        "type": "string",
        "required": false,
        "hint": "ISO date filter, e.g. \"2026-01-01\""
      },
      {
        "name": "include_diff",
        "type": "boolean",
        "required": false,
        "hint": "Include patch bodies. Off by default to save tokens."
      }
    ],
    "surfaces": [
      "mcp"
    ]
  },
  {
    "name": "kb_status",
    "category": "sync",
    "shortDescription": "Read-only sync-state aggregate. Returns counts and entries for code-drift, kb-drift, standards-drift, conform-pending (current + aspirational), pending promotions, and lint issues, plus the current git HEAD short SHA. Same data the KB Sync VSCode extension renders. Never writes. Use at session start, before opening a PR, or whenever the user asks \"what is drifting?\".",
    "whenToUse": "Aggregate sync state in one readonly call — drifts, conform-pending, promotions, lint, HEAD SHA. This is what the dashboards read.",
    "examplePrompts": [
      "Give me the current KB sync status.",
      "Just the totals — how many drifts and lint errors are open?"
    ],
    "keyParams": [
      {
        "name": "skip_lint",
        "type": "boolean",
        "required": false,
        "hint": "Skip the lint subprocess (faster; default false)."
      }
    ],
    "surfaces": [
      "mcp"
    ]
  }
];
