const { test } = require('node:test')
const assert = require('node:assert/strict')
const fs = require('fs')
const path = require('path')
const os = require('os')
const { execSync } = require('child_process')

const ORIGINAL_CWD = process.cwd()
const WRITE = require('../tools/write')
const CONFORM = require('../tools/conform')

function sh(cwd, cmd) {
  return execSync(cmd, { cwd, stdio: ['ignore', 'pipe', 'pipe'] }).toString().trim()
}

function mkTempRepo() {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'kb-aspirational-test-'))
  sh(dir, 'git init -q -b main')
  sh(dir, 'git config user.email "test@test"')
  sh(dir, 'git config user.name "test"')
  sh(dir, 'git config commit.gpgsign false')
  return dir
}

function rmTempRepo(dir) {
  fs.rmSync(dir, { recursive: true, force: true })
}

function writeFile(dir, rel, content) {
  const full = path.join(dir, rel)
  fs.mkdirSync(path.dirname(full), { recursive: true })
  fs.writeFileSync(full, content)
}

function bootstrapKb(dir, codeFiles = {}) {
  writeFile(dir, 'knowledge/_rules.md', `---
version: "1.0"
depth_policy:
  default_max: 3
  overrides:
    specs: 4
    standards: 2
    sync: 1
secret_patterns: []
code_path_patterns: []
prompt_overrides:
  base_dir: "knowledge/_templates/prompts"
  override_dir: "knowledge/_prompt-overrides"
  valid_override_types: [replace, extend-before, extend-after, suppress, section-replace]
  protected: [drift-summary, ask-sync, conform-check, conform-resolve]
---
`)
  writeFile(dir, 'knowledge/sync/standards-drift.md', '<!-- AUTO-GENERATED by kb-mcp -->\n\n# Standards Drift Queue\n\n')
  writeFile(dir, 'knowledge/sync/standards-backlog.md', '<!-- AUTO-GENERATED by kb-mcp -->\n\n# Standards Backlog\n\n')
  for (const [rel, content] of Object.entries(codeFiles)) writeFile(dir, rel, content)
}

function withRepo(fn) {
  return async () => {
    const dir = mkTempRepo()
    process.chdir(dir)
    try {
      await fn(dir)
    } finally {
      process.chdir(ORIGINAL_CWD)
      rmTempRepo(dir)
    }
  }
}

const STANDARD_REGEX = `---
id: no-console-log
type: standard
kind: stack-local
app_scope: all
created: 2026-04-26
tags: [logging]
rules:
  - id: no-console-log
    title: No console.log in production code
    severity: error
    applies_to:
      paths: ["src/**"]
    detect:
      kind: regex
      pattern: "console\\\\.log\\\\("
    description: |
      Production code must not contain console.log calls. Use the structured logger.
    exceptions: []
---
`

const STANDARD_LLM = `---
id: complex-screens
type: standard
kind: stack-local
app_scope: all
created: 2026-04-26
tags: [screens]
rules:
  - id: decompose-large-screens
    title: Decompose screens with many branches
    severity: warn
    applies_to:
      paths: ["src/**"]
      min_lines: 100
    detect:
      kind: llm
      hint: "screen has many conditional render branches"
    description: |
      Screens that grow large should be decomposed.
    exceptions: []
---
`

const STANDARD_INVALID = `---
id: bad-standard
type: standard
kind: stack-local
app_scope: all
created: 2026-04-26
rules: []
---
`

// ── Sweep finds violations via regex rule (deterministic) ──────────────────

test('writing a regex-based standard triggers an aspirational sweep that auto-flags violators', withRepo(async (dir) => {
  bootstrapKb(dir, {
    'src/clean.js': 'export default 1\n',
    'src/dirty.js': 'console.log("hello")\n',
    'src/very-dirty.js': 'function f() { console.log("a") }\nconsole.log("b")\n'
  })
  sh(dir, 'git add -A && git commit -q -m "init"')

  const res = await WRITE.runTool({
    file_path: 'knowledge/standards/code/no-console-log.md',
    content: STANDARD_REGEX
  })

  assert.equal(res.written, true)
  assert.ok(res.aspirational_sweep, 'aspirational_sweep field should be present')
  assert.equal(res.aspirational_sweep.error, undefined, JSON.stringify(res.aspirational_sweep))

  const backlogContent = fs.readFileSync('knowledge/sync/standards-backlog.md', 'utf8')
  assert.match(backlogContent, /## no-console-log\.no-console-log/)
  assert.match(backlogContent, /src\/dirty\.js/)
  assert.match(backlogContent, /src\/very-dirty\.js/)
  assert.doesNotMatch(backlogContent, /src\/clean\.js/, 'clean files should not be flagged')

  // Current-diff queue should be UNCHANGED
  const driftContent = fs.readFileSync('knowledge/sync/standards-drift.md', 'utf8')
  assert.doesNotMatch(driftContent, /## no-console-log/)
}))

// ── Sweep with LLM rule returns requested_evaluations, no auto-queue ───────

test('LLM-only standard sweep returns requested_evaluations without auto-queueing', withRepo(async (dir) => {
  // make a file long enough to pass min_lines: 100
  const longFile = Array(120).fill('// line').join('\n') + '\n'
  bootstrapKb(dir, {
    'src/big-screen.js': longFile,
    'src/short.js': 'export default 1\n'
  })
  sh(dir, 'git add -A && git commit -q -m "init"')

  const res = await WRITE.runTool({
    file_path: 'knowledge/standards/code/complex-screens.md',
    content: STANDARD_LLM
  })

  assert.ok(res.aspirational_sweep)
  assert.ok(Array.isArray(res.aspirational_sweep.requested_evaluations))
  assert.equal(res.aspirational_sweep.requested_evaluations.length, 1)
  assert.equal(res.aspirational_sweep.requested_evaluations[0].file, 'src/big-screen.js')

  // No entries in backlog yet — agent must submit judgments first
  const backlogContent = fs.readFileSync('knowledge/sync/standards-backlog.md', 'utf8')
  assert.doesNotMatch(backlogContent, /## complex-screens/)
}))

// ── Phase 1.5 against aspirational mode populates backlog ─────────────────

test('submitting aspirational judgments populates the backlog (not the drift queue)', withRepo(async (dir) => {
  const longFile = Array(120).fill('// x').join('\n') + '\n'
  bootstrapKb(dir, {
    'src/big-screen.js': longFile
  })
  sh(dir, 'git add -A && git commit -q -m "init"')

  await WRITE.runTool({
    file_path: 'knowledge/standards/code/complex-screens.md',
    content: STANDARD_LLM
  })

  const res = await CONFORM.runTool({
    mode: 'aspirational',
    submit_judgments: [{
      file: 'src/big-screen.js',
      standard_id: 'complex-screens',
      rule_id: 'decompose-large-screens',
      status: 'fail',
      reason: 'too many conditional branches'
    }]
  })

  assert.equal(res.queue_advanced, true)
  assert.equal(res.entries_new, 1)

  const backlog = fs.readFileSync('knowledge/sync/standards-backlog.md', 'utf8')
  assert.match(backlog, /## complex-screens\.decompose-large-screens/)
  assert.match(backlog, /src\/big-screen\.js/)

  const drift = fs.readFileSync('knowledge/sync/standards-drift.md', 'utf8')
  assert.doesNotMatch(drift, /complex-screens/, 'aspirational entries must not leak into the drift queue')
}))

// ── Lint-failing standard skips the sweep ──────────────────────────────────

test('writing a malformed standard skips the aspirational sweep', withRepo(async (dir) => {
  bootstrapKb(dir, {
    'src/dirty.js': 'console.log("x")\n'
  })
  sh(dir, 'git add -A && git commit -q -m "init"')

  const res = await WRITE.runTool({
    file_path: 'knowledge/standards/code/bad-standard.md',
    content: STANDARD_INVALID
  })

  assert.equal(res.written, true)
  assert.ok(res.lint_errors > 0, 'malformed standard should produce lint errors')
  // write.js surfaces the skip as a structured object so the caller knows
  // *why* no requested_evaluations came back, rather than leaving the field
  // unset and ambiguous.
  assert.ok(res.aspirational_sweep, 'sweep result should be present (as a skip object)')
  assert.equal(res.aspirational_sweep.skipped, 'lint_errors', 'sweep should be marked skipped due to lint errors')
  assert.equal(res.aspirational_sweep.requested_evaluations, undefined, 'no evaluations should be produced when skipped')
}))

// ── Non-standard write does not trigger sweep ─────────────────────────────

test('writing a non-standard file does not trigger an aspirational sweep', withRepo(async (dir) => {
  bootstrapKb(dir)
  sh(dir, 'git add -A && git commit -q -m "init"')

  const res = await WRITE.runTool({
    file_path: 'knowledge/specs/features/foo.md',
    content: '---\nid: foo\ntype: feature\napp_scope: all\ncreated: 2026-04-26\ntags: [test]\n---\n\n# Foo\n\nDescription here.\n'
  })

  assert.equal(res.written, true)
  assert.equal(res.aspirational_sweep, undefined)
}))

// ── Tightening an existing standard re-runs the sweep ─────────────────────

test('updating a standard re-runs the sweep and surfaces newly violating files', withRepo(async (dir) => {
  bootstrapKb(dir, {
    'src/dirty.js': 'console.log("x")\n'
  })
  sh(dir, 'git add -A && git commit -q -m "init"')

  // First write — initial standard
  const res1 = await WRITE.runTool({
    file_path: 'knowledge/standards/code/no-console-log.md',
    content: STANDARD_REGEX
  })
  assert.ok(res1.aspirational_sweep)
  let backlog = fs.readFileSync('knowledge/sync/standards-backlog.md', 'utf8')
  assert.match(backlog, /src\/dirty\.js/)

  // Add another violating file then re-write the standard (e.g. to tighten it)
  writeFile(dir, 'src/also-dirty.js', 'console.log("y")\n')
  sh(dir, 'git add -A && git commit -q -m "add also-dirty"')

  const res2 = await WRITE.runTool({
    file_path: 'knowledge/standards/code/no-console-log.md',
    content: STANDARD_REGEX // re-write same content; reindex re-emits, sweep re-runs
  })
  assert.ok(res2.aspirational_sweep)
  backlog = fs.readFileSync('knowledge/sync/standards-backlog.md', 'utf8')
  assert.match(backlog, /src\/also-dirty\.js/)
  assert.match(backlog, /src\/dirty\.js/)
}))

// ── Current-diff queue is independent ─────────────────────────────────────

test('aspirational sweep and current-diff conform produce entries in different queues', withRepo(async (dir) => {
  bootstrapKb(dir, {
    'src/legacy.js': 'console.log("legacy")\n'
  })
  sh(dir, 'git add -A && git commit -q -m "init"')

  await WRITE.runTool({
    file_path: 'knowledge/standards/code/no-console-log.md',
    content: STANDARD_REGEX
  })

  // Aspirational sweep should have queued legacy.js into backlog
  let backlog = fs.readFileSync('knowledge/sync/standards-backlog.md', 'utf8')
  assert.match(backlog, /src\/legacy\.js/)

  // Now make a *new* commit that touches a new file with a violation
  writeFile(dir, 'src/new-feature.js', 'console.log("new")\n')
  sh(dir, 'git add -A && git commit -q -m "new feature"')

  const conformRes = await CONFORM.runTool({ since: 'HEAD~1', include_diffs: false })
  assert.ok(conformRes)
  // Current-diff queue picks up the new file
  const drift = fs.readFileSync('knowledge/sync/standards-drift.md', 'utf8')
  assert.match(drift, /src\/new-feature\.js/)

  // Backlog still has legacy.js, NOT the new file
  backlog = fs.readFileSync('knowledge/sync/standards-backlog.md', 'utf8')
  assert.match(backlog, /src\/legacy\.js/)
  assert.doesNotMatch(backlog, /src\/new-feature\.js/, 'current-diff entries must stay out of the backlog')
}))
