const { test } = require('node:test')
const assert = require('node:assert/strict')
const fs = require('fs')
const path = require('path')
const os = require('os')
const { execSync } = require('child_process')

const ORIGINAL_CWD = process.cwd()
const CONFORM = require('../tools/conform')

function sh(cwd, cmd) {
  return execSync(cmd, { cwd, stdio: ['ignore', 'pipe', 'pipe'] }).toString().trim()
}

function mkTempRepo() {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'kb-conform-test-'))
  sh(dir, 'git init -q -b main')
  sh(dir, 'git config user.email "test@test"')
  sh(dir, 'git config user.name "test"')
  sh(dir, 'git config commit.gpgsign false')
  return dir
}

function rmTempRepo(dir) {
  fs.rmSync(dir, { recursive: true, force: true })
}

function writeFile(dir, rel, content) {
  const full = path.join(dir, rel)
  fs.mkdirSync(path.dirname(full), { recursive: true })
  fs.writeFileSync(full, content)
}

// Set up a minimal KB with one standard. Mirrors what kb_init + kb_reindex
// would produce so conform's loadGraph picks up the standard's rules from
// _index.yaml exactly as in production.
function bootstrapKb(dir, standardYaml, codeFiles = {}) {
  // _rules.md
  writeFile(dir, 'knowledge/_rules.md', `---
version: "1.0"
depth_policy:
  default_max: 3
  overrides:
    standards: 2
    sync: 1
secret_patterns: []
code_path_patterns: []
prompt_overrides:
  base_dir: "knowledge/_templates/prompts"
  override_dir: "knowledge/_prompt-overrides"
  valid_override_types: [replace, extend-before, extend-after, suppress, section-replace]
  protected: [drift-summary, ask-sync, conform-check, conform-resolve]
---
`)
  // standards file
  writeFile(dir, 'knowledge/standards/code/test-rule.md', standardYaml)
  // sync queue files (empty)
  writeFile(dir, 'knowledge/sync/standards-drift.md', '<!-- AUTO-GENERATED by kb-mcp — resolve via kb_conform in Claude. Do not delete entries manually. -->\n\n# Standards Drift Queue\n\n')
  writeFile(dir, 'knowledge/sync/standards-backlog.md', '<!-- AUTO-GENERATED by kb-mcp — surfaced advisorily by kb_get when editing affected files. -->\n\n# Standards Backlog\n\n')
  // code fixtures
  for (const [rel, content] of Object.entries(codeFiles)) writeFile(dir, rel, content)

  // Build minimal _index.yaml carrying the standard's rules — mirrors what
  // kb_reindex would produce after Stage 1.11.
  const matter = require('gray-matter')
  const yaml = require('js-yaml')
  const stdData = matter(standardYaml).data
  const indexData = {
    version: '1.0',
    last_sync: new Date().toISOString().split('T')[0],
    groups: {},
    files: {
      'standards/code/test-rule.md': {
        id: stdData.id,
        type: 'standard',
        app_scope: stdData.app_scope || 'all',
        kind: stdData.kind || 'stack-local',
        topic: stdData.topic || null,
        rules: stdData.rules || [],
        ...(stdData.parties && { parties: stdData.parties }),
        tokens_est: 0,
        always_load: false,
        depends_on: [],
        affects_flows: [],
        tags: stdData.tags || []
      }
    }
  }
  writeFile(dir, 'knowledge/_index.yaml', '# AUTO-GENERATED by kb-mcp — do not edit manually. Run kb_reindex to rebuild.\n' + yaml.dump(indexData, { lineWidth: 120, noRefs: true }))
}

function withRepo(fn) {
  return async () => {
    const dir = mkTempRepo()
    process.chdir(dir)
    try {
      await fn(dir)
    } finally {
      process.chdir(ORIGINAL_CWD)
      rmTempRepo(dir)
    }
  }
}

const STANDARD_LLM_RULE = `---
id: test-rule
type: standard
kind: stack-local
app_scope: all
created: 2026-04-26
tags: [test]
rules:
  - id: must-export-default
    title: Files must export default
    severity: warn
    applies_to:
      paths: ["src/**"]
    detect:
      kind: llm
      hint: "file does not export default"
    description: |
      Each module must export a default value.
    exceptions: []
---
`

const STANDARD_REGEX_RULE = `---
id: test-rule
type: standard
kind: stack-local
app_scope: all
created: 2026-04-26
tags: [test]
rules:
  - id: no-console-log
    title: No console.log
    severity: error
    applies_to:
      paths: ["src/**"]
    detect:
      kind: regex
      pattern: "console\\\\.log\\\\("
    description: |
      Production code must not contain console.log.
    exceptions: []
---
`

// ── Phase 1: detect produces requested_evaluations for LLM rules ────────────

test('Phase 1 detect surfaces files needing LLM judgment', withRepo(async (dir) => {
  bootstrapKb(dir, STANDARD_LLM_RULE, {
    'src/foo.js': 'console.log("hi")\n',
    'src/bar.js': 'export default 42\n'
  })
  sh(dir, 'git add -A && git commit -q -m "init"')

  const res = await CONFORM.runTool({ since: 'HEAD~0', include_diffs: false })
  // First run on a fresh repo with HEAD~0 baseline → empty diff. Make a change.
  writeFile(dir, 'src/baz.js', 'export default null\n')
  sh(dir, 'git add -A && git commit -q -m "add baz"')

  const res2 = await CONFORM.runTool({ since: 'HEAD~1', include_diffs: false })
  assert.ok(Array.isArray(res2.requested_evaluations))
  assert.equal(res2.requested_evaluations.length, 1)
  assert.equal(res2.requested_evaluations[0].file, 'src/baz.js')
  assert.equal(res2.requested_evaluations[0].standard_id, 'test-rule')
  assert.deepEqual(res2.requested_evaluations[0].rule_ids, ['must-export-default'])
}))

// ── Payload: diffs off by default, no duplicated eval JSON in the prompt ────

test('Phase 1 omits _diffs by default and emits diffs_hint instead', withRepo(async (dir) => {
  bootstrapKb(dir, STANDARD_LLM_RULE, { 'src/foo.js': 'console.log("hi")\n' })
  sh(dir, 'git add -A && git commit -q -m "init"')
  writeFile(dir, 'src/baz.js', 'export default null\n')
  sh(dir, 'git add -A && git commit -q -m "add baz"')

  // No include_diffs passed → new default is false.
  const res = await CONFORM.runTool({ since: 'HEAD~1' })
  assert.ok(res.requested_evaluations.length > 0, 'has evaluations')
  assert.ok(!('_diffs' in res), '_diffs not prefetched by default')
  assert.ok(typeof res.diffs_hint === 'string' && /git diff/.test(res.diffs_hint), 'diffs_hint points to git diff')

  // Opting in restores the prefetch and drops the hint.
  const withDiffs = await CONFORM.runTool({ since: 'HEAD~1', include_diffs: true })
  assert.ok(Array.isArray(withDiffs._diffs), 'include_diffs:true restores _diffs')
  assert.ok(!('diffs_hint' in withDiffs), 'no hint when diffs are present')
}))

test('Phase 1 prompt no longer embeds the requested_evaluations JSON (kept as structured field)', withRepo(async (dir) => {
  bootstrapKb(dir, STANDARD_LLM_RULE, { 'src/foo.js': 'console.log("hi")\n' })
  sh(dir, 'git add -A && git commit -q -m "init"')
  writeFile(dir, 'src/baz.js', 'export default null\n')
  sh(dir, 'git add -A && git commit -q -m "add baz"')

  const res = await CONFORM.runTool({ since: 'HEAD~1' })
  // Structured field intact (what the agent and Phase 1.5 actually use).
  assert.equal(res.requested_evaluations[0].file, 'src/baz.js')
  // Prompt references the field but does not re-embed the JSON array of triples.
  assert.ok(/requested_evaluations` field/.test(res.prompt), 'prompt points at the field')
  assert.ok(!res.prompt.includes('"standard_id": "test-rule"'), 'prompt does not re-embed the eval JSON')
}))

// ── Pre-filter: regex deterministic fail queues without LLM round-trip ──────

test('regex detector autoflags violations without going through Phase 1.5', withRepo(async (dir) => {
  bootstrapKb(dir, STANDARD_REGEX_RULE, {
    'src/dirty.js': 'function f() { console.log("x") }\n'
  })
  sh(dir, 'git add -A && git commit -q -m "init"')
  writeFile(dir, 'src/clean.js', 'export default 1\n')
  writeFile(dir, 'src/also-dirty.js', 'console.log("y")\n')
  sh(dir, 'git add -A && git commit -q -m "add files"')

  const res = await CONFORM.runTool({ since: 'HEAD~1', include_diffs: false })
  // No LLM evaluations requested for the regex rule (deterministic).
  assert.equal((res.requested_evaluations || []).length, 0)

  // Queue should now have an entry for the failing file.
  const queueContent = fs.readFileSync('knowledge/sync/standards-drift.md', 'utf8')
  assert.match(queueContent, /## test-rule\.no-console-log/)
  assert.match(queueContent, /src\/also-dirty\.js/)
}))

// ── Phase 1.5: completeness verification ────────────────────────────────────

test('Phase 1.5 returns gaps when judgments are incomplete', withRepo(async (dir) => {
  bootstrapKb(dir, STANDARD_LLM_RULE, {})
  sh(dir, 'git add -A && git commit -q -m "init"')
  writeFile(dir, 'src/a.js', 'function a() {}\n')
  writeFile(dir, 'src/b.js', 'function b() {}\n')
  sh(dir, 'git add -A && git commit -q -m "add files"')

  const phase1 = await CONFORM.runTool({ since: 'HEAD~1', include_diffs: false })
  assert.equal(phase1.requested_evaluations.length, 2)

  // Submit only one judgment
  const partial = await CONFORM.runTool({
    submit_judgments: [
      { file: 'src/a.js', standard_id: 'test-rule', rule_id: 'must-export-default', status: 'fail', reason: 'no default' }
    ]
  })
  assert.equal(partial.queue_advanced, false)
  assert.equal(partial.gaps.length, 1)
  assert.equal(partial.gaps[0].file, 'src/b.js')

  // Now submit both
  const full = await CONFORM.runTool({
    submit_judgments: [
      { file: 'src/a.js', standard_id: 'test-rule', rule_id: 'must-export-default', status: 'fail', reason: 'no default' },
      { file: 'src/b.js', standard_id: 'test-rule', rule_id: 'must-export-default', status: 'pass', reason: 'fine' }
    ]
  })
  assert.equal(full.queue_advanced, true)
  assert.equal(full.entries_new, 1) // only the fail
}))

// ── Phase 2 applied: removes entry, logs RESOLVED ──────────────────────────

test('Phase 2 applied removes the entry and writes audit log', withRepo(async (dir) => {
  bootstrapKb(dir, STANDARD_REGEX_RULE, {
    'src/x.js': 'console.log("x")\n'
  })
  sh(dir, 'git add -A && git commit -q -m "init"')
  writeFile(dir, 'src/y.js', 'console.log("y")\n')
  sh(dir, 'git add -A && git commit -q -m "add y"')

  await CONFORM.runTool({ since: 'HEAD~1', include_diffs: false })
  let queueContent = fs.readFileSync('knowledge/sync/standards-drift.md', 'utf8')
  assert.match(queueContent, /## test-rule\.no-console-log/)

  const res = await CONFORM.runTool({ applied: [{ queue_key: 'test-rule.no-console-log' }] })
  assert.equal(res.resolved, 1)
  queueContent = fs.readFileSync('knowledge/sync/standards-drift.md', 'utf8')
  assert.doesNotMatch(queueContent, /## test-rule\.no-console-log/)

  // Audit log
  const month = new Date().toISOString().slice(0, 7)
  const logContent = fs.readFileSync(`knowledge/sync/drift-log/${month}.md`, 'utf8')
  assert.match(logContent, /CONFORMED · applied/)
  assert.match(logContent, /test-rule\.no-console-log/)
}))

// ── Phase 2 exempted: writes back to standard's exceptions[] ───────────────

test('Phase 2 exempted appends to rule.exceptions[] so re-runs skip the file', withRepo(async (dir) => {
  bootstrapKb(dir, STANDARD_REGEX_RULE, {})
  sh(dir, 'git add -A && git commit -q -m "init"')
  writeFile(dir, 'src/legacy.js', 'console.log("legacy")\n')
  sh(dir, 'git add -A && git commit -q -m "add legacy"')

  await CONFORM.runTool({ since: 'HEAD~1', include_diffs: false })
  const res = await CONFORM.runTool({
    exempted: [{
      queue_key: 'test-rule.no-console-log',
      file_paths: ['src/legacy.js'],
      reason: 'legacy module pending rewrite'
    }]
  })
  assert.equal(res.resolved, 1)
  assert.equal(res.exceptions_written.length, 1)
  assert.equal(res.exceptions_written[0].written, true)

  // Confirm the standard now carries the exception
  const matter = require('gray-matter')
  const std = matter(fs.readFileSync('knowledge/standards/code/test-rule.md', 'utf8'))
  const rule = std.data.rules.find(r => r.id === 'no-console-log')
  assert.ok(Array.isArray(rule.exceptions))
  assert.equal(rule.exceptions.length, 1)
  assert.deepEqual(rule.exceptions[0].paths, ['src/legacy.js'])

  // Re-run conform with another commit touching the legacy file. After
  // exempted, re-runs must NOT re-flag it. Rebuild _index.yaml from the
  // updated standard so conform sees the new exceptions.
  const yaml = require('js-yaml')
  const indexPath = 'knowledge/_index.yaml'
  const indexRaw = fs.readFileSync(indexPath, 'utf8').replace(/^#[^\n]*\n/, '')
  const index = yaml.load(indexRaw)
  index.files['standards/code/test-rule.md'].rules = std.data.rules
  fs.writeFileSync(indexPath, '# AUTO-GENERATED by kb-mcp — do not edit manually. Run kb_reindex to rebuild.\n' + yaml.dump(index, { lineWidth: 120, noRefs: true }))

  writeFile(dir, 'src/legacy.js', 'console.log("legacy"); console.log("more")\n')
  sh(dir, 'git add -A && git commit -q -m "edit legacy"')
  const rerun = await CONFORM.runTool({ since: 'HEAD~1', include_diffs: false })
  const queueAfter = fs.readFileSync('knowledge/sync/standards-drift.md', 'utf8')
  assert.doesNotMatch(queueAfter, /src\/legacy\.js/)
}))

// ── Phase 2 promoted: logs intent, leaves standard unchanged ────────────────

test('Phase 2 promoted logs intent without modifying the standard', withRepo(async (dir) => {
  bootstrapKb(dir, STANDARD_REGEX_RULE, {})
  sh(dir, 'git add -A && git commit -q -m "init"')
  writeFile(dir, 'src/x.js', 'console.log("x")\n')
  sh(dir, 'git add -A && git commit -q -m "add x"')

  await CONFORM.runTool({ since: 'HEAD~1', include_diffs: false })
  const stdBefore = fs.readFileSync('knowledge/standards/code/test-rule.md', 'utf8')

  const res = await CONFORM.runTool({
    promoted: [{
      queue_key: 'test-rule.no-console-log',
      originating_files: ['src/x.js'],
      note: 'console.log is desirable for debug builds; rule should narrow scope'
    }]
  })
  assert.equal(res.resolved, 1)

  const stdAfter = fs.readFileSync('knowledge/standards/code/test-rule.md', 'utf8')
  assert.equal(stdBefore, stdAfter, 'standard file must not be modified by promotion')

  const month = new Date().toISOString().slice(0, 7)
  const log = fs.readFileSync(`knowledge/sync/drift-log/${month}.md`, 'utf8')
  assert.match(log, /CONFORMED · promoted/)
}))

// ── Phase 2 dismissed: separate event_type so it stays visible ─────────────

test('Phase 2 dismissed logs as DISMISSED-CONFORM not RESOLVED', withRepo(async (dir) => {
  bootstrapKb(dir, STANDARD_REGEX_RULE, {})
  sh(dir, 'git add -A && git commit -q -m "init"')
  writeFile(dir, 'src/x.js', 'console.log("x")\n')
  sh(dir, 'git add -A && git commit -q -m "add x"')
  await CONFORM.runTool({ since: 'HEAD~1', include_diffs: false })

  const res = await CONFORM.runTool({
    dismissed: [{ queue_key: 'test-rule.no-console-log', reason: 'inside debug guard' }]
  })
  assert.equal(res.resolved, 1)

  const month = new Date().toISOString().slice(0, 7)
  const log = fs.readFileSync(`knowledge/sync/drift-log/${month}.md`, 'utf8')
  assert.match(log, /DISMISSED-CONFORM/)
}))

// ── Standard removal auto-dismisses entries ────────────────────────────────

test('deleting a standard auto-dismisses its open queue entries', withRepo(async (dir) => {
  bootstrapKb(dir, STANDARD_REGEX_RULE, {})
  sh(dir, 'git add -A && git commit -q -m "init"')
  writeFile(dir, 'src/x.js', 'console.log("x")\n')
  sh(dir, 'git add -A && git commit -q -m "add x"')
  await CONFORM.runTool({ since: 'HEAD~1', include_diffs: false })

  // Remove the standard from the index (simulating kb_reindex after delete)
  const yaml = require('js-yaml')
  const indexPath = 'knowledge/_index.yaml'
  const indexRaw = fs.readFileSync(indexPath, 'utf8').replace(/^#[^\n]*\n/, '')
  const index = yaml.load(indexRaw)
  delete index.files['standards/code/test-rule.md']
  fs.writeFileSync(indexPath, '# AUTO-GENERATED by kb-mcp — do not edit manually. Run kb_reindex to rebuild.\n' + yaml.dump(index, { lineWidth: 120, noRefs: true }))
  fs.unlinkSync('knowledge/standards/code/test-rule.md')
  // Also need a new commit so getChangedFiles has something to diff against.
  sh(dir, 'git add -A && git commit -q -m "delete standard"')

  const res = await CONFORM.runTool({ since: 'HEAD~1', include_diffs: false })
  assert.ok(res.auto_dismissed >= 1)

  const queueContent = fs.readFileSync('knowledge/sync/standards-drift.md', 'utf8')
  assert.doesNotMatch(queueContent, /## test-rule\.no-console-log/)

  const month = new Date().toISOString().slice(0, 7)
  const log = fs.readFileSync(`knowledge/sync/drift-log/${month}.md`, 'utf8')
  assert.match(log, /AUTO-DISMISSED · standard removed/)
}))

// ── Force baseline / purge ─────────────────────────────────────────────────

test('force_baseline + purge clears entries and resets the baseline', withRepo(async (dir) => {
  bootstrapKb(dir, STANDARD_REGEX_RULE, {})
  sh(dir, 'git add -A && git commit -q -m "init"')
  writeFile(dir, 'src/x.js', 'console.log("x")\n')
  sh(dir, 'git add -A && git commit -q -m "add x"')
  await CONFORM.runTool({ since: 'HEAD~1', include_diffs: false })

  const res = await CONFORM.runTool({ force_baseline: 'HEAD', purge: true })
  assert.equal(res.purged, true)
  assert.ok(res.baseline)
  const queueContent = fs.readFileSync('knowledge/sync/standards-drift.md', 'utf8')
  assert.doesNotMatch(queueContent, /## test-rule/)
  assert.match(queueContent, /<!-- baseline:/)
}))
