const { test } = require('node:test')
const assert = require('node:assert/strict')
const fs = require('fs')
const path = require('path')
const os = require('os')
const yaml = require('js-yaml')

const ORIGINAL_CWD = process.cwd()
const GET = require('../tools/get')

function mkTempProject() {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'kb-get-test-'))
}

function rmProject(dir) {
  fs.rmSync(dir, { recursive: true, force: true })
}

function writeFile(dir, rel, content) {
  const full = path.join(dir, rel)
  fs.mkdirSync(path.dirname(full), { recursive: true })
  fs.writeFileSync(full, content)
}

// Bootstrap a minimal KB with one or more standards. Builds _index.yaml so
// the kb_get implementation finds the rules without needing a real reindex.
function bootstrapKb(dir, standards = [], rulesYaml = '') {
  writeFile(dir, 'knowledge/_rules.md', `---
version: "1.0"
depth_policy:
  default_max: 3
  overrides:
    standards: 2
secret_patterns: []
code_path_patterns: []
${rulesYaml}
prompt_overrides:
  base_dir: "knowledge/_templates/prompts"
  override_dir: "knowledge/_prompt-overrides"
  valid_override_types: [replace, extend-before, extend-after, suppress, section-replace]
  protected: [drift-summary, ask-sync, conform-check, conform-resolve]
---
`)

  const indexFiles = {}
  for (const std of standards) {
    const filePath = `standards/${std.group || 'code'}/${std.id}.md`
    const stdPath = path.join(dir, 'knowledge', filePath)
    fs.mkdirSync(path.dirname(stdPath), { recursive: true })
    const fm = {
      id: std.id,
      type: 'standard',
      kind: std.kind || 'stack-local',
      app_scope: std.app_scope || 'all',
      created: '2026-04-26',
      tags: std.tags || [],
      rules: std.rules,
      ...(std.parties && { parties: std.parties })
    }
    fs.writeFileSync(stdPath, `---\n${yaml.dump(fm, { lineWidth: 120 })}---\n`, 'utf8')
    indexFiles[filePath] = {
      id: std.id,
      type: 'standard',
      app_scope: fm.app_scope,
      kind: fm.kind,
      topic: std.topic || null,
      rules: std.rules,
      ...(std.parties && { parties: std.parties }),
      tokens_est: 0,
      always_load: false,
      depends_on: [],
      affects_flows: [],
      tags: fm.tags
    }
  }

  const indexData = {
    version: '1.0',
    last_sync: '2026-04-26',
    groups: {},
    files: indexFiles
  }
  writeFile(dir, 'knowledge/_index.yaml', '# AUTO-GENERATED by kb-mcp — do not edit manually. Run kb_reindex to rebuild.\n' + yaml.dump(indexData, { lineWidth: 120 }))
}

function withProject(fn) {
  return async () => {
    const dir = mkTempProject()
    process.chdir(dir)
    try {
      await fn(dir)
    } finally {
      process.chdir(ORIGINAL_CWD)
      rmProject(dir)
    }
  }
}

// ── Basic injection ─────────────────────────────────────────────────────────

test('working_paths populates rules_in_scope; existing files field unchanged', withProject(async (dir) => {
  bootstrapKb(dir, [{
    id: 'screen-routing',
    rules: [{
      id: 'decompose-by-routes',
      title: 'Decompose complex screens',
      severity: 'warn',
      applies_to: { paths: ['src/screens/**'] },
      detect: { kind: 'llm', hint: 'screen uses conditional render trees' },
      fix_hint: 'introduce nested <Routes>',
      description: 'Screens over ~200 lines should be decomposed via routes.'
    }]
  }])

  const res = await GET.runTool({ keywords: ['anything'], working_paths: ['src/screens/orders/list.tsx'] })
  assert.ok(Array.isArray(res.files), 'files field still present')
  assert.ok(Array.isArray(res.rules_in_scope), 'rules_in_scope field present')
  assert.equal(res.rules_in_scope.length, 1)
  const r = res.rules_in_scope[0]
  assert.equal(r.standard_id, 'screen-routing')
  assert.equal(r.rule_id, 'decompose-by-routes')
  assert.equal(r.severity, 'warn')
  assert.equal(r.advisory, false)
  assert.equal(r.detect_hint, 'screen uses conditional render trees')
  assert.equal(r.fix_hint, 'introduce nested <Routes>')
}))

test('rules_in_scope is omitted when working_paths is not provided', withProject(async (dir) => {
  bootstrapKb(dir, [{
    id: 's1',
    rules: [{ id: 'r1', title: 't', severity: 'warn', description: 'd', applies_to: { paths: ['src/**'] } }]
  }])
  const res = await GET.runTool({ keywords: ['anything'] })
  assert.equal(res.rules_in_scope, undefined)
}))

// ── Description trim ────────────────────────────────────────────────────────

test('description is trimmed to first paragraph or 300 chars', withProject(async (dir) => {
  const longDesc = 'a'.repeat(500) + '\n\nsecond paragraph here'
  bootstrapKb(dir, [{
    id: 's1',
    rules: [{
      id: 'r1', title: 't', severity: 'warn',
      applies_to: { paths: ['src/**'] },
      description: longDesc,
      detect: { kind: 'llm', hint: 'h' }
    }]
  }])

  const res = await GET.runTool({ working_paths: ['src/foo.js'] })
  const desc = res.rules_in_scope[0].description
  assert.ok(desc.length <= 301, `description ${desc.length} > 301`)
  assert.ok(desc.endsWith('…'), 'truncated description should end with ellipsis')
}))

test('first-paragraph trim drops body when there are multiple paragraphs', withProject(async (dir) => {
  bootstrapKb(dir, [{
    id: 's1',
    rules: [{
      id: 'r1', title: 't', severity: 'warn',
      applies_to: { paths: ['src/**'] },
      description: 'short first para\n\nlonger second paragraph with details that should not surface in the trimmed view',
      detect: { kind: 'llm', hint: 'h' }
    }]
  }])
  const res = await GET.runTool({ working_paths: ['src/foo.js'] })
  const desc = res.rules_in_scope[0].description
  assert.ok(desc.startsWith('short first para'), 'should start with first paragraph')
  assert.ok(desc.endsWith('…'), 'should end with ellipsis indicating truncation')
  assert.ok(!desc.includes('longer second'), 'second paragraph must not leak through')
}))

// ── Cap from _rules.md ──────────────────────────────────────────────────────

test('working_paths_cap from _rules.md bounds rules_in_scope', withProject(async (dir) => {
  const rules = []
  for (let i = 0; i < 15; i++) {
    rules.push({
      id: `r${i}`, title: `t${i}`, severity: 'warn',
      applies_to: { paths: ['src/**'] },
      description: 'd',
      detect: { kind: 'llm', hint: 'h' }
    })
  }
  bootstrapKb(dir, [{ id: 's1', rules }], 'working_paths_cap: 3')
  const res = await GET.runTool({ working_paths: ['src/foo.js'] })
  assert.equal(res.rules_in_scope.length, 3)
}))

// ── App-scope inference via app_root_patterns ──────────────────────────────

test('explicit app_scope overrides inference', withProject(async (dir) => {
  bootstrapKb(dir, [
    {
      id: 'fe-rule', app_scope: 'fe',
      rules: [{ id: 'r', title: 't', severity: 'warn', applies_to: { paths: ['src/**'] }, description: 'd', detect: { kind: 'llm', hint: 'h' } }]
    },
    {
      id: 'be-rule', app_scope: 'be',
      rules: [{ id: 'r', title: 't', severity: 'warn', applies_to: { paths: ['src/**'] }, description: 'd', detect: { kind: 'llm', hint: 'h' } }]
    }
  ])
  // No inference, explicit app_scope: 'fe' → only fe-rule matches
  const res = await GET.runTool({ working_paths: ['src/foo.js'], app_scope: 'fe' })
  assert.equal(res.rules_in_scope.length, 1)
  assert.equal(res.rules_in_scope[0].standard_id, 'fe-rule')
}))

test('app_root_patterns drives inference when app_scope is unset', withProject(async (dir) => {
  bootstrapKb(dir, [
    {
      id: 'fe-rule', app_scope: 'fe',
      rules: [{ id: 'r', title: 't', severity: 'warn', applies_to: { paths: ['fe/**'] }, description: 'd', detect: { kind: 'llm', hint: 'h' } }]
    },
    {
      id: 'be-rule', app_scope: 'be',
      rules: [{ id: 'r', title: 't', severity: 'warn', applies_to: { paths: ['be/**'] }, description: 'd', detect: { kind: 'llm', hint: 'h' } }]
    }
  ], 'app_root_patterns:\n  "fe/**": "fe"\n  "be/**": "be"')
  const res = await GET.runTool({ working_paths: ['fe/screens/list.tsx'] })
  assert.equal(res.rules_in_scope.length, 1)
  assert.equal(res.rules_in_scope[0].standard_id, 'fe-rule')
}))

test('no app_root_patterns: only app_scope: all standards match', withProject(async (dir) => {
  bootstrapKb(dir, [
    {
      id: 'fe-rule', app_scope: 'fe',
      rules: [{ id: 'r', title: 't', severity: 'warn', applies_to: { paths: ['src/**'] }, description: 'd', detect: { kind: 'llm', hint: 'h' } }]
    },
    {
      id: 'all-rule', app_scope: 'all',
      rules: [{ id: 'r', title: 't', severity: 'warn', applies_to: { paths: ['src/**'] }, description: 'd', detect: { kind: 'llm', hint: 'h' } }]
    }
  ])
  const res = await GET.runTool({ working_paths: ['src/foo.js'] })
  // No inference — fe-rule is excluded; only all-rule matches
  assert.equal(res.rules_in_scope.length, 1)
  assert.equal(res.rules_in_scope[0].standard_id, 'all-rule')
}))

// ── Contracts surface via party paths ──────────────────────────────────────

test('contract rules surface via party applies_to.paths', withProject(async (dir) => {
  bootstrapKb(dir, [{
    id: 'i18n',
    kind: 'contract',
    app_scope: ['fe', 'be'],
    parties: {
      backend: { app_scope: ['be'], applies_to: { paths: ['be/handlers/**'] }, detect: { kind: 'ast-grep', hint: 'no literal strings' } },
      frontend: { app_scope: ['fe'], applies_to: { paths: ['fe/screens/**'] }, detect: { kind: 'llm', hint: 'must call t()' } }
    },
    rules: [{ id: 'keys-only', title: 't', severity: 'error', description: 'BE sends keys; FE renders via t()' }]
  }], 'app_root_patterns:\n  "fe/**": "fe"\n  "be/**": "be"')

  const res = await GET.runTool({ working_paths: ['fe/screens/orders.tsx'] })
  const contractRule = res.rules_in_scope.find(r => r.standard_id === 'i18n')
  assert.ok(contractRule, 'contract rule should appear in rules_in_scope')
  assert.equal(contractRule.severity, 'error')
}))

// ── Backlog as advisory ────────────────────────────────────────────────────

test('backlog entries surface as advisory: true when their files match working_paths', withProject(async (dir) => {
  bootstrapKb(dir, [{
    id: 's1',
    rules: [{
      id: 'r1', title: 't', severity: 'warn',
      applies_to: { paths: ['src/**'] },
      description: 'd',
      detect: { kind: 'llm', hint: 'h' }
    }]
  }])
  // Add a backlog entry pointing at a different file (so the active rule
  // doesn't auto-cover it) — but that file IS in working_paths
  writeFile(dir, 'knowledge/sync/standards-backlog.md', `<!-- AUTO-GENERATED by kb-mcp — surfaced advisorily by kb_get when editing affected files. -->

# Standards Backlog

## s1.r1

- **Standard:** \`s1\` (stack-local)
- **Rule:** \`r1\` — warn
- **Files:**
  - \`src/legacy.js\` — since \`abc1234\` (2026-04-26)
- **Reason:** queued by aspirational sweep
`)

  const res = await GET.runTool({ working_paths: ['src/legacy.js'] })
  // The active rule appears (matches via applies_to glob). Advisory should
  // NOT appear separately since the active entry already covers the rule.
  // But for an out-of-active-scope entry, advisory shows up.
  assert.equal(res.rules_in_scope.length, 1)
  // active wins because key is the same
  assert.equal(res.rules_in_scope[0].advisory, false)
}))

test('backlog entry surfaces as advisory when no active rule covers it', withProject(async (dir) => {
  // Standard exists but its applies_to.paths doesn't match the file being
  // edited — so the active loop yields zero rules. Backlog has an entry for
  // this exact file though, so it surfaces as advisory.
  bootstrapKb(dir, [{
    id: 's1',
    rules: [{
      id: 'r1', title: 't', severity: 'error',
      applies_to: { paths: ['other/**'] },
      description: 'desc',
      detect: { kind: 'llm', hint: 'h' }
    }]
  }])
  writeFile(dir, 'knowledge/sync/standards-backlog.md', `<!-- AUTO-GENERATED by kb-mcp -->

# Standards Backlog

## s1.r1

- **Standard:** \`s1\` (stack-local)
- **Rule:** \`r1\` — warn
- **Files:**
  - \`legacy/foo.js\` — since \`abc1234\` (2026-04-26)
- **Reason:** queued by aspirational sweep
`)

  const res = await GET.runTool({ working_paths: ['legacy/foo.js'] })
  assert.equal(res.rules_in_scope.length, 1)
  assert.equal(res.rules_in_scope[0].advisory, true)
  assert.equal(res.rules_in_scope[0].standard_id, 's1')
}))

// ── Composition with task_context ──────────────────────────────────────────

test('working_paths and task_context are independent', withProject(async (dir) => {
  bootstrapKb(dir, [{
    id: 's1',
    rules: [{ id: 'r1', title: 't', severity: 'warn', applies_to: { paths: ['src/**'] }, description: 'd', detect: { kind: 'llm', hint: 'h' } }]
  }])
  // task_context: 'creating' affects keyword scoring (no keywords here, so no effect)
  // working_paths populates rules_in_scope independently
  const res = await GET.runTool({ working_paths: ['src/foo.js'], task_context: 'creating' })
  assert.equal(res.rules_in_scope.length, 1)
}))

// ── Existing kb_get behavior preserved ─────────────────────────────────────

test('export mode (scope) ignores working_paths gracefully', withProject(async (dir) => {
  bootstrapKb(dir, [{
    id: 's1',
    rules: [{ id: 'r1', title: 't', severity: 'warn', applies_to: { paths: ['src/**'] }, description: 'd', detect: { kind: 'llm', hint: 'h' } }]
  }])
  // Export mode short-circuits before working_paths handling — that's existing
  // behavior we don't want to break.
  const res = await GET.runTool({ scope: 'all', working_paths: ['src/foo.js'] })
  assert.ok(Array.isArray(res.files))
  assert.equal(res.rules_in_scope, undefined)
}))
