const { test } = require('node:test')
const assert = require('node:assert/strict')
const fs = require('fs')
const path = require('path')
const os = require('os')
const yaml = require('js-yaml')

const ORIGINAL_CWD = process.cwd()
const INVENTORY = require('../tools/inventory')

function mkTempProject() {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'kb-inventory-test-'))
}

function rmProject(dir) {
  fs.rmSync(dir, { recursive: true, force: true })
}

function writeFile(dir, rel, content) {
  const full = path.join(dir, rel)
  fs.mkdirSync(path.dirname(full), { recursive: true })
  fs.writeFileSync(full, content)
}

function bootstrapKb(dir, { standards = [], codeFiles = {} } = {}) {
  writeFile(dir, 'knowledge/_rules.md', `---
version: "1.0"
depth_policy:
  default_max: 3
  overrides:
    standards: 2
secret_patterns: []
code_path_patterns: []
---
`)

  const indexFiles = {}
  for (const std of standards) {
    const filePath = `standards/${std.group || 'code'}/${std.id}.md`
    indexFiles[filePath] = {
      id: std.id,
      type: 'standard',
      app_scope: std.app_scope || 'all',
      kind: std.kind || 'stack-local',
      rules: std.rules,
      ...(std.parties && { parties: std.parties }),
      tokens_est: 0,
      always_load: false,
      depends_on: [],
      affects_flows: [],
      tags: []
    }
    // Also write a real file so kb_inventory could read it if it wanted
    writeFile(dir, `knowledge/${filePath}`, `---\nid: ${std.id}\ntype: standard\n---\n`)
  }
  writeFile(dir, 'knowledge/_index.yaml',
    '# AUTO-GENERATED by kb-mcp — do not edit manually. Run kb_reindex to rebuild.\n' +
    yaml.dump({ version: '1.0', last_sync: '2026-04-26', groups: {}, files: indexFiles }, { lineWidth: 120 }))

  for (const [rel, content] of Object.entries(codeFiles)) writeFile(dir, rel, content)
}

function withProject(fn) {
  return async () => {
    const dir = mkTempProject()
    process.chdir(dir)
    try {
      await fn(dir)
    } finally {
      process.chdir(ORIGINAL_CWD)
      rmProject(dir)
    }
  }
}

// ── Stale rules ─────────────────────────────────────────────────────────────

test('stale_rules: rule whose applies_to.paths matches nothing is flagged', withProject(async (dir) => {
  bootstrapKb(dir, {
    standards: [{
      id: 's1',
      rules: [{
        id: 'r1', title: 't', severity: 'warn', description: 'd',
        applies_to: { paths: ['nonexistent/**/*.tsx'] }
      }]
    }],
    codeFiles: { 'src/foo.js': 'export default 1\n' }
  })

  const res = await INVENTORY.runTool({})
  assert.equal(res.stale_rules.length, 1)
  assert.equal(res.stale_rules[0].standard_id, 's1')
  assert.equal(res.stale_rules[0].rule_id, 'r1')
}))

test('stale_rules: rule with at least one matching file is NOT stale', withProject(async (dir) => {
  bootstrapKb(dir, {
    standards: [{
      id: 's1',
      rules: [{
        id: 'r1', title: 't', severity: 'warn', description: 'd',
        applies_to: { paths: ['src/**'] }
      }]
    }],
    codeFiles: { 'src/foo.js': 'x\n' }
  })
  const res = await INVENTORY.runTool({})
  assert.equal(res.stale_rules.length, 0)
}))

test('stale_rules: contracts are stale only when ALL party paths match nothing', withProject(async (dir) => {
  bootstrapKb(dir, {
    standards: [{
      id: 'i18n',
      kind: 'contract',
      app_scope: ['fe', 'be'],
      parties: {
        backend: { app_scope: ['be'], applies_to: { paths: ['be/**'] }, detect: { kind: 'llm' } },
        frontend: { app_scope: ['fe'], applies_to: { paths: ['fe/**'] }, detect: { kind: 'llm' } }
      },
      rules: [{ id: 'keys-only', title: 't', severity: 'error', description: 'd' }]
    }],
    codeFiles: {
      // Only backend has matching files — contract is NOT stale
      'be/handler.go': 'package x\n'
    }
  })
  const res = await INVENTORY.runTool({})
  assert.equal(res.stale_rules.length, 0)

  // Now bootstrap with NO matching files for either party
  rmProject(dir)
  fs.mkdirSync(dir, { recursive: true })
  process.chdir(dir)
  bootstrapKb(dir, {
    standards: [{
      id: 'i18n',
      kind: 'contract',
      app_scope: ['fe', 'be'],
      parties: {
        backend: { app_scope: ['be'], applies_to: { paths: ['be/**'] }, detect: { kind: 'llm' } },
        frontend: { app_scope: ['fe'], applies_to: { paths: ['fe/**'] }, detect: { kind: 'llm' } }
      },
      rules: [{ id: 'keys-only', title: 't', severity: 'error', description: 'd' }]
    }],
    codeFiles: { 'unrelated/file.js': 'x\n' }
  })
  const res2 = await INVENTORY.runTool({})
  assert.equal(res2.stale_rules.length, 1)
  assert.equal(res2.stale_rules[0].kind, 'contract')
}))

// ── Uncovered files ─────────────────────────────────────────────────────────

test('uncovered_files: source files matching no rule are listed', withProject(async (dir) => {
  bootstrapKb(dir, {
    standards: [{
      id: 's1',
      rules: [{
        id: 'r1', title: 't', severity: 'warn', description: 'd',
        applies_to: { paths: ['src/**'] }
      }]
    }],
    codeFiles: {
      'src/covered.js': 'x\n',
      'lib/uncovered.js': 'y\n',
      'tools/also-uncovered.js': 'z\n'
    }
  })
  const res = await INVENTORY.runTool({})
  assert.equal(res.uncovered_files.count, 2)
  assert.ok(res.uncovered_files.files.includes('lib/uncovered.js'))
  assert.ok(res.uncovered_files.files.includes('tools/also-uncovered.js'))
  assert.ok(!res.uncovered_files.files.includes('src/covered.js'))
}))

test('uncovered_files: when no standards exist, all source files are uncovered (up to cap)', withProject(async (dir) => {
  bootstrapKb(dir, {
    standards: [],
    codeFiles: { 'src/a.js': 'x\n', 'lib/b.js': 'y\n' }
  })
  const res = await INVENTORY.runTool({})
  assert.equal(res.uncovered_files.count, 2)
}))

test('uncovered_files: respects scope glob', withProject(async (dir) => {
  bootstrapKb(dir, {
    standards: [],
    codeFiles: {
      'fe/a.js': 'x\n',
      'be/b.js': 'y\n'
    }
  })
  const res = await INVENTORY.runTool({ scope: 'fe/**' })
  assert.equal(res.uncovered_files.count, 1)
  assert.equal(res.uncovered_files.files[0], 'fe/a.js')
}))

// ── Pending promotions ─────────────────────────────────────────────────────

test('pending_promotions: surfaces entries from the ledger, one row per (queue_key, file)', withProject(async (dir) => {
  bootstrapKb(dir, { standards: [], codeFiles: {} })
  // Source of truth for promotions is sync/standards-promotions.md (the ledger).
  // Write the file directly in the on-disk format so we exercise the parser
  // rather than the addPromotions() write path.
  writeFile(dir, 'knowledge/sync/standards-promotions.md', `<!-- AUTO-GENERATED -->

# Standards Promotions Ledger

## s1.r1

- **Standard:** \`s1\`
- **Rule:** \`r1\` — warn
- **Rule fingerprint:** \`sha256:abc\`
- **Files:**
  - \`src/x.js\` — promoted \`2026-04-26\`, note: "rule should narrow scope"
  - \`src/y.js\` — promoted \`2026-04-26\`, note: "rule should narrow scope"

## s3.r3

- **Standard:** \`s3\`
- **Rule:** \`r3\` — warn
- **Rule fingerprint:** \`sha256:def\`
- **Files:**
  - \`lib/z.js\` — promoted \`2026-04-25\`
`)

  const res = await INVENTORY.runTool({})
  assert.equal(res.pending_promotions.length, 3, JSON.stringify(res.pending_promotions))
  // Most recent first; multi-file s1.r1 produces one row per file
  assert.equal(res.pending_promotions[0].queue_key, 's1.r1')
  assert.equal(res.pending_promotions[0].standard_id, 's1')
  assert.equal(res.pending_promotions[0].rule_id, 'r1')
  assert.deepEqual(res.pending_promotions[0].originating_files, ['src/x.js'])
  assert.equal(res.pending_promotions[0].note, 'rule should narrow scope')
  assert.equal(res.pending_promotions[1].queue_key, 's1.r1')
  assert.deepEqual(res.pending_promotions[1].originating_files, ['src/y.js'])
  assert.equal(res.pending_promotions[2].queue_key, 's3.r3')
  assert.deepEqual(res.pending_promotions[2].originating_files, ['lib/z.js'])
}))

test('pending_promotions: empty list when no ledger exists', withProject(async (dir) => {
  bootstrapKb(dir, { standards: [], codeFiles: {} })
  const res = await INVENTORY.runTool({})
  assert.deepEqual(res.pending_promotions, [])
}))

// ── Read-only ───────────────────────────────────────────────────────────────

test('read-only: running inventory twice produces no file changes', withProject(async (dir) => {
  bootstrapKb(dir, {
    standards: [{
      id: 's1',
      rules: [{ id: 'r1', title: 't', severity: 'warn', description: 'd', applies_to: { paths: ['nonexistent/**'] } }]
    }],
    codeFiles: { 'lib/foo.js': 'x\n' }
  })

  // Snapshot the project state before
  const before = listAllFiles(dir)
  await INVENTORY.runTool({})
  const afterFirst = listAllFiles(dir)
  await INVENTORY.runTool({})
  const afterSecond = listAllFiles(dir)

  assert.deepEqual(afterFirst, before, 'first run must not change any files')
  assert.deepEqual(afterSecond, before, 'second run must not change any files')
}))

// ── Summary ─────────────────────────────────────────────────────────────────

test('summary counts standards, rules, and scanned files', withProject(async (dir) => {
  bootstrapKb(dir, {
    standards: [
      {
        id: 's1',
        rules: [
          { id: 'r1', title: 't', severity: 'warn', description: 'd', applies_to: { paths: ['src/**'] } },
          { id: 'r2', title: 't', severity: 'error', description: 'd', applies_to: { paths: ['src/**'] } }
        ]
      },
      {
        id: 's2',
        rules: [{ id: 'r1', title: 't', severity: 'info', description: 'd', applies_to: { paths: ['lib/**'] } }]
      }
    ],
    codeFiles: { 'src/a.js': 'x', 'lib/b.js': 'y' }
  })
  const res = await INVENTORY.runTool({})
  assert.equal(res.summary.standards_count, 2)
  assert.equal(res.summary.rules_count, 3)
  assert.equal(res.summary.source_files_scanned, 2)
}))

// Helper: list all files in the project recursively for diff
function listAllFiles(dir) {
  const result = {}
  function walk(d) {
    const entries = fs.readdirSync(d, { withFileTypes: true })
    for (const e of entries) {
      if (e.name === '.git') continue
      const full = path.join(d, e.name)
      if (e.isDirectory()) walk(full)
      else if (e.isFile()) {
        const rel = path.relative(dir, full)
        result[rel] = fs.statSync(full).mtimeMs + ':' + fs.statSync(full).size
      }
    }
  }
  walk(dir)
  return result
}
